### ISSUE TITLE
ARIMA fit failing for small set of data due to invalid maxlag

### ISSUE THREAD

**Issue by feathj** [statsmodels/statsmodels#1146]
I am not sure if this is expected behavior or not, but ARIMA models which have endog of length less than or equal to 5 will always fail due to maxlag < nobs check.

Maxlag is calculated with the following value if not provided:

``` python
int(round(12*(nobs/100.)**(1/4.)))
```

Since the call to the parent "fit" method does not explicitly pass the maxlag argument, it is calculated using the formula above and results in this error:

```
error with ARIMA model (4, 1, 2):  maxlag should be < nobs
Traceback (most recent call last):
  File "/Users/jfeatherstone/dev/deos/post_processing/market_data/mrforecaster.py", line 126, in createModel
    results = model.fit(disp=-1, exog=range(1,len(items)), maxiter=100)
  File "/Users/jfeatherstone/dev/virtualenvs/deos/lib/python2.7/site-packages/statsmodels/tsa/arima_model.py", line 1005, in fit
    full_output, disp, callback, **kwargs)
  File "/Users/jfeatherstone/dev/virtualenvs/deos/lib/python2.7/site-packages/statsmodels/tsa/arima_model.py", line 828, in fit
    start_params = self._fit_start_params((k_ar,k_ma,k), method)
  File "/Users/jfeatherstone/dev/virtualenvs/deos/lib/python2.7/site-packages/statsmodels/tsa/arima_model.py", line 453, in _fit_start_params
    start_params = self._fit_start_params_hr(order)
  File "/Users/jfeatherstone/dev/virtualenvs/deos/lib/python2.7/site-packages/statsmodels/tsa/arima_model.py", line 399, in _fit_start_params_hr
    armod = AR(endog).fit(ic='bic', trend='nc')
  File "/Users/jfeatherstone/dev/virtualenvs/deos/lib/python2.7/site-packages/statsmodels/tsa/ar_model.py", line 548, in fit
    k_ar = self.select_order(k_ar, ic, trend, method)
  File "/Users/jfeatherstone/dev/virtualenvs/deos/lib/python2.7/site-packages/statsmodels/tsa/ar_model.py", line 425, in select_order
    X = self._stackX(maxlag, trend) # sets k_trend
  File "/Users/jfeatherstone/dev/virtualenvs/deos/lib/python2.7/site-packages/statsmodels/tsa/ar_model.py", line 393, in _stackX
    X = lagmat(endog, maxlag=k_ar, trim='both')
  File "/Users/jfeatherstone/dev/virtualenvs/deos/lib/python2.7/site-packages/statsmodels/tsa/tsatools.py", line 305, in lagmat
    raise ValueError("maxlag should be < nobs")
ValueError: maxlag should be < nobs
```

Note that an arima call in "R" with 5 items completes successfully.

**Comment by manishajohn** [comment]
I have the sales input data for 2 years say for 2014-2015 from month 04(April)-12(Dec) and need to forecast the value for the year 2016.
In this case,i have only small amount of data say less than 50 rows.
For this i am getting the error "ValueError: maxlag should be < nobs" ,so i browsed and found that i need to set the lesser maxlag value,but have no clue where to set it.
Already tried setting it in fit(maxlag=intValue,ic='bic') but it is not getting assigned with the new value and again the same error.
Where i need to and how i should set it actually?
Please help.
Looking for your response.
This is the code i tried:
def test_final_output():
    df = pd.read_csv('../../data/salesoneproduct.csv', index_col=0)
    nobs=len(df)
    df.index.name=None
    df.reset_index(inplace=True)
    start = datetime.datetime.strptime("2014-04-01", "%Y-%m-%d")
    date_list = [start + relativedelta(months=x) for x in range(0,48)]
    df['index'] =date_list
    df.set_index(['index'], inplace=True)
    df.index.name=None
    df.columns= ['riders']
    df['riders'] = df.riders.apply(lambda x: int(x)*100)
    mod = sm.tsa.statespace.SARIMAX(df.riders, trend='n', order=(0,1,0), seasonal_order=(1,1,1,12)
    results = mod.fit(ic='bic',maxlag=10)
    start = datetime.datetime.strptime("2019-04-01", "%Y-%m-%d")
    date_list = [start + relativedelta(months=x) for x in range(0,12)]
    future = pd.DataFrame(index=date_list, columns= df.columns)
    df = pd.concat([df, future])
    df['forecast'] = results.predict(start = 48, end = 59, dynamic= True)
    df[['riders', 'forecast']].ix[-24:].plot(figsize=(12, 8))
    print (df.forecast/100)
