### ISSUE TITLE
Test tsa.tests.test_ar.TestARMLEConstant.test_predict

### ISSUE THREAD

**Issue by sergiopasra** [statsmodels/statsmodels#1320]
The test statsmodels.tsa.tests.test_ar.TestARMLEConstant.test_predict fails in Fedora 20

```
In [2]: sm.version.full_version
Out[2]: '0.6.0.dev-b401d4d'In 

In [6]: sm.api.show_versions()

INSTALLED VERSIONS
------------------
Python: 2.7.5.final.0
OS: Linux 3.12.7-300.fc20.x86_64 #1 SMP Fri Jan 10 15:35:31 UTC 2014 x86_64
byteorder: little
LC_ALL: None
LANG: es_ES.utf8

Statsmodels
===========

Installed: 0.6.0.dev-b401d4d (statsmodels)

Required Dependencies
=====================

cython: 0.19.2 (/usr/lib64/python2.7/site-packages/Cython)
numpy: 1.8.0 (/usr/lib64/python2.7/site-packages/numpy)
scipy: 0.12.1 (/usr/lib64/python2.7/site-packages/scipy)
pandas: 0.10.0 (/usr/lib64/python2.7/site-packages/pandas)
    dateutil: 1.5 (/usr/lib/python2.7/site-packages/dateutil)
patsy: 0.2.1 (/usr/lib/python2.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 1.3.0 (/usr/lib64/python2.7/site-packages/matplotlib)
cvxopt: Not installed

Developer Tools
================

IPython: 0.13.2 (/usr/lib/python2.7/site-packages/IPython)
    jinja2: 2.7.1 (/usr/lib/python2.7/site-packages/jinja2)
sphinx: 1.1.3 (/usr/lib/python2.7/site-packages/sphinx)
    pygments: 1.6 (/usr/lib/python2.7/site-packages/pygments)
nose: 1.3.0 (/usr/lib/python2.7/site-packages/nose)
virtualenv: 1.10.1 (/usr/lib/python2.7/site-packages)

```

And the stack trace is

```
======================================================================
FAIL: statsmodels.tsa.tests.test_ar.TestARMLEConstant.test_predict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/spr/devel/statsmodels/build/lib.linux-x86_64-2.7/statsmodels/tsa/tests/test_ar.py", line 127, in test_predict
    DECIMAL_4)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 454, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 811, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 4 decimals

(mismatch 0.323624595469%)
 x: array([  48.32445796,   12.66331955,   26.19584557,   30.74308239,
         35.68550603,   48.62065188,   67.61597863,   16.00186953,
         13.37599163,   11.2305071 ,    9.48771851,    9.05879904,...
 y: array([  48.3243,   12.6633,   26.1958,   30.743 ,   35.6854,   48.6206,
         67.6159,   16.0018,   13.376 ,   11.2305,    9.4877,    9.0588,
          8.7644,   11.2268,   20.9667,   23.5576,   36.9585,   50.0107,...
----------------------------------------------------------------------
```

**Comment by bashtage** [comment]
Long closed.
