### ISSUE TITLE
numdiff test failure

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1405]
In a run on python 3.3 numpy 1.7.1, scipy 0.12.0 pandas 0.13.1

I get two test failures in numdiff

precision problems ?

```
======================================================================
FAIL: statsmodels.tools.tests.test_numdiff.TestDerivativeFun.test_hess_fun1_fd
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Josef\testing\tox\py33\lib\site-packages\nose-1.3.0-py3.3.egg\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "E:\Josef\testing\tox\py33\lib\site-packages\statsmodels\tools\tests\test_numdiff.py", line 217, in test_hess_fun1_fd
    assert_almost_equal(hetrue, hefd, decimal=DEC3)
  File "E:\Josef\testing\tox\py33\lib\site-packages\numpy\testing\utils.py", line 452, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "E:\Josef\testing\tox\py33\lib\site-packages\numpy\testing\utils.py", line 812, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "E:\Josef\testing\tox\py33\lib\site-packages\numpy\testing\utils.py", line 645, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 3 decimals

(mismatch 11.111111111111114%)
 x: array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])
 y: array([[ 0.        , -0.00096591,  0.00019104],
       [-0.00096591, -0.00157126, -0.00019422],
       [ 0.00019104, -0.00019422,  0.00067223]])

======================================================================
FAIL: statsmodels.tools.tests.test_numdiff.TestGradLogit.test_hess
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Josef\testing\tox\py33\lib\site-packages\nose-1.3.0-py3.3.egg\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "E:\Josef\testing\tox\py33\lib\site-packages\statsmodels\tools\tests\test_numdiff.py", line 64, in test_hess
    assert_allclose(he, hefd, rtol=5e-10)
  File "E:\Josef\testing\tox\py33\lib\site-packages\numpy\testing\utils.py", line 1179, in assert_allclose
    verbose=verbose, header=header)
  File "E:\Josef\testing\tox\py33\lib\site-packages\numpy\testing\utils.py", line 645, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=5e-10, atol=0

(mismatch 100.0%)
 x: array([[ -2.96566711e+01,  -1.98886470e+02,  -2.37019378e+00,
         -1.00365370e+01],
       [ -1.98886470e+02,  -1.38337697e+03,  -1.59229215e+01,...
 y: array([[ -2.96566711e+01,  -1.98886470e+02,  -2.37019378e+00,
         -1.00365370e+01],
       [ -1.98886470e+02,  -1.38337697e+03,  -1.59229214e+01,...
```

**Comment by josef-pkt** [comment]
first failure is also reported here.

it seems to be gone, so closing.
