### ISSUE TITLE
GLM families link classes

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1509]
Why can I not use the class?

it works with the instance `sm.families.links.log`

```
>>> mod_glm = sm.GLM(y, x, family=sm.families.Gaussian(link=sm.families.links.Log))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\genmod\families\family.py", line 408, in __init__
    self.link = link()
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\genmod\families\family.py", line 60, in _setlink
    raise ValueError(errmsg % (`self.links`, link))
ValueError: Invalid link for family, should be in [<class 'statsmodels.genmod.families.links.log'>, <class 'statsmodels.genmod.families.links.identity'>, <class 'statsmodels.genmod.families.links.inverse_power'>]. (got <statsmodels.genmod.families.links.Log object at 0x06443830>)
```

**Comment by bashtage** [comment]
Fixed by PR #7579 (clear TypeError when a link class rather than instance is passed to a Family) and PR #7816 (unified the capitalized/lowercase link-alias validity lists). Closing as fixed.
