### ISSUE TITLE
BUG: missing asarray in exposure

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1711]
I get an exception with  pandas 0.12.
Is it supported?

```
>>> pd.__version__
'0.12.0'
```

```
import StringIO

import numpy as np
import pandas as pd

from statsmodels.discrete.discrete_model import Poisson

ss='''\
agecat  smokes  deaths  pyears
1   1   32  52407
2   1   104 43248
3   1   206 28612
4   1   186 12663
5   1   102 5317
1   0   2   18790
2   0   12  10673
3   0   28  5710
4   0   28  2585
5   0   31  1462'''

data = pd.read_csv(StringIO.StringIO(ss), delimiter='\t')

mod = Poisson.from_formula('deaths ~ smokes + agecat', data=data, 
                           exposure=data['pyears']) #.values)

res0 = mod.fit()
```

```
Traceback (most recent call last):
  File "E:\Josef\eclipsegworkspace\statsmodels-git\local_scripts\local_scripts\ex_poisson_constrained.py", line 35, in <module>
    res0 = mod.fit()
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\discrete\discrete_model.py", line 916, in fit
    disp=disp, callback=callback, **kwargs)
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\discrete\discrete_model.py", line 168, in fit
    disp=disp, callback=callback, **kwargs)
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\base\model.py", line 390, in fit
    full_output=full_output)
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\base\optimizer.py", line 184, in _fit
    hess=hessian)
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\base\optimizer.py", line 237, in _fit_newton
    H = hess(newparams)
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\base\model.py", line 378, in <lambda>
    hess = lambda params: self.hessian(params) / nobs
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\discrete\discrete_model.py", line 1024, in hessian
    return -np.dot(L*X.T, X)
  File "C:\Programs\Python27\lib\site-packages\pandas-0.12.0-py2.7-win32.egg\pandas\core\series.py", line 187, in wrapper
    index=self.index, name=self.name, dtype=dtype)
  File "C:\Programs\Python27\lib\site-packages\pandas-0.12.0-py2.7-win32.egg\pandas\core\series.py", line 477, in __new__
    raise_cast_failure=True)
  File "C:\Programs\Python27\lib\site-packages\pandas-0.12.0-py2.7-win32.egg\pandas\core\series.py", line 3404, in _sanitize_array
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional

>>> type(mod.exposure)
<class 'pandas.core.series.Series'>
```

**Comment by josef-pkt** [comment]
no idea, check

**Comment by josef-pkt** [comment]
I don't get an exception with current master, and looks like it's working correctly, I get the same results with pandas + formula as with numpy arrays (using formula created endog and exog)

updated version in a notebook, no tab delimiter after copy past, python 3

-------
from statsmodels.compat import StringIO

import numpy as np
import pandas as pd

from statsmodels.discrete.discrete_model import Poisson

ss='''\
agecat  smokes  deaths  pyears
1   1   32  52407
2   1   104 43248
3   1   206 28612
4   1   186 12663
5   1   102 5317
1   0   2   18790
2   0   12  10673
3   0   28  5710
4   0   28  2585
5   0   31  1462'''

data = pd.read_csv(StringIO(ss), delim_whitespace=True)

mod = Poisson.from_formula('deaths ~ smokes + agecat', data=data, 
                           exposure=data['pyears'])

res0 = mod.fit()
-------------

**Comment by josef-pkt** [comment]
type(mod.exposure) is ndarray now
I don't find any related asarray in discrete_model, so this will come most likely from data handling in super.

2-D, 1 column exposure fails both with pandas DataFrame and with numpy array
