### ISSUE TITLE
dtype complex: statsmodels.api.Probit leads to _flapack.error in scipy.linag.decomp_svd.py

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#1838]
Amateur user, first time submitting to an issue tracker.  Please let me know if more/different information is needed to be useful.

X and Y are numpy matrices.  The columns of X are constructed so as to be uncorrelated.  The following error persists if I drop one or more columns of X.  The same error also occurs if I use statsmodels.api.Logit instead of Probit.

```
>>>X.shape
(92007, 7)
>>>Y.shape
(1,92007)

>>> model = statsmodels.api.Probit(Y, X)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/statsmodels/discrete/discrete_model.py", line 117, in __init__
    super(DiscreteModel, self).__init__(endog, exog, **kwargs)
  File "/Library/Python/2.7/site-packages/statsmodels/base/model.py", line 137, in __init__
    self.initialize()
  File "/Library/Python/2.7/site-packages/statsmodels/discrete/discrete_model.py", line 126, in initialize
    self.df_model = float(tools.rank(self.exog) - 1)  # assumes constant
  File "/Library/Python/2.7/site-packages/statsmodels/tools/tools.py", line 381, in rank
    D = svdvals(X)
  File "/Library/Python/2.7/site-packages/scipy/linalg/decomp_svd.py", line 146, in svdvals
    check_finite=check_finite)
  File "/Library/Python/2.7/site-packages/scipy/linalg/decomp_svd.py", line 100, in svd
    full_matrices=full_matrices, overwrite_a=overwrite_a)
_flapack.error: (lwork>=(compute_uv?2*minmn*minmn+MAX(m,n)+2*minmn:2*minmn+MAX(m,n))) failed for 3rd keyword lwork: zgesdd:lwork=1547


>>> statsmodels.__version__
'0.5.0'
>>> scipy.__version__
'0.14.0'
>>> numpy.__version__
'1.8.1'
>>> platform.platform()
'Darwin-13.3.0-x86_64-i386-64bit'
```

**Comment by jbrockmendel** [comment]
Pretty sure this was user error, closing.
