### ISSUE TITLE
_get_predict_out_of_sample bug?

### ISSUE THREAD

**Issue by BlondeLlama** [statsmodels/statsmodels#1879]
Hi statsmodels-experts,

I am new to statsmodels, so I am not entairly sure this is a bug or just me messing up.
Anyway, when executing the script below,  the exog and exparams in _get_predict_out_of_sample do not align during a np.dot function.
exog and exparams are both pandas.Series and I have added their shape at the end of the page.
I am not sure how pandas uses the dot function, so maybe can point out what goes wrong and give a workaround?

Thanks in advance!
______________________________

    import sys
    import pandas as pd
    pd.options.display.mpl_style= 'default'
    sys.path.append("C:\\Users\\XXX\\Documents\\diveintopython-5.4\\py")
    from SOBEK_Results import CSV_read
    from SOBEK_BUI import BUI_read

    print "read BUI data"

    BUIfile = "f:\\Docs\\uurgeg_350_2011-2020.BUI"

    default, event, names, rtable = BUI_read(BUIfile)

    print "read Discharge data"

    dfQ2 = CSV_read(filename = "C:\\Users\\Jeroen\\Documents\\ArcGIS\\SBK_1DFlowQ2.csv", header=4)
    #dfQ2.columns = ['place1' ,'place2', 'place3']
    dfQ2.sort_index(axis=1, inplace=True)

    dfQ3 = CSV_read(filename = "C:\\Users\\Jeroen\\Documents\\ArcGIS\\SBK_1DFlowQ3.csv", header=4)
    #dfQ3.columns = ['place1', 'place2', 'place3']
    dfQ3.sort_index(axis=1, inplace=True)

    period = pd.to_datetime('2013-1-1 00:00:00', dayfirst=True) - pd.to_datetime('2011-01-01 00:00:00', dayfirst=True)
    period = period.days * 24

    print "Decide order"

    import statsmodels.api as sm
    import statsmodels.tsa.arima_model as arima
    from statsmodels.tsa.stattools import arma_order_select_ic
    #res = arma_order_select_ic(y = dfQ2.ix[0:period,0], max_ar = 6, max_ma = 4,
                                #ic=['aic', 'bic'], trend='nc', 
                                #model_kw = {'exog': dfQ3.ix[0:period,0], 'freq': 'H'})
    #print str(res.aic_min_order)
    #print str(res.bic_min_order)

    print "fit ARMA model"
    armaQ20 = arima.ARMA(endog = dfQ2.ix[0:period,0], order = (4,2),
                exog = dfQ3.ix[0:period,0]).fit(disp=0, trend='nc', start_params=None)

    #armaQ20.resid.plot()
    print (armaQ20.aic, armaQ20.bic, armaQ20.hqic)
    print "params/n%s " % str(armaQ20.params)

    print "predict ARMA"
    #this is the nsteps ahead predictor function
    from statsmodels.tsa.arima_model import _arma_predict_out_of_sample

    #get what you need for predicting one-step ahead
    params = armaQ20.params
    residuals = armaQ20.resid
    p = armaQ20.k_ar
    q = armaQ20.k_ma
    k_exog = armaQ20.k_exog
    k_trend = armaQ20.k_trend
    steps = 1

    start = pd.to_datetime('2013 1 1', dayfirst=True)
    end = pd.to_datetime('2013 7 1', dayfirst=True)

    armapred = _arma_predict_out_of_sample(params, steps, residuals,
                                        p, q, k_trend, k_exog,
                                        endog=dfQ2.ix[0:period,0],
                                        exog=dfQ3.ix[0:period,0],
                                        start=len(dfQ2.ix[0:period,0]))
    print end

    ______________________

    Traceback (most recent call last):
    File "C:\Users\Jeroen\Documents\diveintopython-5.4\py\Test_Predict.py", line 69, in <module>
        start=len(dfQ2.ix[0:period,0]))
    File "C:\Python27\64bit\lib\site-packages\statsmodels\tsa\arima_model.py", line 261, in _arma_predict_out_of_sample
        exog)
    File "C:\Python27\64bit\lib\site-packages\statsmodels\tsa\arima_model.py", line 233, in _get_predict_out_of_sample
        X = np.dot(exog, exparams)
    ValueError: matrices are not aligned
    _____________

    exog:
    DATE:
    2011-01-01 00:00:00    0
    2011-01-01 01:00:00    0
    2011-01-01 02:00:00    0
    2011-01-01 03:00:00    0
    2011-01-01 04:00:00    0
    2011-01-01 05:00:00    0
    2011-01-01 06:00:00    0
    2011-01-01 07:00:00    0
    2011-01-01 08:00:00    0
    2011-01-01 09:00:00    0
    2011-01-01 10:00:00    0
    2011-01-01 11:00:00    0
    2011-01-01 12:00:00    0
    2011-01-01 13:00:00    0
    2011-01-01 14:00:00    0
    ...
    2012-12-31 09:00:00    53.57692
    2012-12-31 10:00:00    51.37471
    2012-12-31 11:00:00    50.72179
    2012-12-31 12:00:00    50.91718
    2012-12-31 13:00:00    48.81682
    2012-12-31 14:00:00    47.00536
    2012-12-31 15:00:00    47.10442
    2012-12-31 16:00:00    46.92752
    2012-12-31 17:00:00    45.99190
    2012-12-31 18:00:00    45.78441
    2012-12-31 19:00:00    46.60528
    2012-12-31 20:00:00    46.54289
    2012-12-31 21:00:00    50.83975
    2012-12-31 22:00:00    55.38880
    2012-12-31 23:00:00    58.72393
    Name: place1, Length: 17544
    exparams:
    19_116    0.090554
    dtype: float64
______________________

**Comment by jseabold** [comment]
Please re-open if you can provide more information.
