### ISSUE TITLE
TST: occasional failure in test_numdiff.TestGradLogit.test_hess

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1893]
I get the following failure every once in a while
I don't get it very often, and never when I try specifically those tests

reduce rtol? or try to reproduce and investigate?

```
======================================================================
FAIL: statsmodels.tools.tests.test_numdiff.TestGradLogit.test_hess
----------------------------------------------------------------------
Traceback (most recent call last):
  File "e:\josef\testing\tox\py27e\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "e:\josef\testing\tox\py27e\lib\site-packages\statsmodels-0.6.0-py2.7-win32.egg\statsmodels\tools\tests\test_numdiff.py", line 64, in test_hess
    assert_allclose(he, hefd, rtol=5e-10)
  File "e:\josef\testing\tox\py27e\lib\site-packages\numpy-1.8.2-py2.7-win32.egg\numpy\testing\utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "e:\josef\testing\tox\py27e\lib\site-packages\numpy-1.8.2-py2.7-win32.egg\numpy\testing\utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=5e-10, atol=0

(mismatch 100.0%)
 x: array([[ -2.96566711e+01,  -1.98886470e+02,  -2.37019378e+00,
         -1.00365370e+01],
       [ -1.98886470e+02,  -1.38337697e+03,  -1.59229215e+01,...
 y: array([[ -2.96566711e+01,  -1.98886470e+02,  -2.37019378e+00,
         -1.00365370e+01],
       [ -1.98886470e+02,  -1.38337697e+03,  -1.59229215e+01,...
```

**Comment by jbrockmendel** [comment]
I don't recall seeing this error anytime recently.  Closeable?

**Comment by bashtage** [comment]
Appears to be fixed in master. No errors on this in a long time.
