### ISSUE TITLE
BUG f_value, ftest/wald_test against implicit constant

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1988]
see part of the comments in #1212

The f_value with robust covariance is based on the wald_test.
If we have k_constant=True but no const_idx, then it raises an exception when it tries to use const_idx to index into an array. 

My guess is that we need a helper function that calculates the linear restriction of the current model against an implicit constant only model. (I'm not sure yet what this will look like, just two lines of linalg)

not directly replicable changes to a test case

```
======================================================================
ERROR: statsmodels.regression.tests.test_robustcov.TestWLSOLSRobustSmall.test_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\programs\python27\lib\site-packages\nose-1.0.0-py2.7.egg\nose\case.py", line 187, in runTest
    self.test(*self.arg)
  File "E:\Josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\regression\tests\test_robustcov.py", line 763, in test_all
    assert_allclose(res1.f_pvalue, res2.f_pvalue, rtol=1e-13)
  File "E:\Josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\tools\decorators.py", line 94, in __get__
    _cachedval = self.fget(obj)
  File "E:\Josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\regression\linear_model.py", line 1218, in f_pvalue
    return stats.f.sf(self.fvalue, self.df_model, self.df_resid)
  File "E:\Josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\tools\decorators.py", line 94, in __get__
    _cachedval = self.fget(obj)
  File "E:\Josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\regression\linear_model.py", line 1206, in fvalue
    idx.pop(const_idx)
TypeError: an integer is required
```

**Comment by bashtage** [comment]
There is no longer a crash, and the difference is expected.  It is not possible to get OLS to calculate a "wrong" f-stat when it doesn't get an actual constant column.
