### ISSUE TITLE
cvxopt test failure

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2033]
Yaroslav on the mailing list

on s390x just a single failure atm

```
======================================================================
FAIL: statsmodels.discrete.tests.test_discrete.TestCVXOPT.test_cvxopt_versus_slsqp
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/statsmodels/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/discrete/tests/test_discrete.py", line 510, in test_cvxopt_versus_slsqp
    assert_almost_equal(res_slsqp.params, res_cvxopt.params, DECIMAL_4)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 454, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 811, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 4 decimals

(mismatch 50.0%)
 x: array([-4.10274719,  0.        ,  0.15493873,  0.        ])
 y: array([-0.30976854,  0.        ,  0.        ,  0.        ])
```

**Comment by bashtage** [comment]
There haven't been any complaints about this in a long time, so closing as self-solved.
