### ISSUE TITLE
TST failure Edgeworth expansion on debian

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2106]
http://nipy.bic.berkeley.edu/builders/statsmodels-py2.7-wheezy-sparc/builds/126/steps/shell_7/logs/stdio

```
======================================================================
ERROR: test_chi2_moments (statsmodels.distributions.tests.test_edgeworth.TestExpandedNormal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/nd-bb-slave-sparc-wheezy/statsmodels-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-sparc64.egg/statsmodels/distributions/tests/test_edgeworth.py", line 123, in test_chi2_moments
    check_pdf(ne, arg=(), msg='')
  File "/home/buildslave/nd-bb-slave-sparc-wheezy/statsmodels-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-sparc64.egg/statsmodels/distributions/tests/test_edgeworth.py", line 153, in check_pdf
    median = distfn.ppf(0.5, *arg)
  File "/usr/lib/python2.7/dist-packages/scipy/stats/distributions.py", line 1516, in ppf
    place(output,cond,self._ppf(*goodargs)*scale + loc)
  File "/usr/lib/python2.7/dist-packages/scipy/stats/distributions.py", line 1212, in _ppf
    return self.vecfunc(q,*args)
  File "/home/buildslave/nd-bb-slave-sparc-wheezy/statsmodels-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1700, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/buildslave/nd-bb-slave-sparc-wheezy/statsmodels-py2_7-wheezy-sparc/build/venv/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1769, in _vectorize_call
    outputs = ufunc(*inputs)
  File "/usr/lib/python2.7/dist-packages/scipy/stats/distributions.py", line 1158, in _ppf_single_call
    return optimize.brentq(self._ppf_to_solve, self.xa, self.xb, args=(q,)+args, xtol=self.xtol)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/zeros.py", line 366, in brentq
    r = _zeros._brentq(f,a,b,xtol,maxiter,args,full_output,disp)
ValueError: f(a) and f(b) must have different signs
```

**Comment by josef-pkt** [comment]
there is no failure right now on nipy debian, even with the same scipy version.

reopen if it shows up during 0.7rc testing across machines
