### ISSUE TITLE
order selection for AR model raises exception

### ISSUE THREAD

**Issue by debjan** [statsmodels/statsmodels#2118]
I have time series data:

``` pytb
>>> ts.describe()
count     1093.000000
mean     26814.123139
std      17044.026136
min        699.098200
25%      14313.080000
50%      21469.620000
75%      36069.570000
max      96611.610000
dtype: float64
>>> ts.index
<class 'pandas.tseries.index.DatetimeIndex'>
[2005-07-01, ..., 2008-06-30]
Length: 1093, Freq: None, Timezone: None
```

and I want to see suggested order for supposed AR process:

``` pytb
>>> ar = sm.tsa.AR(ts)
>>> ar.select_order(maxlag=12, ic='aic')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/statsmodels-0.6.0-py2.7-linux-x86_64.egg/statsmodels/tsa/ar_model.py", line 435, in select_order
    maxiter=100, disp=0)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels-0.6.0-py2.7-linux-x86_64.egg/statsmodels/tsa/ar_model.py", line 584, in fit
    params = self._transparams(params)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels-0.6.0-py2.7-linux-x86_64.egg/statsmodels/tsa/ar_model.py", line 94, in _transparams
    newparams = params.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

Apparently `params = mlefit.params` is passed to `fit()` as `None`, which as such doesn't have `copy()` method. So why does this happen, are there some prerequisites to using this function, not explained in the docs?

Thanks

**Comment by cstich** [comment]
I also just bumped into this.

**Comment by punyidea** [comment]
I also ran into this bug. Has there been any progress in fixing it?

**Comment by josef-pkt** [comment]
Did you try this with current master?

**Comment by punyidea** [comment]
No, I suppose not. Only the currently-released package that I installed with pip.
