### ISSUE TITLE
Failure: TypeError (<functools.partial object at 0x2ba14414df18> is not a function or method) ... ERROR

### ISSUE THREAD

**Issue by yarikoptic** [statsmodels/statsmodels#2121]
never saw such a beast... while building/testing 0.6.1 on ubuntus, both recent ones spit out into my face:

```
statsmodels.nonparametric.tests.test_kernels.TestUniform.test_smoothconf ... ok
Failure: TypeError (<functools.partial object at 0x2ba14414df18> is not a function or method) ... ERROR
Failure: TypeError (<functools.partial object at 0x2ba14414d100> is not a function or method) ... ERROR
Failure: TypeError (<functools.partial object at 0x2ba141b70c00> is not a function or method) ... ERROR
Failure: TypeError (<functools.partial object at 0x2ba143c6e6d8> is not a function or method) ... ERROR
Failure: TypeError (<functools.partial object at 0x2ba143c6e158> is not a function or method) ... ERROR
Failure: TypeError (<functools.partial object at 0x2ba143c6e6d8> is not a function or method) ... ERROR
Failure: TypeError (<functools.partial object at 0x2ba143c6e158> is not a function or method) ... ERROR
Failure: TypeError (<functools.partial object at 0x2ba143c6e6d8> is not a function or method) ... ERROR
statsmodels.nonparametric.tests.test_lowess.TestLowess.test_flat ... ok
statsmodels.nonparametric.tests.test_lowess.TestLowess.test_import ... ok
...
SKIP: X13/X12 not available

======================================================================
ERROR: Failure: TypeError (<functools.partial object at 0x2ba14414df18> is not a function or method)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
TypeError: <functools.partial object at 0x2ba14414df18> is not a function or method

======================================================================
ERROR: Failure: TypeError (<functools.partial object at 0x2ba14414d100> is not a function or method)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
TypeError: <functools.partial object at 0x2ba14414d100> is not a function or method
...
```
what are those about?  not working parametric tests?

diff shows that those are for
```
-test_simple ... ok
-test_iter_0 ... ok
-test_iter_0 ... ok
-test_frac_2_3 ... ok
-test_frac_1_5 ... ok
-test_delta_0 ... ok
-test_delta_Rdef ... ok
-test_delta_1 ... ok
```
may be nose too old? (e.g. 1.3.1)

**Comment by josef-pkt** [comment]
TODO for 0.7: check whether we cannot easily rewrite the tests to avoid this.
(I lived my life without `partial`)

**Comment by jseabold** [comment]
Just now seeing this. I haven't seen this with pip install nose 1.3.1 or 1.3.4 on Python 3, so it may even be the repo nose? There's only this old bug report and no action.

https://github.com/nose-devs/nose/issues/114

**Comment by josef-pkt** [comment]
I assume the nose issue got fixed but the ticket wasn't closed.

I had the problem with my ancient nose 1.x

**Comment by jseabold** [comment]
Ah, well simple enough fix. Don't yield partial funcs to nose. Submitted a patch.
