### ISSUE TITLE
Fail more gracefully on bad exog for ARMAX.

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#2129]
See example [here](https://stackoverflow.com/questions/27057445/how-to-fit-an-armax-model-using-statsmodels/).

**Comment by Juanlu001** [comment]
This issue is no longer present in 0.10.0:

```
$ cat test.py
import numpy as np
import statsmodels.api as sm
# some stupid data

y = np.random.randn(100)
u = np.ones((100,2))
armax = sm.tsa.ARMA(y, order=(1, 1), exog=u).fit()
$ python test.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/.pyenv/versions/st37/lib/python3.7/site-packages/statsmodels/tsa/arima_model.py", line 904, in fit
    k_trend, exog = _make_arma_exog(endog, self.exog, trend)
  File "/home/juanlu/.pyenv/versions/st37/lib/python3.7/site-packages/statsmodels/tsa/arima_model.py", line 397, in _make_arma_exog
    exog = add_trend(exog, trend='c', prepend=True, has_constant='raise')
  File "/home/juanlu/.pyenv/versions/st37/lib/python3.7/site-packages/statsmodels/tsa/tsatools.py", line 108, in add_trend
    raise ValueError(msg)
ValueError: x contains a constant. Adding a constant with trend='c' is not allowed.
```

**Comment by Juanlu001** [comment]
Specifically, it was fixed in https://github.com/statsmodels/statsmodels/commit/119fcf90b218b95e48897a6fcaff6ef64dfd314c

**Comment by bashtage** [comment]
Closing as fixed.
