### ISSUE TITLE
ols prediction with nan

### ISSUE THREAD

**Issue by adrianschlatter** [statsmodels/statsmodels#2171]
Apparently, when the data used to estimate an ols model has NaNs, prediction will not work. Not even if the exog data used for prediction does *not* have NaNs.

This behavior occurs with statsmodels 0.6.1.

Example:

```
import numpy as np
import statsmodels.formula.api as sm
import pandas as pd

np.random.seed(9876789)
nsample = 100

# Create exog data:

data = pd.DataFrame( { 'x': np.linspace(0, 10, nsample) } )
null = pd.DataFrame( { 'x': np.array( [np.nan] ) } )
data = pd.concat( [data, null] )

# Create endog data:

beta = np.array([1, 0.1])
e = np.random.normal(size=nsample+1)
data['y'] = beta[0] + beta[1]*data['x'] + e

# Model:

model = sm.ols( 'y ~ x', data=data)
fit = model.fit()

# Predict:

fit.predict( exog=data[:-1] ) # fails
```

Traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/adrian/Desktop/ToDo/statsmodels_debugging/OLS.py", line 34, in <module>
    fit.predict( exog=data[:-1] ) # fails
  File "/usr/local/lib/python2.7/dist-packages/statsmodels-0.6.1-py2.7-linux-i686.egg/statsmodels/base/model.py", line 739, in predict
    exog = dmatrix(self.model.data.orig_exog.design_info.builder,
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 1936, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataFrame' object has no attribute 'design_info'
```

**Comment by josef-pkt** [comment]
maybe related to  #1263

longer term solution
we need to store design_info separate from the data arrays/frames.

We also have other issues for this I think

Thanks for the report
