### ISSUE TITLE
ImportError: cannot import name 'calc_lwork'

### ISSUE THREAD

**Issue by kousu** [statsmodels/statsmodels#2191]
I'm on Arch. I have these versions installed:
[kousu@galleon]$ pacman -Q python-scipy python-statsmodels
python-scipy 0.15.0-1
python-statsmodels 0.6.1-1

I cannot use statsmodels because scipy has refactored. I guess this is partly the fault of the Arch packagers for not checking this first, but just in case you weren't aware of it:
```
Python 3.4.2 (default, Jan 12 2015, 11:38:40) 
[GCC 4.9.2 20141224 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> impot statsmodels.api
  File "<stdin>", line 1
    impot statsmodels.api
                    ^
SyntaxError: invalid syntax
>>> import statsmodels.api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/statsmodels/api.py", line 15, in <module>
    from .tsa import api as tsa
  File "/usr/lib/python3.4/site-packages/statsmodels/tsa/api.py", line 5, in <module>
    from .vector_ar.var_model import VAR
  File "/usr/lib/python3.4/site-packages/statsmodels/tsa/vector_ar/var_model.py", line 23, in <module>
    from statsmodels.tools.linalg import logdet_symm
  File "/usr/lib/python3.4/site-packages/statsmodels/tools/linalg.py", line 23, in <module>
    from scipy.linalg import calc_lwork
ImportError: cannot import name 'calc_lwork'
>>> 
```

For now, this simple workaround seems to be alright:
```
>>> import scipy.lib.lapack.calc_lwork
>>> scipy.linalg.calc_lwork = scipy.lib.lapack.calc_lwork
>>> import statsmodels.api
```

**Comment by josef-pkt** [comment]
see #2184

nice trick with the monkey patching the missing function

closing as duplicate

**Comment by josef-pkt** [comment]
scipy 0.15.1 with the fix should be on the way.
