### ISSUE TITLE
TST: precision in test for SARIMAX

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2257]
appveyor testing might have problems

one precision issue in nipy Debian testing
http://nipy.bic.berkeley.edu/builders/statsmodels-py2.x-sid-sparc/builds/289/steps/shell_5/logs/stdio

```
======================================================================
FAIL: statsmodels.tsa.statespace.tests.test_sarimax.Test_seasonal_arma_trend_ct.test_loglike
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/nd-bb-slave-sparc64-sid/statsmodels-py2_x-sid-sparc/build/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/buildslave/nd-bb-slave-sparc64-sid/statsmodels-py2_x-sid-sparc/build/venv/local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-sparc64.egg/statsmodels/tsa/statespace/tests/test_sarimax.py", line 561, in test_loglike
    self.decimal
  File "/home/buildslave/nd-bb-slave-sparc64-sid/statsmodels-py2_x-sid-sparc/build/venv/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 490, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 4 decimals
 ACTUAL: -277.63055030066369
 DESIRED: -277.63049999999998

```

**Comment by bashtage** [comment]
Hasn't shown up for a long time, so likely long fixed.
