### ISSUE TITLE
doc build warnings

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2309]
doc build problems currently in master   (new install in a Mint Linux virtualbox)

I didn't log notebook conversion which mentions exceptions in several notebooks

```
VirtualBox ~/develop/statsmodels-git/statsmodels/docs $ make html >log1.txt
WARNING: [autosummary] failed to import 'statsmodels.tools.tools.ECDF': no module named statsmodels.tools.tools.ECDF
WARNING: [autosummary] failed to import 'statsmodels.tools.tools.monotone_fn_inverter': no module named statsmodels.tools.tools.monotone_fn_inverter
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/datasets/generated/fair.rst:47: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/dev/git_notes.rst:2: WARNING: Duplicate explicit target name: "this page".
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/duration.rst:34: WARNING: toctree contains reference to nonexisting document u'examples/notebooks/generated'
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/stats/stattools.py:docstring of statsmodels.stats.stattools.medcouple:29: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/stats/stattools.py:docstring of statsmodels.stats.stattools.robust_kurtosis:76: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/stats/stattools.py:docstring of statsmodels.stats.stattools.robust_skewness:55: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/tools/pca.py:docstring of statsmodels.tools.pca.PCA:129: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/tools/tools.py:docstring of statsmodels.tools.tools.add_constant:19: WARNING: Inline literal start-string without end-string.
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/tools/tools.py:docstring of statsmodels.tsa.tsatools.add_constant:19: WARNING: Inline literal start-string without end-string.
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/mixed_linear.rst:46: WARNING: toctree contains reference to nonexisting document u'examples/notebooks/generated'
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/release/version0.6.rst:96: WARNING: Exception occurred in plotting version0-6-1
 from /home/adminuser/develop/statsmodels-git/statsmodels/docs/source/release/version0.6.rst:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/matplotlib/sphinxext/plot_directive.py", line 515, in run_code
    exec code in ns
  File "<string>", line 5, in <module>
  File "/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 2544, in interpolate
    return res
UnboundLocalError: local variable 'res' referenced before assignment
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/release/version0.6.rst:151: WARNING: Exception occurred in plotting version0-6-2
 from /home/adminuser/develop/statsmodels-git/statsmodels/docs/source/release/version0.6.rst:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/matplotlib/sphinxext/plot_directive.py", line 515, in run_code
    exec code in ns
  File "<string>", line 4, in <module>
  File "/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 2544, in interpolate
    return res
UnboundLocalError: local variable 'res' referenced before assignment
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/release/version0.7.rst:69: ERROR: GitHub issue number must be a number greater than or equal to 1; "XXX" is invalid.
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/tools.rst:33: WARNING: failed to import tools.ECDF
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/tools.rst:33: WARNING: failed to import tools.monotone_fn_inverter
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/tools.rst:33: WARNING: toctree references unknown document u'generated/tools.ECDF'
/home/adminuser/develop/statsmodels-git/statsmodels/docs/source/tools.rst:33: WARNING: toctree references unknown document u'generated/tools.monotone_fn_inverter'
WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting
WARNING: LaTeX command 'latex' cannot be run (needed for math display), check the pngmath_latex setting
None:None: WARNING: toctree contains reference to nonexisting document u'generated/tools.ECDF'
None:None: WARNING: toctree contains reference to nonexisting document u'generated/tools.monotone_fn_inverter'
<autosummary>:None: WARNING: toctree contains reference to nonexisting document u'generated/tools.ECDF'
<autosummary>:None: WARNING: toctree contains reference to nonexisting document u'generated/tools.monotone_fn_inverter'
```

**Comment by josef-pkt** [comment]
one notebook problem:

```
Writing  pca_fertility_factors
ran notebook 
    ran  13 cells
    there were no errors in run_cell
      3 cells have exceptions in their output
Title not in first cell for  pca_fertility_factors
Not generating rST
```

**Comment by bashtage** [comment]
Will look at that NB

**Comment by bashtage** [comment]
I don't get any exceptions.  Does the converter expect a Heading1 in the first cell?

**Comment by bashtage** [comment]
I will also look at 
```
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/stats/stattools.py:docstring of statsmodels.stats.stattools.medcouple:29: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/stats/stattools.py:docstring of statsmodels.stats.stattools.robust_kurtosis:76: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/stats/stattools.py:docstring of statsmodels.stats.stattools.robust_skewness:55: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/tools/pca.py:docstring of statsmodels.tools.pca.PCA:129: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/tools/tools.py:docstring of statsmodels.tools.tools.add_constant:19: WARNING: Inline literal start-string without end-string.
/home/adminuser/.local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/tools/tools.py:docstring of statsmodels.tsa.tsatools.add_constant:19: WARNING: Inline literal start-string without end-string.
```

which I wrote a while ago

**Comment by josef-pkt** [comment]
I looked at the pca and, IIRC, the medcouple a few weeks ago, but couldn't find anything wrong.

I don't remember seeing the pca_fertility notebook error before, but I guess the rst style underline header is not compatible with the ipython markup to rst conversion.

**Comment by josef-pkt** [comment]
spot checking several notebooks: They all start with a `heading 1` line, so I guess (!) it's required.
