### ISSUE TITLE
bug or uncaught exception when plotting formula w/o constant

### ISSUE THREAD

**Issue by nitroamos** [statsmodels/statsmodels#2364]
Thanks for the great tool! I've been learning how to use it the last few days. I've encountered a problem. I'm not sure if it's my fault, so apologies if it is!

Adapted from one of your examples:
```
from __future__ import print_function
from statsmodels.compat import lzip
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.formula.api import ols

prestige = sm.datasets.get_rdataset("Duncan", "car", cache=True).data

print(prestige.head())

prestige_model = ols("prestige ~ education -1", data=prestige).fit()
#prestige_model = ols("prestige ~ income + education", data=prestige).fit()

print(prestige_model.summary())

fig = plt.figure(figsize=(12,8))
fig = sm.graphics.plot_regress_exog(prestige_model, "education", fig=fig)
```

The code pasted above gives the error pasted below. If I uncomment the line, the error goes away.

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    fig = sm.graphics.plot_regress_exog(prestige_model, "education", fig=fig)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/graphics/regressionplots.py", line 211, in plot_regress_exog
    exog_others, obs_labels=False, ax=ax)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/graphics/regressionplots.py", line 339, in plot_partregress
    res_yaxis = OLS(endog, RHS).fit()
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/regression/linear_model.py", line 691, in __init__
    hasconst=hasconst, **kwargs)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/regression/linear_model.py", line 586, in __init__
    weights=weights, hasconst=hasconst, **kwargs)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/regression/linear_model.py", line 91, in __init__
    super(RegressionModel, self).__init__(endog, exog, **kwargs)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/base/model.py", line 186, in __init__
    super(LikelihoodModel, self).__init__(endog, exog, **kwargs)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/base/model.py", line 60, in __init__
    **kwargs)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/base/model.py", line 84, in _handle_data
    data = handle_data(endog, exog, missing, hasconst, **kwargs)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/base/data.py", line 566, in handle_data
    **kwargs)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/base/data.py", line 75, in __init__
    self._handle_constant(hasconst)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/base/data.py", line 135, in _handle_constant
    rank_orig = np_matrix_rank(self.exog)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 1500, in matrix_rank
    S = svd(M, compute_uv=False)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 1274, in svd
    _assertNonEmpty(a)
  File "/home/amosa/pkg/tools/python/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 170, in _assertNonEmpty
    raise LinAlgError("Arrays cannot be empty")
numpy.linalg.linalg.LinAlgError: Arrays cannot be empty
```

**Comment by josef-pkt** [comment]
Thanks for reporting

I had several power outages today and don't have the computer running right now. 
My guess

Several of these functions have never been checked for the case when there is only one explanatory variable (1 column exog)
AFAIR, we are partialling out the other explanatory variables in an auxiliary regression, but in this case the array of other explanatory variables is empty.

In some cases we might have to raise an exception, but, I think, in this case we could just skip the partialling out step. I guess the plots still make sense.

PR welcome. I think fixing this will not require to dig much into statsmodels. I will check the relevant code later.

**Comment by saketkc** [comment]
This kind of is fixed in https://github.com/saketkc/statsmodels/commit/1b5672da7abccc9039c39eb5e91715fe80e55239

I guess we keep the partial regression plot?
