### ISSUE TITLE
BUG: exception in WLS summary without constant

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2444]
**update**  #2477 sets fvalue to nan

see comments below, see #2482 for general issue

possible enhancement: figure out linear restriction for the implicit constant case

---

```
>>> print(res_out.summary())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34\statsmodels\regression\linear_model.py", line 1993, in summary
    ('F-statistic:', ["%#8.4g" % self.fvalue] ),
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34\statsmodels\tools\decorators.py", line 97, in __get__
    _cachedval = self.fget(obj)
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34\statsmodels\regression\linear_model.py", line 1231, in fvalue
    idx.pop(const_idx)
TypeError: 'NoneType' object cannot be interpreted as an integer

>>> res_out.model.data.const_idx
>>> repr(res_out.model.data.const_idx)
'None'
```

**Comment by josef-pkt** [comment]
tricky: I didn't specify which model
this is only with a robust cov_type and with an implicit constant

```

import numpy as np

nobs = 100
np.random.seed(2)
x = np.random.randn(nobs, 1)
x = ((x > 0) == [True, False]).astype(int) 
y = x.sum(1) + np.random.randn(nobs)
w = 1 + 0.25 * np.random.rand(nobs)

from statsmodels.regression.linear_model import OLS, WLS

res = OLS(y, x).fit(cov_type='HC1')
res.summary()

res = WLS(y, x).fit(cov_type='HC1')
res.summary()
```

The reason: If cov_type is robust, then we don't use the fvalue defined by sum of squares, we use wald test that all slope coefficients are zero but not constant. If we only have an implicit constant, then we cannot test that coefficients are zero.

Quick fix: return nan for fvalue in this case
"correct" fix: I guess we could get the linear restriction for the t_test that implies that all linear combinations except for the implicit constant are zero. (How would that look like?)

**Comment by josef-pkt** [comment]
I opened #3723 for ENH, so I can close this BUG issue.
