### ISSUE TITLE
TST: test_discrete tests don't warn

### ISSUE THREAD

**Issue by FRidh** [statsmodels/statsmodels#2602]
Two tests seem to fail when testing statsmodels 0.6.1 on Python 3.3 with Pandas 0.16.2, numpy 1.9.2 and scipy 0.15.1.
```py
SKIP: X13/X12 not available

======================================================================
FAIL: statsmodels.discrete.tests.test_discrete.test_perfect_prediction
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/dkifypi51kxmvdknkqva2wwmi0bn8ixa-python3.3-nose-1.3.4/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python3.3-statsmodels-0.6.1.drv-0/statsmodels-0.6.1/statsmodels/discrete/tests/test_discrete.py", line 1290, in test_perfect_prediction
    mod.fit(disp=False, maxiter=50)  # should not raise but does warn
  File "/nix/store/l6mjyivpfdr9fn975fa4lzwis2knwasx-python3-3.3.6/lib/python3.3/contextlib.py", line 55, in __exit__
    next(self.gen)
  File "/nix/store/96pfw39hxzx57dqpkkcnyvdyavcj6dqf-python3.3-pandas-0.16.2/lib/python3.3/site-packages/pandas/util/testing.py", line 1720, in assert_produces_warning
    % expected_warning.__name__)
AssertionError: Did not see expected warning of class 'Warning'.

======================================================================
FAIL: statsmodels.discrete.tests.test_discrete.test_poisson_newton
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/dkifypi51kxmvdknkqva2wwmi0bn8ixa-python3.3-nose-1.3.4/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/nix-build-python3.3-statsmodels-0.6.1.drv-0/statsmodels-0.6.1/statsmodels/discrete/tests/test_discrete.py", line 1319, in test_poisson_newton
    res = mod.fit(start_params=-np.ones(4), method='newton', disp=0)
  File "/nix/store/l6mjyivpfdr9fn975fa4lzwis2knwasx-python3-3.3.6/lib/python3.3/contextlib.py", line 55, in __exit__
    next(self.gen)
  File "/nix/store/96pfw39hxzx57dqpkkcnyvdyavcj6dqf-python3.3-pandas-0.16.2/lib/python3.3/site-packages/pandas/util/testing.py", line 1720, in assert_produces_warning
    % expected_warning.__name__)
AssertionError: Did not see expected warning of class 'Warning'.

----------------------------------------------------------------------
Ran 3296 tests in 642.390s

FAILED (failures=2, skipped=25)
```

```py
>>> import statsmodels as sm
>>> sm.version.full_version
'0.6.1'
>>> sm.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'show_versions'
```

**Comment by FRidh** [comment]
The tests don't fail on Python 2.7 and 3.4.

**Comment by josef-pkt** [comment]
@FRidh  Thanks for the report, I add temporarily prio-high to check this.

Looking at the first missing warning: I don't see where we raise the warning yet, but it's not included in the `always` warn `sm_exception` which are set in `statsmodels.__init__`

My guess right now is that the warnings have already been used before, and without `always` it won't warn again when we test for it. That could be version dependent and depend on the sequence how nose is running the unit tests.

**Comment by josef-pkt** [comment]
related aside: pandas `assert_produces_warning()` should be used with a specific warning so it's more directed and more informative

The second missing warning is supposed to be a `ConvergenceWarning` which is set to `always`, so that's puzzling. I think it's unlikely, although not impossible, that the optimization converges successfully on one machine.

**Comment by josef-pkt** [comment]
running the example from the first warning PerfectSeparation
this issues a ConvergenceWarning and not a warning related to perfect separation.
The perfect separation is still correctly identified in the assert_raises before this.

So something is interfering with the ConvergenceWarning in both cases.

Also pandas `assert_produces_warning` are only used in those two cases and grep didn't find it anywhere else in statsmodels. I find 4 cases where we use numpy `assert_warns`

**Comment by josef-pkt** [comment]
closing, I haven't seen anything like this in a long time and assume everything works

Please reopen if there are still problems with some version combinations
