### ISSUE TITLE
old_behavior flag removed from numpy.correlate() in numpy-1.10 - several tests fail

### ISSUE THREAD

**Issue by jlec** [statsmodels/statsmodels#2667]
```python
======================================================================
ERROR: test suite for <class 'statsmodels.tsa.tests.test_ar.TestARMLEConstant'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/usr/lib64/python3.4/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/tests/test_ar.py", line 123, in setupClass
    cls.res1 = AR(data.endog).fit(maxlag=9,method="mle", disp=-1)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 580, in fit
    callback=callback, **kwargs)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/model.py", line 425, in fit
    full_output=full_output)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/optimizer.py", line 184, in _fit
    hess=hessian)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/optimizer.py", line 382, in _fit_lbfgs
    **extra_kwargs)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 188, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 320, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 266, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/optimize.py", line 285, in function_wrapper
    return function(*(wrapper_args + args))
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/model.py", line 403, in <lambda>
    f = lambda params, *args: -self.loglike(params, *args) / nobs
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 353, in loglike
    return self._loglike_mle(params)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 303, in _loglike_mle
    Vpinv = self._presample_varcov(params)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 260, in _presample_varcov
    old_behavior=False)[:-1]
TypeError: correlate() got an unexpected keyword argument 'old_behavior'

======================================================================
ERROR: statsmodels.tsa.tests.test_ar.test_ar_dates
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/tests/test_ar.py", line 264, in test_ar_dates
    ar_model = sm.tsa.AR(endog, freq='A').fit(maxlag=9, method='mle', disp=-1)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 580, in fit
    callback=callback, **kwargs)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/model.py", line 425, in fit
    full_output=full_output)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/optimizer.py", line 184, in _fit
    hess=hessian)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/optimizer.py", line 382, in _fit_lbfgs
    **extra_kwargs)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 188, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 320, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 266, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/optimize.py", line 285, in function_wrapper
    return function(*(wrapper_args + args))
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/model.py", line 403, in <lambda>
    f = lambda params, *args: -self.loglike(params, *args) / nobs
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 353, in loglike
    return self._loglike_mle(params)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 303, in _loglike_mle
    Vpinv = self._presample_varcov(params)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 260, in _presample_varcov
    old_behavior=False)[:-1]
TypeError: correlate() got an unexpected keyword argument 'old_behavior'

======================================================================
ERROR: statsmodels.tsa.tests.test_ar.test_ar_start_params
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/tests/test_ar.py", line 285, in test_ar_start_params
    method="mle", disp=-1, maxiter=100)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 580, in fit
    callback=callback, **kwargs)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/model.py", line 425, in fit
    full_output=full_output)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/optimizer.py", line 184, in _fit
    hess=hessian)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/optimizer.py", line 382, in _fit_lbfgs
    **extra_kwargs)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 188, in fmin_l_bfgs_b
    **opts)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 320, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/lbfgsb.py", line 266, in func_and_grad
    f = fun(x, *args)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/optimize.py", line 285, in function_wrapper
    return function(*(wrapper_args + args))
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/model.py", line 403, in <lambda>
    f = lambda params, *args: -self.loglike(params, *args) / nobs
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 353, in loglike
    return self._loglike_mle(params)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 303, in _loglike_mle
    Vpinv = self._presample_varcov(params)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/ar_model.py", line 260, in _presample_varcov
    old_behavior=False)[:-1]
TypeError: correlate() got an unexpected keyword argument 'old_behavior'

```
statsmodel-0.6.1
numpy-1.10.1

**Comment by jlec** [comment]
```patch
 statsmodels/tsa/ar_model.py | 6 ++----
 1 file changed, 2 insertions(+), 4 deletions(-)

diff --git a/statsmodels/tsa/ar_model.py b/statsmodels/tsa/ar_model.py
index f0af7ee..fe05634 100644
--- a/statsmodels/tsa/ar_model.py
+++ b/statsmodels/tsa/ar_model.py
@@ -256,10 +256,8 @@ class AR(tsbase.TimeSeriesModel):
 
         Vpinv = np.zeros((p, p), dtype=params.dtype)
         for i in range(1, p1):
-            Vpinv[i-1, i-1:] = np.correlate(params0, params0[:i],
-                                            old_behavior=False)[:-1]
-            Vpinv[i-1, i-1:] -= np.correlate(params0[-i:], params0,
-                                             old_behavior=False)[:-1]
+            Vpinv[i-1, i-1:] = np.correlate(params0, params0[:i])[:-1]
+            Vpinv[i-1, i-1:] -= np.correlate(params0[-i:], params0)[:-1]
 
         Vpinv = Vpinv + Vpinv.T - np.diag(Vpinv.diagonal())
         return Vpinv
```
Possible fix.

**Comment by josef-pkt** [comment]
This was changed already in numpy 1.5, new behavior is default since then
https://github.com/numpy/numpy/blob/master/doc/release/1.5.0-notes.rst

There is no problem with just deleting the keyword
