### ISSUE TITLE
TypeError: cannot perform reduce with flexible type - failing tests

### ISSUE THREAD

**Issue by jlec** [statsmodels/statsmodels#2668]
```python
======================================================================
ERROR: test suite for <class 'statsmodels.base.tests.test_data.TestRecarrays'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/usr/lib64/python3.4/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/tests/test_data.py", line 159, in setupClass
    cls.data = sm_data.handle_data(cls.endog, cls.exog)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/data.py", line 566, in handle_data
    **kwargs)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/data.py", line 75, in __init__
    self._handle_constant(hasconst)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/data.py", line 93, in _handle_constant
    const_idx = np.where(self.exog.ptp(axis=0) == 0)[0].squeeze()
TypeError: cannot perform reduce with flexible type

======================================================================
ERROR: test suite for <class 'statsmodels.base.tests.test_data.TestStructarrays'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/usr/lib64/python3.4/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/usr/lib64/python3.4/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/tests/test_data.py", line 178, in setupClass
    cls.data = sm_data.handle_data(cls.endog, cls.exog)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/data.py", line 566, in handle_data
    **kwargs)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/data.py", line 75, in __init__
    self._handle_constant(hasconst)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/base/data.py", line 93, in _handle_constant
    const_idx = np.where(self.exog.ptp(axis=0) == 0)[0].squeeze()
TypeError: cannot perform reduce with flexible type
```
statsmodels-0.6.1
numpy-1.10
pandas-0.17.0

**Comment by josef-pkt** [comment]
That's a bug that was introduced in numpy according the the mailing list discussion (when I asked about this)

It should be fixed in the next release of numpy. I guess disabling the tests for now will be the best choice.

There is also a failure in
`FAIL: statsmodels.tsa.vector_ar.tests.test_var.TestVARResults.test_irf_coefs`
that looks like it's coming from the same behavior change. I don't know the details yet.

**Comment by jlec** [comment]
Any reference to the fix so that we can backport it for numpy?

**Comment by josef-pkt** [comment]
AFAICS, it's https://github.com/numpy/numpy/pull/6500
but I don't know any details since I don't understand the numpy internals for this.

**Comment by jlec** [comment]
Backporting that fix makes the test succeed.

**Comment by josef-pkt** [comment]
@jlec  Thanks for checking, and confirming that it works.
To make sure: Did the `statsmodels.tsa.vector_ar.tests.test_var.TestVARResults.test_irf_coefs` failure also go away?

Do you still have any failures with statsmodels 0.6.1 left?
statsmodels master still has other errors and failures that still need to be investigated.

**Comment by jlec** [comment]
Both go away. But just reported the next.

**Comment by bashtage** [comment]
Is there any reason not to completely remove support for recarrays from master?

**Comment by josef-pkt** [comment]
@bashtage  It's mainly tradition and inertia. recarrays, structured dtypes were used by several packages before pandas became dominant. Looking at a few pages of search results on github, I find almost only copies of numpy or statsmodels that use recarrays. Matplotlib still has the support functions, AFAICS, and it might also work with patsy formulas because of the named columns (pymc3 glm mentions recarrays)

If we decide to drop support we also have to check our own usage. Our datasets are still based on recarrays. We also have a reasonably large number of unit tests for recarray (93 occurrences in a file search).

This also makes a useful test suite for numpy.

**Comment by bashtage** [comment]
I know - but the code for working with recarrays is often messy and in many places I've see was never tested.  I'm not suggesting going out of the way to remove things, but that the official position is that recarrays are not officially supported so that any place they work is just legacy, and when code is refactored these should be removed.

**Comment by bashtage** [comment]
@josef-pkt This is fixed now.

**Comment by sophiashahid** [comment]
i am using numpy version: '1.13.3' and ubuntu version : 16.04.4 
still i am getting this errror . TypeError: cannot perform reduce with flexible type
my traindata is :scipy.sparse.csr.csr_matrix
and my test data is : numpy.ndarray
i am trying hubberREgressor () of features selected after kbest select on count vecterizer matrix. 
can anyone help ?
