### ISSUE TITLE
FAIL: statsmodels.tsa.vector_ar.tests.test_var.TestVARResults.test_irf_coefs

### ISSUE THREAD

**Issue by jlec** [statsmodels/statsmodels#2670]
```python
======================================================================
FAIL: statsmodels.tsa.vector_ar.tests.test_var.TestVARResults.test_irf_coefs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/vector_ar/tests/test_var.py", line 170, in test_irf_coefs
    self._check_irfs(self.irf.irfs, self.ref.irf)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_4/lib/statsmodels/tsa/vector_ar/tests/test_var.py", line 177, in _check_irfs
    assert_almost_equal(ref_irfs, res_irfs)
  File "/usr/lib64/python3.4/site-packages/numpy/testing/utils.py", line 494, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/usr/lib64/python3.4/site-packages/numpy/testing/utils.py", line 886, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python3.4/site-packages/numpy/testing/utils.py", line 663, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(shapes (6,), (6, 3) mismatch)
 x: recarray([ [  0   0   0   0   0   0 -16  63   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0],
       [ -27   59   -4   58   66  -30  -47  -65   22   93   40   -8   68  -72  -71...
 y: array([[ 1.       ,  0.       ,  0.       ],
       [-0.2794347, -0.100468 , -1.9709737],
       [-0.0469873, -0.1728197,  0.0436493],...

----------------------------------------------------------------------
```
statsmodels-0.6.1
numpy-1.10
pandas-0.17.0

**Comment by josef-pkt** [comment]
see #2668 which is most likely the same bug

**Comment by bashtage** [comment]
@josef-pkt This is fixed now.

**Comment by josef-pkt** [comment]
@bashtage   Thanks for the triage of issues

closing
