### ISSUE TITLE
ERROR: statsmodels.graphics.tests.test_tsaplots.test_plot_month

### ISSUE THREAD

**Issue by jlec** [statsmodels/statsmodels#2674]
```python
======================================================================
ERROR: statsmodels.graphics.tests.test_tsaplots.test_plot_month
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib64/python3.5/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_5/lib/statsmodels/graphics/tests/test_tsaplots.py", line 39, in test_plot_month
    dta.index.values)
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_5/lib/statsmodels/compat/python.py", line 87, in lmap
    return list(map(*args, **kwargs))
  File "/var/tmp/portage/dev-python/statsmodels-0.6.1/work/statsmodels-0.6.1-python3_5/lib/statsmodels/graphics/tests/test_tsaplots.py", line 38, in <lambda>
    dates = lmap(lambda x : pd.datetools.parse('1 '+' '.join(x)),
AttributeError: module 'pandas.core.datetools' has no attribute 'parse'

----------------------------------------------------------------------
Ran 3306 tests in 381.635s
```
statsmodels-0.6.1

**Comment by jlec** [comment]
dupe of #2669
