### ISSUE TITLE
TST:  varmax uses online data in unit tests

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2681]
Debian and Ubuntu testing doesn't allow internet access during build and testing

https://launchpadlibrarian.net/223439066/buildlog_ubuntu-vivid-i386.statsmodels_0.7.0~ppa27~revno-1907~ubuntu15.04.1_BUILDING.txt.gz

```
======================================================================
ERROR: Failure: URLError (<urlopen error [Errno -2] Name or service not known>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 519, in makeTest
    return self._makeTest(obj, parent)
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 578, in _makeTest
    return MethodTestCase(obj)
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 345, in __init__
    self.inst = self.cls()
  File "/«PKGBUILDDIR»/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/tsa/statespace/tests/test_varmax.py", line 565, in __init__
    true, order=(1,1), trend='nc', error_cov_type='diagonal')
  File "/«PKGBUILDDIR»/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/tsa/statespace/tests/test_varmax.py", line 539, in __init__
    dta = webuse('manufac', 'http://www.stata-press.com/data/r12/')
  File "/«PKGBUILDDIR»/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/datasets/utils.py", line 48, in webuse
    dta = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by josef-pkt** [comment]
this is still there https://launchpadlibrarian.net/246055802/buildlog_ubuntu-vivid-amd64.statsmodels_0.7.0~ppa27~revno-1938~ubuntu15.04.1_BUILDING.txt.gz

one extra test failure in 

```
======================================================================
FAIL: statsmodels.tsa.statespace.tests.test_dynamic_factor.TestDynamicFactor_ar2_errors.test_mle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/tsa/statespace/tests/test_dynamic_factor.py", line 484, in test_mle
    assert_allclose(res.llf, self.results.llf, atol=1e-3)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1183, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.001

(mismatch 100.0%)
 x: array(607.4054435641632)
 y: array(607.4201043440736)
```

**Comment by josef-pkt** [comment]
@ChadFulton The `manufac` data is from FRED so it's public domain and no restriction for including in statsmodels.
