### ISSUE TITLE
Intel MKL Errors + test_hess FAIL

### ISSUE THREAD

**Issue by jmwoloso** [statsmodels/statsmodels#2695]
Hello,

Linux Mint / Intel MKL/ Virtualenv

Pandas == 0.17.0
Numpy == 1.9.2
Scipy == 0.15.1

I seem to be getting a combination of #1893, #2308 and #1405. Output is below. I also tried to build from source but I get the error that tells me that Pandas needs to be installed (even though it is already).

```
======================================================================
ERROR: statsmodels.formula.tests.test_formula.test_formula_labels
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/formula/tests/test_formula.py", line 92, in test_formula_labels
    assert_equal(model.fittedvalues.index, dta.index)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 35, in assert_equal
    if not is_pandas_min_version('0.14.1'):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 20, in is_pandas_min_version
    from pandas.version import short_version as pversion
ImportError: No module named 'pandas.version'

======================================================================
ERROR: statsmodels.graphics.tests.test_tsaplots.test_plot_month
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/graphics/tests/test_tsaplots.py", line 39, in test_plot_month
    dta.index.values)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/compat/python.py", line 87, in lmap
    return list(map(*args, **kwargs))
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/graphics/tests/test_tsaplots.py", line 38, in <lambda>
    dates = lmap(lambda x : pd.datetools.parse('1 '+' '.join(x)),
AttributeError: 'module' object has no attribute 'parse'

======================================================================
ERROR: statsmodels.tsa.base.tests.test_base.test_predict_freq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/base/tests/test_base.py", line 34, in test_predict_freq
    assert_equal(predict_dates, expected_dates)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 35, in assert_equal
    if not is_pandas_min_version('0.14.1'):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 20, in is_pandas_min_version
    from pandas.version import short_version as pversion
ImportError: No module named 'pandas.version'

======================================================================
ERROR: statsmodels.tsa.tests.test_ar.test_ar_dates
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/tests/test_ar.py", line 270, in test_ar_dates
    assert_equal(ar_model.data.predict_dates, predict_dates)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 35, in assert_equal
    if not is_pandas_min_version('0.14.1'):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 20, in is_pandas_min_version
    from pandas.version import short_version as pversion
ImportError: No module named 'pandas.version'

======================================================================
ERROR: statsmodels.tsa.tests.test_arima.test_reset_trend
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/tests/test_arima.py", line 470, in test_reset_trend
    assert_equal(len(res1.params), len(res2.params)+1)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 35, in assert_equal
    if not is_pandas_min_version('0.14.1'):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 20, in is_pandas_min_version
    from pandas.version import short_version as pversion
ImportError: No module named 'pandas.version'

======================================================================
ERROR: statsmodels.tsa.tests.test_arima.test_arima_predict_mle_dates
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/tests/test_arima.py", line 685, in test_arima_predict_mle_dates
    assert_equal(res1.data.predict_dates, cpi_dates[start:end+1])
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 35, in assert_equal
    if not is_pandas_min_version('0.14.1'):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 20, in is_pandas_min_version
    from pandas.version import short_version as pversion
ImportError: No module named 'pandas.version'

======================================================================
ERROR: statsmodels.tsa.tests.test_arima.test_arma_predict_mle_dates
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/tests/test_arima.py", line 714, in test_arma_predict_mle_dates
    assert_equal(mod.data.predict_dates, sun_dates[start:end+1])
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 35, in assert_equal
    if not is_pandas_min_version('0.14.1'):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 20, in is_pandas_min_version
    from pandas.version import short_version as pversion
ImportError: No module named 'pandas.version'

======================================================================
ERROR: statsmodels.tsa.tests.test_arima.test_arima_predict_css_dates
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/tests/test_arima.py", line 744, in test_arima_predict_css_dates
    assert_equal(res1.data.predict_dates, cpi_dates[start:end+1])
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 35, in assert_equal
    if not is_pandas_min_version('0.14.1'):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 20, in is_pandas_min_version
    from pandas.version import short_version as pversion
ImportError: No module named 'pandas.version'

======================================================================
ERROR: statsmodels.tsa.tests.test_arima.test_arma_predict_indices
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/tests/test_arima.py", line 975, in test_arma_predict_indices
    _check_start(*((model,) + case))
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/tests/test_arima.py", line 920, in _check_start
    assert_equal(start, expected)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 35, in assert_equal
    if not is_pandas_min_version('0.14.1'):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 20, in is_pandas_min_version
    from pandas.version import short_version as pversion
ImportError: No module named 'pandas.version'

======================================================================
ERROR: statsmodels.tsa.tests.test_arima.test_arima_predict_indices
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/tests/test_arima.py", line 1047, in test_arima_predict_indices
    _check_start(*((model,) + case))
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/tests/test_arima.py", line 920, in _check_start
    assert_equal(start, expected)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 35, in assert_equal
    if not is_pandas_min_version('0.14.1'):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 20, in is_pandas_min_version
    from pandas.version import short_version as pversion
ImportError: No module named 'pandas.version'

======================================================================
ERROR: statsmodels.tsa.tests.test_arima.test_arima_wrapper
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tsa/tests/test_arima.py", line 1572, in test_arima_wrapper
    'ma.L1.D.cpi']))
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 35, in assert_equal
    if not is_pandas_min_version('0.14.1'):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/testing.py", line 20, in is_pandas_min_version
    from pandas.version import short_version as pversion
ImportError: No module named 'pandas.version'

======================================================================
FAIL: statsmodels.tools.tests.test_numdiff.TestGradLogit.test_hess
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/statsmodels/tools/tests/test_numdiff.py", line 64, in test_hess
    assert_allclose(he, hefd, rtol=5e-10)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/jason/.virtualenvs/wheelshop/lib/python3.4/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=5e-10, atol=0

(mismatch 100.0%)
 x: array([[ -2.965667e+01,  -1.988865e+02,  -2.370194e+00,  -1.003654e+01],
       [ -1.988865e+02,  -1.383377e+03,  -1.592292e+01,  -6.800266e+01],
       [ -2.370194e+00,  -1.592292e+01,  -8.301699e-01,  -8.301699e-01],
       [ -1.003654e+01,  -6.800266e+01,  -8.301699e-01,  -3.449885e+00]])
 y: array([[ -2.965667e+01,  -1.988865e+02,  -2.370194e+00,  -1.003654e+01],
       [ -1.988865e+02,  -1.383377e+03,  -1.592292e+01,  -6.800266e+01],
       [ -2.370194e+00,  -1.592292e+01,  -8.301699e-01,  -8.301699e-01],
       [ -1.003654e+01,  -6.800266e+01,  -8.301699e-01,  -3.449885e+00]])

----------------------------------------------------------------------
Ran 3306 tests in 312.478s

FAILED (SKIP=25, errors=11, failures=1)
```

**Comment by bashtage** [comment]
You need to use master if you want to pass the pandas.version problems (it was just committed yesterday).

**Comment by jmwoloso** [comment]
Excellent, thank you very much. I just tried that and it worked. I did have to run:

`cython -3 -a `

on the 3 .pyx files as described in the comments here -->> http://stackoverflow.com/questions/23343484/python-3-statsmodels. But it all works. Thanks a million!

**Comment by jmwoloso** [comment]
For clarity for others if they experience the same thing, I'm using Python 3.4.3 and I had to use Cython on the following files in the statsmodels master:

```
/statsmodels/tsa/kalmanf/kalman_loglike.pyx
/statsmodels/nonparametric/_smoothers_lowess.pyx
/statsmodels/nonparametric/linbin.pyx
```

So the full command would be (assuming you've unzipped and are sitting in the 'statsmodels-master' directory:

```
cython -3 -a ./statsmodels/tsa/kalmanf/kalman_loglike.pyx ./statsmodels/nonparametric/_smoothers_lowess.pyx ./statsmodels/nonparametric/linbin.pyx
```
