### ISSUE TITLE
multipletests/fdrcorrection0 returning corrected array of nans

### ISSUE THREAD

**Issue by mgxd** [statsmodels/statsmodels#2899]
It seems if I pass in an array with any nan values, the pvals_corrected is filled with nans. 
The functions I've used:
`statsmodels.sandbox.stats.multicomp.multipletests(p,alpha=0.05,method='fdr_bh')`
`statsmodels.sandbox.stats.multicomp.fdrcorrection0(p,alpha=0.05)`

**Comment by josef-pkt** [comment]
I'm pretty sure I've never checked this for behavior with nans.

All functions treat nan as a regular number and just work with it, unless it's explicitly mention that missing or nan are handled.

I doubt that we/users can do anything better than just dropping nans. 

The nans will spread to the entire results if we need to do reduce operation and broadcast it back.
One possibility is to check whether we can add the nans back in the original position, after dropping them for the calculation.

possible design question: Do we assume that nan's don't count as a hypothesis test? e.g. is Bonferroni using the full count or the not-nan count?
It could be either depending on the meaning of nans.

**Comment by mgxd** [comment]
@josef-pkt 

In my case, I'm taking the difference of coordinates within 3D brain images for pre-post treatment, and then conducting a t-test to see if each value in the array (voxel) differs from 0. But I have to account for multiple comparisons - hence why I'm using this test. 

The problem with dropping the nans is the image would lose its structure, unless they could be added back in the same spot after correcting the pvals. But then these nans will have to be accounted in the hypothesis test I believe. 

Let me know what you think the best course of action is

**Comment by josef-pkt** [comment]
@mgxd   you can keep the mask and reassign, for example

```
mask_valid = np.isfinite(pvalues_original)
pval_corrected = np.empty(pvalues_original.shape)
np.fill(pval_corrected, np.nan)  ? don't remember exactly

pval_corrected[mask] =  multipletests(pvalues_original[mask], ...)
```

this would preserve the position.
If/when we change this, then we would have to do essentially the same.

counting nans as tests or not?
What are the reasons that you have nans in the pvalues?

If we count them as valid tests, then I think it will be equivalent to replacing the nans by 1, i.e. don't reject but use multiple testing correction based on full number of tests.
If we don't count them as valid tests (because we cannot reject them anyway), then the result would be the same as dropping nans as above.

Not all pvalue corrections are equally sensitive to the total number of tests, I need to look that up because I don't remember the computations.

**Comment by mgxd** [comment]
@josef-pkt 
Thanks for the reply, I believe scipy's ttest_1samp (what I'm using) returns nans for 0/0 zero variance.

The nan data is likely blank space outside the brains for both participants - so not counting them as valid tests seems to be the better option.

I have set up almost identical to your method:

`mask = np.isfinite(p)`
`pval_corrected = np.empty(p.shape)`
`pval_corrected.fill(np.nan)` 
`_pvals = pval_corrected[mask]`
`_pvals= multipletests(p[mask],method='fdr_bh')[1]`

which gives me non-nan corrected pvals, but I'm still unsure how to get the nans back in their spot to make my array the same length as p. Any help is welcome!

**Comment by josef-pkt** [comment]
you need to assign into `pval_corrected` at the non-nan positions, i.e. index with the mask

```pval_corrected[mask] = multipletests(p[mask],method='fdr_bh')[1]```

If your `_pvals` is a view on the original array, then `pval_corrected` would be changed after your assignment. I'm not sure whether this works without trying.

**Comment by mgxd** [comment]
@josef-pkt 
`pval_corrected[mask] = multipletests(p[mask],method='fdr_bh')[1]` did the trick, and assigned values to select nans in `pval_corrected`. Thanks again!

**Comment by josef-pkt** [comment]
I put the summary into the description and added FAQ label.

Eventually we should get this inside the functions with a `missing` keyword for the different options.

**Comment by levlitichev** [comment]
I haven't been able to get the code above to work for me. Here's an example script and the stack trace.

## Code

```python

import numpy as np
import pandas as pd
import statsmodels.sandbox.stats.multicomp as multicomp

p = pd.DataFrame([[0.0, 0.1], [0.8, np.nan], [0.05, 0.1]])

mask = np.isfinite(p)
pval_corrected = np.empty(p.shape)
pval_corrected.fill(np.nan)
_pvals = pval_corrected[mask]
pval_corrected[mask] = multicomp.multipletests(p[mask], method='fdr_bh')[1]

```

## Stack trace:

```
Traceback (most recent call last):
  File "/Users/lev/code/pestle/cmap/analytics/evaluate_sets/example_for_github", line 11, in <module>
    pval_corrected[mask] = multicomp.multipletests(p[mask], method='fdr_bh')[1]
  File "/Users/lev/miniconda2/envs/psp_dev/lib/python2.7/site-packages/statsmodels/stats/multitest.py", line 215, in multipletests
    is_sorted=True)
  File "/Users/lev/miniconda2/envs/psp_dev/lib/python2.7/site-packages/statsmodels/stats/multitest.py", line 320, in fdrcorrection
    reject = pvals_sorted <= ecdffactor*alpha
ValueError: operands could not be broadcast together with shapes (3,2) (3,)
```

It looks like the mask is not working as desired.

As with the OP, my problem is that I have a dataframe of p-values with some missing values, and I eventually want to insert corrected p-values into another dataframe. I haven't figured out another way to do this, so your advice would be much appreciated.

Thanks,
Lev

**Comment by josef-pkt** [comment]
maybe p cannot be a pandas DataFrame when applying the mask

`pval_corrected[mask] = multicomp.multipletests(p[mask], method='fdr_bh')[1]`

if p is a numpy ndarray, then `p[mask]` is 1-dimensional as required. pandas will produce 2-D I guess.

try to add an asarray, i.e. 
`pval_corrected[mask] = multicomp.multipletests(np.asarray(p)[mask], method='fdr_bh')[1]`

**Comment by levlitichev** [comment]
I see; you're right. That did the trick. Thanks very much for looking into it so quickly.

**Comment by levlitichev** [comment]
I should clarify. Simply adding `np.asarray` did not work (because then the mask is applied wrong), but using p as an ndarray worked. Here's code that worked for me, starting and ending with a dataframe:

```python

import numpy as np
import pandas as pd
import statsmodels.sandbox.stats.multicomp as multicomp

p = np.array([[0.0, 0.1], [0.8, np.nan], [0.05, 0.1]])
p_df = pd.DataFrame(p, index=["a", "b", "c"], columns=["d", "e"])

mask = pd.notnull(p)
pval_corrected = np.full(p.shape, np.nan)
pval_corrected[mask] = multicomp.multipletests(p[mask], method='fdr_bh')[1]

pval_corrected_df = pd.DataFrame(pval_corrected, index=p_df.index, columns=p_df.columns)
print pval_corrected_df
```

**Comment by josef-pkt** [comment]
@levlitichev  glad to help

Given that this is not unit tested yet, I would suggest that you spot check your results, just to make sure the values are inserted in the right order and the right places.
e.g. you can create a DataFrame from pval_corrected with labels and index from your p DataFrame and compare with p.

I just saw your new comment. Thanks for the full example using pandas.
Is mask a ndarray or a DataFrame in your two examples?  (I don't know the behavior if mask is a DataFrame.)

**Comment by levlitichev** [comment]
Spot-checking is a good idea. It looks good:

```python

# Using a linear array
p_lin = [0.0, 0.1, 0.8, 0.05, 0.1]
pval_corrected_lin = multicomp.multipletests(p_lin, method='fdr_bh')[1]

print pval_corrected_df
print pval_corrected_lin

```

mask is a numpy ndarray in my example (because we're calling `np.isfinite` on p, which is a numpy ndarray).
