### ISSUE TITLE
BUG: ARMA predict with dynamic and constant breaks

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2982]
I'm in the middle of an example
ARMA with seasonal dummies and with default trend (constant)

It looks like dynamic predict, does not take into account that the model has added a constant.
not specifying exog raises an exception in concatenation.

using the model exog explicitly raises the same exception

dropping the constant column (first column of exog) works, and based on the plot it looks correct

`pred_dynamic = res_arma.predict(start='2008-12-01', end='2010-12-01', exog=res_arma.model.exog[-3*12:, 1:], dynamic=True)`

the model is

```
from statsmodels.datasets.elnino import load_pandas
​datadf = load_pandas()

temperature = np.asarray(datadf.data.iloc[:, 1:]).ravel()
nobs = len(temperature)
index = pd.date_range("1950-01-01", periods=nobs, freq='MS')
months = np.tile(np.arange(12), nobs // 12)

df_el = pd.DataFrame({'temperature': temperature, 'month': months}, index=index)


import patsy
y, x = patsy.dmatrices('temperature ~ C(month)', df_el, return_type='dataframe')
res_arma = sm.tsa.ARMA(y, order=(2, 1), exog=x.iloc[:, 1:]).fit()
```

**Comment by josef-pkt** [comment]
this fails, using prediction periods inside the estimation periods
`pred_dynamic2 = res_arma.predict(start='2008-12-01', end='2010-11-01', dynamic=True)`

```
  File "...\statsmodels\base\wrapper.py", line 95, in wrapper
    obj = data.wrap_output(func(results, *args, **kwargs), how)
  File "...\statsmodels\tsa\arima_model.py", line 1501, in predict
    return self.model.predict(self.params, start, end, exog, dynamic)
  File "...\statsmodels\tsa\arima_model.py", line 742, in predict
    exog = np.vstack((self.exog[start - k_ar:, self.k_trend:], exog))
  File "...\python-3.4.4.amd64\lib\site-packages\numpy\core\shape_base.py", line 230, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```
