### ISSUE TITLE
TypeError in fit() of Arima model

### ISSUE THREAD

**Issue by anuragladdha-fk** [statsmodels/statsmodels#2984]
With following sample below:

import statsmodels.tsa.arima_model

t = [52,45,32,56,78,28,19,81,53,49]
s = [1,0,0,0,2,0,0,3,0,1]
u = [0,1,0,3,2,0]

a = statsmodels.tsa.arima_model.ARIMA(t, [2,0,1], s)
model = a.fit()
print model.forecast(6, u, 0.2)

**I am getting following error when a.fit() gets executed**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/osboxes/Documents/anurag/pythonvirtualenv/python276/local/lib/python2.7/site-packages/statsmodels/tsa/arima_model.py", line 919, in fit
    start_params = self._fit_start_params((k_ar, k_ma, k), method)
  File "/home/osboxes/Documents/anurag/pythonvirtualenv/python276/local/lib/python2.7/site-packages/statsmodels/tsa/arima_model.py", line 556, in _fit_start_params
    start_params = self._fit_start_params_hr(order)
  File "/home/osboxes/Documents/anurag/pythonvirtualenv/python276/local/lib/python2.7/site-packages/statsmodels/tsa/arima_model.py", line 493, in _fit_start_params_hr
    endog -= np.dot(exog, ols_params).squeeze()
**TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('int64') with casting rule 'same_kind'**

**Environment details:**
Ubuntu 14
Python (2.7.6)
Cython (0.24)
numpy (1.11.0)
pandas (0.18.1)
patsy (0.4.1)
pip (8.1.2)
python-dateutil (2.5.3)
pytz (2016.4)
scipy (0.17.1)
setuptools (22.0.0)
six (1.10.0)
statsmodels (0.6.1)
wheel (0.29.0)

**How can i fix this issue?**
- I get the same error on CentOS 6.4 as well with similar version of python, cython, numpy, pip, statsmodels, patsy and pandas.
- Even after building and installing 0.8 version of statsmodels i get the same error (instructions from http://statsmodels.sourceforge.net/devel/install.html)

Please help.
Thanks!

**Comment by josef-pkt** [comment]
based on the traceback, the endog is not automatically upcast to float.

So you need to convert the data arrays, mainly `t` in your example to float64.

**Comment by anuragladdha-fk** [comment]
Works now. Thanks much.

**Comment by jbrockmendel** [comment]
Fixed in master cc @bashtage.
