### ISSUE TITLE
TST failure on Win32  in test_sarimax

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3018]
there are several tests all at the same assert that have been failing several times

https://ci.appveyor.com/project/josef-pkt/statsmodels/build/1.0.372/job/0or8pitudu3uc143

AFAICS (spot checking): the following is the test with lowest agreement, rtol=1e-7
all other ones look rtol=1e-10 or better

```
>>> -277.6305357488543 / -277.6305438770892 - 1
-2.92771638044087e-08
```

```
======================================================================
FAIL: statsmodels.tsa.statespace.tests.test_sarimax.Test_seasonal_arma_trend_ct.test_init_keys_replicate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Py\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\tests\test_sarimax.py", line 1061, in test_init_keys_replicate
    assert_allclose(res2.llf, res1.llf, rtol=1e-13)
  File "C:\Py\lib\site-packages\numpy\testing\utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Py\lib\site-packages\numpy\testing\utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-13, atol=0
 
(mismatch 100.0%)
 x: array(-277.6305357488543)
 y: array(-277.6305438770892)
```

**Comment by josef-pkt** [comment]
@ChadFulton  Can we lower rtol to 1e-7, or is this supposed to be more precise?
Is llf the maximized loglike, where results will depend on how good convergence is?
