### ISSUE TITLE
BUG maybe: Windows 32 bit compatibility

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3026]
We have Windows 32bit testing in appveyor, which will be removed again in #3023 

some unit tests where disabled for Win32

in one of the last appveyor runs a new error showed up, which should be investigated, see below

Note: python-xy Ubuntu nightly testing runs 32bit Ubuntu which runs without errors or failures

https://ci.appveyor.com/project/josef-pkt/statsmodels/build/1.0.396/job/4jc8ixsoi271j6g5

```
======================================================================
ERROR: statsmodels.tsa.tests.test_arima.test_1dexog
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Py\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\statsmodels\statsmodels\tsa\tests\test_arima.py", line 1587, in test_1dexog
    mod = ARMA(dta['realcons'], (1,1), dta['m1']).fit(trend='nc', disp=-1)
  File "C:\projects\statsmodels\statsmodels\tsa\arima_model.py", line 947, in fit
    callback=callback, **kwargs)
  File "C:\projects\statsmodels\statsmodels\base\model.py", line 436, in fit
    full_output=full_output)
  File "C:\projects\statsmodels\statsmodels\base\optimizer.py", line 184, in _fit
    hess=hessian)
  File "C:\projects\statsmodels\statsmodels\base\optimizer.py", line 378, in _fit_lbfgs
    **extra_kwargs)
  File "C:\Py\lib\site-packages\scipy\optimize\lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "C:\Py\lib\site-packages\scipy\optimize\lbfgsb.py", line 330, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "C:\Py\lib\site-packages\scipy\optimize\lbfgsb.py", line 273, in func_and_grad
    f = fun(x, *args)
  File "C:\Py\lib\site-packages\scipy\optimize\optimize.py", line 289, in function_wrapper
    return function(*(wrapper_args + args))
  File "C:\projects\statsmodels\statsmodels\base\model.py", line 414, in <lambda>
    f = lambda params, *args: -self.loglike(params, *args) / nobs
  File "C:\projects\statsmodels\statsmodels\tsa\arima_model.py", line 776, in loglike
    return self.loglike_kalman(params, set_sigma2)
  File "C:\projects\statsmodels\statsmodels\tsa\arima_model.py", line 786, in loglike_kalman
    return KalmanFilter.loglike(params, self, set_sigma2)
  File "C:\projects\statsmodels\statsmodels\tsa\kalmanf\kalmanfilter.py", line 649, in loglike
    R_mat, T_mat)
  File "statsmodels\tsa\kalmanf\kalman_loglike.pyx", line 342, in statsmodels.tsa.kalmanf.kalman_loglike.kalman_loglike_double (statsmodels/tsa/kalmanf/kalman_loglike.c:5986)
    v, F, loglikelihood = kalman_filter_double(y,k,p,q,r,nobs,Z_mat,R_mat,T_mat)
  File "statsmodels\tsa\kalmanf\kalman_loglike.pyx", line 74, in statsmodels.tsa.kalmanf.kalman_loglike.kalman_filter_double (statsmodels/tsa/kalmanf/kalman_loglike.c:3344)
    double[::1,:] P = asfortranarray(dot(pinv(identity(r**2)-
  File "C:\Py\lib\site-packages\numpy\linalg\linalg.py", line 1617, in pinv
    u, s, vt = svd(a, 0)
  File "C:\Py\lib\site-packages\numpy\linalg\linalg.py", line 1359, in svd
    u, s, vt = gufunc(a, signature=signature, extobj=extobj)
  File "C:\Py\lib\site-packages\numpy\linalg\linalg.py", line 99, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
LinAlgError: SVD did not converge
```

**Comment by josef-pkt** [comment]
see #3067 for mac 32-bit problems

there is a nan or inf in the SVD/linear algebra (printed at end of log, no information which test)
`** On entry to DGESV   parameter number  4 had an illegal value` 
https://travis-ci.org/MacPython/statsmodels-wheels/jobs/139376880

maybe there is a overflow or underflow/zerodivision in one of the tests for edge cases

**Comment by bashtage** [comment]
@josef-pkt Closeable.

**Comment by josef-pkt** [comment]
@bashtage in general: A short comment about why it can be closed would be helpful, especially for later reference.
E.g what it fixed, where was it fixed, did the issue just disappear, are we ignoring the problem, is it an invalid issue.

e.g. in this case: I don't remember what our 32-bit behavior and status is.
AFAIR, we are not testing 32-bit Python on Windows anymore. 
#3067 only has adjustment to test precision
invalid/inf/nan in linalg/SVD didn't show up anymore, AFAIR in 0.9 testing.

**Comment by bashtage** [comment]
I've been running lots in #4912 

https://ci.appveyor.com/project/josef-pkt/statsmodels/build/1.0.4047

There is a new failure there though.
