### ISSUE TITLE
BLD/DOC: Executing notebooks when building documentation fails with Python 2.7

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#3047]
Parking this as an issue, but it may be user (me) error. It appears that some of the notebooks have been saved with the Python 3 kernel and so `nbgenerate.py` fails when I only have a Python 2 kernel (see error below).

I have temporarily worked around this explicitly setting `kernel_name = 'python2'` in the `execute_nb` function, but probably that is no good for people who actually have the python3 kernel.

    Converting /Users/.../projects/statsmodels/examples/executed/generic_mle.ipynb to /Users/.../projects/statsmodels/docs/source/examples/notebooks/generated/generic_mle.html
    Finished /Users/.../projects/statsmodels/examples/notebooks/generic_mle.ipynb
    Executeing /Users/.../projects/statsmodels/examples/notebooks/glm.ipynb to /Users/.../projects/statsmodels/examples/executed/glm.ipynb

    Traceback (most recent call last):
      File "../tools/nbgenerate.py", line 142, in <module>
        main()
      File "../tools/nbgenerate.py", line 139, in main
        kernel_name=args.kernel_name)
      File "../tools/nbgenerate.py", line 115, in do
        func(nb)
      File "../tools/nbgenerate.py", line 95, in do_one
        kernel_name=kernel_name)
      File "../tools/nbgenerate.py", line 56, in execute_nb
        ep.preprocess(nb, {'metadta': {'path': 'notebooks/'}})
      File "/Users/.../.virtualenvs/default/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 141, in preprocess
        cwd=path)
      File "/Users/.../.virtualenvs/default/lib/python2.7/site-packages/jupyter_client/manager.py", line 429, in start_new_kernel
        km.start_kernel(**kwargs)
      File "/Users/.../.virtualenvs/default/lib/python2.7/site-packages/jupyter_client/manager.py", line 230, in start_kernel
        kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
      File "/Users/.../.virtualenvs/default/lib/python2.7/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
        cmd = self.kernel_spec.argv + extra_arguments
      File "/Users/.../.virtualenvs/default/lib/python2.7/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
        self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
      File "/Users/.../.virtualenvs/default/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 175, in get_kernel_spec
        raise NoSuchKernel(kernel_name)
    jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3
    make: *** [html] Error 1

**Comment by ChadFulton** [comment]
@TomAugspurger I was hoping you might know about this :) Thanks for making building everything so much easier.
