### ISSUE TITLE
BUG predict pandas wrapper breaks without pandas exog but formula

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3182]
after using a standard formula and pandas model, I use just a dict with numpy array for predict.
(

This raises and exception

```
>>> res.predict({'temp': x_p})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\base\model.py", line 774, in predict
    if len(exog) < len(exog_index):
TypeError: object of type 'NoneType' has no len()
```

in base: we compare length even though `exog_index` could be None.
We need `exog_index` is None check first

```
            if len(exog) < len(exog_index):
                # missing values, rows have been dropped
                if exog_index is not None:
```

If exog in predict is a dict for patsy handling, then we cannot tell how many observations are in the dict `exog`, given that we don't parse the original data names.

**Comment by josef-pkt** [comment]
workaround: use pandas

```
df_p = pd.DataFrame({'temp': x_p})
res.predict(df_p)
```

i.e. we could convert to DataFrame, if predict exog is a dict. (instance check would still break dict-like)
