### ISSUE TITLE
BUG: acorr_ljungbox for short time series is broken

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3229]
`diag.acorr_ljungbox`  requires at least 41 observations with default lag, It raises an exception for shorter series.

http://stackoverflow.com/questions/39916771/error-in-acorr-ljungbox-from-statsmodel/39919347#39919347

```
>>> from statsmodels.stats import diagnostic as diag
>>> diag.acorr_ljungbox(np.random.random(50))[0].shape
(40,)
>>> diag.acorr_ljungbox(np.random.random(20), lags=5)
(array([ 0.36718151,  1.02009595,  1.23734092,  3.75338034,  4.35387236]), array([ 0.54454461,  0.60046677,  0.74406305,  0.44040973,  0.49966951]))
>>> diag.acorr_ljungbox(np.random.random(20))
Traceback (most recent call last):
  File "<pyshell#543>", line 1, in <module>
    diag.acorr_ljungbox(np.random.random(20))
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\sandbox\stats\diagnostic.py", line 295, in acorr_ljungbox
    acf2norm = acfx[1:maxlag+1]**2 / (nobs - np.arange(1,maxlag+1))
ValueError: operands could not be broadcast together with shapes (19,) (40,) 
```

Solution: we need a cutoff as function of nobs, `lags = min((lags, nobs // 2)` or something like that.
`nobs - 1` or `nobs -5` or similar would be possible, but given that we return the results for all lags up to maxlags and the estimate won't be reliable with few observations for the long lags, I think nobs // 2 is a reasonable default. Users can always pick something else. 
(I don't have Stata open right now to check what they do for short time series.)

**update**
related: We have ljung-box duplicated, and seems to default to lags=min((nobs - 1, nlags) with nlags=40 by default

```
>>> from statsmodels.tsa import stattools as ts
>>> ts.acf(z, unbiased=False, qstat=True)[-1]
array([ 0.67152051,  0.89754045,  0.95671896,  0.59265665,  0.70013498,
        0.39934265,  0.50700587,  0.59843545,  0.60683743,  0.5344915 ,
        0.5145257 ,  0.56778241,  0.63762903,  0.70128111,  0.54131853,
        0.60332243,  0.66656227,  0.72635071,  0.77991177])
>>> diag.acorr_ljungbox(z, lags=19)[1]
array([ 0.67152051,  0.89754045,  0.95671896,  0.59265665,  0.70013498,
        0.39934265,  0.50700587,  0.59843545,  0.60683743,  0.5344915 ,
        0.5145257 ,  0.56778241,  0.63762903,  0.70128111,  0.54131853,
        0.60332243,  0.66656227,  0.72635071,  0.77991177])
```

**Comment by zveryansky** [comment]
here the fix: #3360
