### ISSUE TITLE
with recent numpy/pandas: TypeError: cannot sort an Index object in-place, use sort_values instead

### ISSUE THREAD

**Issue by yarikoptic** [statsmodels/statsmodels#3282]
As revealed by tests running for https://github.com/statsmodels/statsmodels/pull/3281:

```
======================================================================
ERROR: statsmodels.tools.tests.test_grouputils.TestIndexGrouping.test_transform_slices
----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/statsmodels-0.8.0rc1-py2.7-linux-x86_64.egg/statsmodels/tools/tests/test_grouputils.py", line 108, in test_transform_slices

    level=0)

  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/statsmodels-0.8.0rc1-py2.7-linux-x86_64.egg/statsmodels/tools/grouputils.py", line 489, in transform_slices

    self.get_slices(level=level)

  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/statsmodels-0.8.0rc1-py2.7-linux-x86_64.egg/statsmodels/tools/grouputils.py", line 406, in get_slices

    groups.sort()

  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/pandas/indexes/base.py", line 1733, in sort

    raise TypeError("cannot sort an Index object in-place, use "

TypeError: cannot sort an Index object in-place, use sort_values instead

======================================================================

ERROR: statsmodels.tools.tests.test_grouputils.TestMultiIndexGrouping.test_transform_slices

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/statsmodels-0.8.0rc1-py2.7-linux-x86_64.egg/statsmodels/tools/tests/test_grouputils.py", line 108, in test_transform_slices

    level=0)

  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/statsmodels-0.8.0rc1-py2.7-linux-x86_64.egg/statsmodels/tools/grouputils.py", line 489, in transform_slices

    self.get_slices(level=level)

  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/statsmodels-0.8.0rc1-py2.7-linux-x86_64.egg/statsmodels/tools/grouputils.py", line 406, in get_slices

    groups.sort()

  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.7/site-packages/pandas/indexes/base.py", line 1733, in sort

    raise TypeError("cannot sort an Index object in-place, use "

TypeError: cannot sort an Index object in-place, use sort_values instead
```

could it

**Comment by josef-pkt** [comment]
We don't get the error in our test runs, So I assume this was fixed in pandas compat changes
