### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by lmsanch** [statsmodels/statsmodels#3308]
I am running a script that has dependencies on statsmodel. I have several matrices of about 180 rows by 50 to 500 columns. The code runs well for the matrices that have roughly 100 columns or less, but for the remaining ones, the code breaks at the point below:

```
51     # run the search
     52     ic_algorithm = IC(RobustRegressionTest, data_frame, variable_types)
---> 53     graph = ic_algorithm.search()
     54     solution = graph.edges(data=True)
     55 

/Users/luissanchez/anaconda/lib/python2.7/site-packages/causality/inference/search/__init__.pyc in search(self)
     23     def search(self):
     24         self._build_g()
---> 25         self._find_skeleton()
     26         self._orient_colliders()
     27 

/Users/luissanchez/anaconda/lib/python2.7/site-packages/causality/inference/search/__init__.pyc in _find_skeleton(self)
    124                 for z in itertools.combinations(z_candidates, N):
    125                     test = self.independence_test([y], [x], list(z), 
--> 126                         self.data, self.alpha)
    127                     if test.independent():
    128                         self._g.remove_edge(x,y)

/Users/luissanchez/anaconda/lib/python2.7/site-packages/causality/inference/independence_tests/__init__.pyc in __init__(self, y, x, z, data, alpha)
      4 class RobustRegressionTest():
      5     def __init__(self, y, x, z, data, alpha):
----> 6         self.regression = sm.RLM(data[y], data[x+z])
      7         self.result = self.regression.fit()
      8         self.coefficient = self.result.params[x][0]

/Users/luissanchez/anaconda/lib/python2.7/site-packages/statsmodels/robust/robust_linear_model.pyc in __init__(self, endog, exog, M, missing, **kwargs)
    115         self.M = M
    116         super(base.LikelihoodModel, self).__init__(endog, exog,
--> 117                 missing=missing, **kwargs)
    118         self._initialize()
    119         #things to remove_data

/Users/luissanchez/anaconda/lib/python2.7/site-packages/statsmodels/base/model.pyc in __init__(self, endog, exog, **kwargs)
     58         hasconst = kwargs.pop('hasconst', None)
     59         self.data = self._handle_data(endog, exog, missing, hasconst,
---> 60                                       **kwargs)
     61         self.k_constant = self.data.k_constant
     62         self.exog = self.data.exog

/Users/luissanchez/anaconda/lib/python2.7/site-packages/statsmodels/base/model.pyc in _handle_data(self, endog, exog, missing, hasconst, **kwargs)
     82 
     83     def _handle_data(self, endog, exog, missing, hasconst, **kwargs):
---> 84         data = handle_data(endog, exog, missing, hasconst, **kwargs)
     85         # kwargs arrays could have changed, easier to just attach here
     86         for key in kwargs:

/Users/luissanchez/anaconda/lib/python2.7/site-packages/statsmodels/base/data.pyc in handle_data(endog, exog, missing, hasconst, **kwargs)
    564     klass = handle_data_class_factory(endog, exog)
    565     return klass(endog, exog=exog, missing=missing, hasconst=hasconst,
--> 566                  **kwargs)

/Users/luissanchez/anaconda/lib/python2.7/site-packages/statsmodels/base/data.pyc in __init__(self, endog, exog, missing, hasconst, **kwargs)
     73 
     74         # this has side-effects, attaches k_constant and const_idx
---> 75         self._handle_constant(hasconst)
     76         self._check_integrity()
     77         self._cache = resettable_cache()

/Users/luissanchez/anaconda/lib/python2.7/site-packages/statsmodels/base/data.pyc in _handle_constant(self, hasconst)
     91             # detect where the constant is
     92             check_implicit = False
---> 93             const_idx = np.where(self.exog.ptp(axis=0) == 0)[0].squeeze()
     94             self.k_constant = const_idx.size
     95 

ValueError: zero-size array to reduction operation maximum which has no identity
```
Any solution? Thanks

**Comment by josef-pkt** [comment]
This sounds strange, The ValueError sounds like self.exog is an empty array.

Check that you have the correct data. Are you using statsmodels 0.6.1.
(I don't remember when we changed things in constant detection, but your line numbers differ from mine.

Right now I cannot think of any reason why we should get an empty array from our side, except for missing='drop' and there are no rows without missing values left (untested I guess).

```
>>> mod_ols2 = OLS(np.ones((0,0)), np.ones((0,3)))
Traceback (most recent call last):
  File "<pyshell#98>", line 1, in <module>
    mod_ols2 = OLS(np.ones((0,0)), np.ones((0,3)))
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\regression\linear_model.py", line 631, in __init__
    hasconst=hasconst, **kwargs)
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\regression\linear_model.py", line 526, in __init__
    weights=weights, hasconst=hasconst, **kwargs)
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\regression\linear_model.py", line 95, in __init__
    super(RegressionModel, self).__init__(endog, exog, **kwargs)
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\base\model.py", line 212, in __init__
    super(LikelihoodModel, self).__init__(endog, exog, **kwargs)
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\base\model.py", line 63, in __init__
    **kwargs)
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\base\model.py", line 88, in _handle_data
    data = handle_data(endog, exog, missing, hasconst, **kwargs)
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\base\data.py", line 630, in handle_data
    **kwargs)
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\base\data.py", line 79, in __init__
    self._handle_constant(hasconst)
  File "m:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\base\data.py", line 131, in _handle_constant
    const_idx = np.where(self.exog.ptp(axis=0) == 0)[0].squeeze()
ValueError: zero-size array to reduction operation maximum which has no identity
````

**Comment by lmsanch** [comment]
Thank you. I have version 0.6.1. I have no idea what the problem is, and a somebody else I know is having the same problem with a different part of my dataset.

**Comment by josef-pkt** [comment]
You can use a debugger like pdb and check what self.exog is at that place, and whether your code doesn't use an empty dataframe or array.
Otherwise, I need a reproducible example that I can run.

My guess right now is that it's a problem on your side and not inside statsmodels.

**Comment by lmsanch** [comment]
Thank you, I'll check that.

**Comment by josef-pkt** [comment]
@lmsanch  If you find a problem in statsmodels, then please reopen. But we will need a reproducible example, or enough information to find the cause for a bug.
