### ISSUE TITLE
BUG/MAINT: numpy compat float in reshape

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3332]
looks like a new test failure in debian testing
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848782

It should be integer division in GEE plot function, uses now numpy reshape with a float

uses 
numpy 1:1.12.0~b1-1
pandas is 0.19.1-3  which doesn't have anymore the previous closed StringIO error
full buildlog
http://aws-logs.debian.net/2016/12/19/statsmodels_0.8.0~rc1+git59-gef47cd9-1_unstable.log

```
> ======================================================================
> ERROR: statsmodels.genmod.tests.test_gee.TestGEE.test_nominal_plot
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
>     self.test(*self.arg)
>   File "/usr/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 147, in skipper_func
>     return f(*args, **kwargs)
>   File "/<<BUILDDIR>>/statsmodels-0.8.0~rc1+git59-gef47cd9/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/genmod/tests/test_gee.py", line 187, in test_nominal_plot
>     fig = result.plot_distribution()
>   File "/<<BUILDDIR>>/statsmodels-0.8.0~rc1+git59-gef47cd9/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/genmod/generalized_estimating_equations.py", line 2395, in plot_distribution
>     (ncut, len(self.params) / ncut))
>   File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
>     return _wrapfunc(a, 'reshape', newshape, order=order)
>   File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 67, in _wrapfunc
>     return _wrapit(obj, method, *args, **kwds)
>   File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
>     result = getattr(asarray(obj), method)(*args, **kwds)
> TypeError: 'float' object cannot be interpreted as an index
```

**Comment by josef-pkt** [comment]
warnings in the above log file about future numpy compatibility

```
test_add_lag1d_struct (statsmodels.tsa.tests.test_tsa_tools.TestLagmat) ... /usr/lib/python2.7/dist-packages/numpy/lib/recfunctions.py:400: FutureWarning: Numpy has detected that you may be viewing or writing to an array returned by selecting multiple fields in a structured array. 

This code may break in numpy 1.13 because this will return a view instead of a copy -- see release notes for details.
  return seqarrays.view(dtype=seqdtype, type=seqtype)
ok
```

**Comment by josef-pkt** [comment]
test  noise in the log:

```
statsmodels.tsa.tests.test_arima.test_bad_start_params ... /<<BUILDDIR>>/statsmodels-0.8.0~rc1+git59-gef47cd9/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/regression/linear_model.py:1094: RuntimeWarning: invalid value encountered in sqrt
  return rho, np.sqrt(sigmasq)
ok
statsmodels.tsa.tests.test_arima.test_arima_small_data_bug ... /<<BUILDDIR>>/statsmodels-0.8.0~rc1+git59-gef47cd9/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/tsa/ar_model.py:770: RuntimeWarning: divide by zero encountered in log
  return np.log(self.sigma2) + (1 + self.df_model) * np.log(nobs)/nobs
ok
```

**Comment by jreback** [comment]
for >= 0.19.0 to avoid warnings use

```
In [1]: from pandas import to_datetime

In [2]: from pandas.tseries.tools import parse_time_string
```

**Comment by josef-pkt** [comment]
@jreback Thanks, 
Is this compatible with a few older pandas versions, or do we need to make the import conditional on the pandas version?

@ChadFulton Given that you just refactored this in master, can you look at what changes would be needed against maintenance/0.8 and whether there is a separate fix needed for master?

**Comment by jreback** [comment]
@josef-pkt no this should be backward compat

**Comment by bashtage** [comment]
@josef-pkt This can be closed.  Just checked on Numpy 1.12, Latest rls SciPy and Pandas 0.19.2 and there are not future warnings in master.

FWIW pandas-master does output a lot of warnings for removal of .ix.  There are 250 uses of .ix in statsmodels but this can wait since it won't be removed for a long time.

**Comment by josef-pkt** [comment]
Thanks for confirming

closing

**Comment by bsolomon1124** [comment]
I know this issue is closed here, but `import statsmodels.api` still gives rise to this deprecation warning (`import statsmodels` doesn't).  I'm using pandas 0.20.3.

**Comment by bashtage** [comment]
Are you using master or 0.8?

**Comment by bsolomon1124** [comment]
`statsmodels.__version__ = 0.8`
