### ISSUE TITLE
ARIMA ValueError with constant exog variable

### ISSUE THREAD

**Issue by datacathy** [statsmodels/statsmodels#3343]
I'm getting a ValueError in ARIMA which seems to happen when an exog variable has a constant value. This happens in real world data, a small snippet of which I reproduce here:
```
>>> import pandas as pd
>>> from statsmodels.tsa.arima_model import ARIMA
>>> X = [0.5,0.5,0.5,0.5,0.5]
>>> Y = [-0.011866,0.003380,0.015357,0.004451,-0.020889]
>>> T = ['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04', '2000-01-05']
>>> TDT = pd.to_datetime(T)
>>> df = pd.DataFrame({'x': X, 'y': Y})
>>> df.index = TDT
>>> df
              x         y
2000-01-01  0.5 -0.011866
2000-01-02  0.5  0.003380
2000-01-03  0.5  0.015357
2000-01-04  0.5  0.004451
2000-01-05  0.5 -0.020889
>>> m = ARIMA(endog=df.y, order=(1,1,0), exog=df.x)
>>> r = m.fit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/statsmodels/tsa/arima_model.py", line 1104, in fit
    callback, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/statsmodels/tsa/arima_model.py", line 919, in fit
    start_params = self._fit_start_params((k_ar, k_ma, k), method)
  File "/usr/local/lib/python3.5/dist-packages/statsmodels/tsa/arima_model.py", line 563, in _fit_start_params
    bounds=bounds, iprint=-1)
  File "/usr/local/lib/python3.5/dist-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "/usr/local/lib/python3.5/dist-packages/scipy/optimize/lbfgsb.py", line 328, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/local/lib/python3.5/dist-packages/scipy/optimize/lbfgsb.py", line 273, in func_and_grad
    f = fun(x, *args)
  File "/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/usr/local/lib/python3.5/dist-packages/statsmodels/tsa/arima_model.py", line 554, in <lambda>
    func = lambda params: -self.loglike_css(params)
  File "/usr/local/lib/python3.5/dist-packages/statsmodels/tsa/arima_model.py", line 788, in loglike_css
    y -= dot(self.exog, newparams[:k])
ValueError: shapes (4,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)
```
It also seems ARIMA does not work for more than 2 exog variables, but I guess that is a separate bug report...

Thanks very much.

**Comment by josef-pkt** [comment]
Parts of this have changed since 0.6.1. It should work for any number of exog, but there is some specific code that checks that there is no constant column in the exog when constants are added through the trend keyword to avoid singular exog.

I don't have access to a computer right know, and can check the details in the new year. I'm pretty sure arima does not support singular exog like this.

**Comment by josef-pkt** [comment]
(issue didn't get labels and got lost)

The user needs to avoid the duplicate constant by using e.g. trend='nc'
But at least we need a better error message. (and fail right away?)
