### ISSUE TITLE
BUG: pandas 0.19.2 compatibility - long versus integer in timestamp 

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3349]
This looks like a new failure with pandas 0.19.2 on appveyor windows python 2.7, it passes on python 3.5.
The unit tests passed with pandas 0.19.1 in previous run at https://ci.appveyor.com/project/josef-pkt/statsmodels/build/1.0.1076/job/863r6ag0kup7wspa

failing in a PR that is the latest test run:
https://ci.appveyor.com/project/josef-pkt/statsmodels/build/1.0.1094/job/7qac29xs07orl9pw

```

======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_sarimax.test_misc_exog
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Py\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\tests\test_sarimax.py", line 1982, in test_misc_exog
    res.forecast(steps=1, exog=oos_exog)
  File "C:\projects\statsmodels\statsmodels\base\wrapper.py", line 95, in wrapper
    obj = data.wrap_output(func(results, *args, **kwargs), how)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 2401, in forecast
    return self.predict(start=self.nobs, end=end, **kwargs)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 2374, in predict
    prediction_results = self.get_prediction(start, end, dynamic, **kwargs)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\sarimax.py", line 1889, in get_prediction
    self.model._get_prediction_index(start, end, index, silent=True))
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 447, in _get_prediction_index
    start, start_index, start_oos = self._get_index_label_loc(start)
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 383, in _get_index_label_loc
    self._get_index_loc(key, base_index))
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 308, in _get_index_loc
    freq=base_index.freq)
  File "C:\Py\lib\site-packages\pandas\util\decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 301, in __new__
    ambiguous=ambiguous)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 506, in _generate
    index = _generate_regular_range(start, end, periods, offset)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 1977, in _generate_regular_range
    dates = list(xdr)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 2894, in generate_range
    end = start + (periods - 1) * offset
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 395, in __radd__
    return self.__add__(other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 390, in __add__
    return self.apply(other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 70, in wrapper
    result = func(self, other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 2041, in apply
    other = other + relativedelta(months=3 * n - monthsSince, day=1)
  File "C:\Py\lib\site-packages\dateutil\relativedelta.py", line 383, in __radd__
    return self.__add__(other)
  File "C:\Py\lib\site-packages\dateutil\relativedelta.py", line 365, in __add__
    ret = (other.replace(**repl)
  File "pandas\tslib.pyx", line 697, in pandas.tslib.Timestamp.replace (pandas\tslib.c:14489)
  File "pandas\tslib.pyx", line 691, in pandas.tslib.Timestamp.replace.validate (pandas\tslib.c:14143)
ValueError: value must be an integer, received <type 'long'> for year
======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_structural.test_misc_exog
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Py\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\tests\test_structural.py", line 334, in test_misc_exog
    res.forecast(steps=1, exog=oos_exog)
  File "C:\projects\statsmodels\statsmodels\base\wrapper.py", line 95, in wrapper
    obj = data.wrap_output(func(results, *args, **kwargs), how)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 2401, in forecast
    return self.predict(start=self.nobs, end=end, **kwargs)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 2374, in predict
    prediction_results = self.get_prediction(start, end, dynamic, **kwargs)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\structural.py", line 1486, in get_prediction
    self.model._get_prediction_index(start, end, index, silent=True))
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 447, in _get_prediction_index
    start, start_index, start_oos = self._get_index_label_loc(start)
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 383, in _get_index_label_loc
    self._get_index_loc(key, base_index))
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 308, in _get_index_loc
    freq=base_index.freq)
  File "C:\Py\lib\site-packages\pandas\util\decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 301, in __new__
    ambiguous=ambiguous)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 506, in _generate
    index = _generate_regular_range(start, end, periods, offset)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 1977, in _generate_regular_range
    dates = list(xdr)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 2894, in generate_range
    end = start + (periods - 1) * offset
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 395, in __radd__
    return self.__add__(other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 390, in __add__
    return self.apply(other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 70, in wrapper
    result = func(self, other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 2041, in apply
    other = other + relativedelta(months=3 * n - monthsSince, day=1)
  File "C:\Py\lib\site-packages\dateutil\relativedelta.py", line 383, in __radd__
    return self.__add__(other)
  File "C:\Py\lib\site-packages\dateutil\relativedelta.py", line 365, in __add__
    ret = (other.replace(**repl)
  File "pandas\tslib.pyx", line 697, in pandas.tslib.Timestamp.replace (pandas\tslib.c:14489)
  File "pandas\tslib.pyx", line 691, in pandas.tslib.Timestamp.replace.validate (pandas\tslib.c:14143)
ValueError: value must be an integer, received <type 'long'> for year
======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_varmax.TestVAR_exog.test_forecast
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Py\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\tests\test_varmax.py", line 437, in test_forecast
    desired = self.results.forecast(steps=16, exog=exog)
  File "C:\projects\statsmodels\statsmodels\base\wrapper.py", line 95, in wrapper
    obj = data.wrap_output(func(results, *args, **kwargs), how)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 2401, in forecast
    return self.predict(start=self.nobs, end=end, **kwargs)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 2374, in predict
    prediction_results = self.get_prediction(start, end, dynamic, **kwargs)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\varmax.py", line 781, in get_prediction
    self.model._get_prediction_index(start, end, index, silent=True))
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 447, in _get_prediction_index
    start, start_index, start_oos = self._get_index_label_loc(start)
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 383, in _get_index_label_loc
    self._get_index_loc(key, base_index))
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 308, in _get_index_loc
    freq=base_index.freq)
  File "C:\Py\lib\site-packages\pandas\util\decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 301, in __new__
    ambiguous=ambiguous)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 506, in _generate
    index = _generate_regular_range(start, end, periods, offset)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 1977, in _generate_regular_range
    dates = list(xdr)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 2894, in generate_range
    end = start + (periods - 1) * offset
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 395, in __radd__
    return self.__add__(other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 390, in __add__
    return self.apply(other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 70, in wrapper
    result = func(self, other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 2041, in apply
    other = other + relativedelta(months=3 * n - monthsSince, day=1)
  File "C:\Py\lib\site-packages\dateutil\relativedelta.py", line 383, in __radd__
    return self.__add__(other)
  File "C:\Py\lib\site-packages\dateutil\relativedelta.py", line 365, in __add__
    ret = (other.replace(**repl)
  File "pandas\tslib.pyx", line 697, in pandas.tslib.Timestamp.replace (pandas\tslib.c:14489)
  File "pandas\tslib.pyx", line 691, in pandas.tslib.Timestamp.replace.validate (pandas\tslib.c:14143)
ValueError: value must be an integer, received <type 'long'> for year
======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_varmax.TestVAR_exog2.test_forecast
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Py\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\tests\test_varmax.py", line 528, in test_forecast
    desired = self.results.forecast(steps=16, exog=exog)
  File "C:\projects\statsmodels\statsmodels\base\wrapper.py", line 95, in wrapper
    obj = data.wrap_output(func(results, *args, **kwargs), how)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 2401, in forecast
    return self.predict(start=self.nobs, end=end, **kwargs)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 2374, in predict
    prediction_results = self.get_prediction(start, end, dynamic, **kwargs)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\varmax.py", line 781, in get_prediction
    self.model._get_prediction_index(start, end, index, silent=True))
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 447, in _get_prediction_index
    start, start_index, start_oos = self._get_index_label_loc(start)
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 383, in _get_index_label_loc
    self._get_index_loc(key, base_index))
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 308, in _get_index_loc
    freq=base_index.freq)
  File "C:\Py\lib\site-packages\pandas\util\decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 301, in __new__
    ambiguous=ambiguous)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 506, in _generate
    index = _generate_regular_range(start, end, periods, offset)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 1977, in _generate_regular_range
    dates = list(xdr)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 2894, in generate_range
    end = start + (periods - 1) * offset
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 395, in __radd__
    return self.__add__(other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 390, in __add__
    return self.apply(other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 70, in wrapper
    result = func(self, other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 2041, in apply
    other = other + relativedelta(months=3 * n - monthsSince, day=1)
  File "C:\Py\lib\site-packages\dateutil\relativedelta.py", line 383, in __radd__
    return self.__add__(other)
  File "C:\Py\lib\site-packages\dateutil\relativedelta.py", line 365, in __add__
    ret = (other.replace(**repl)
  File "pandas\tslib.pyx", line 697, in pandas.tslib.Timestamp.replace (pandas\tslib.c:14489)
  File "pandas\tslib.pyx", line 691, in pandas.tslib.Timestamp.replace.validate (pandas\tslib.c:14143)
ValueError: value must be an integer, received <type 'long'> for year
======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_varmax.test_misc_exog
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Py\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\tests\test_varmax.py", line 817, in test_misc_exog
    res.forecast(steps=1, exog=oos_exog)
  File "C:\projects\statsmodels\statsmodels\base\wrapper.py", line 95, in wrapper
    obj = data.wrap_output(func(results, *args, **kwargs), how)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 2401, in forecast
    return self.predict(start=self.nobs, end=end, **kwargs)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 2374, in predict
    prediction_results = self.get_prediction(start, end, dynamic, **kwargs)
  File "C:\projects\statsmodels\statsmodels\tsa\statespace\varmax.py", line 781, in get_prediction
    self.model._get_prediction_index(start, end, index, silent=True))
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 447, in _get_prediction_index
    start, start_index, start_oos = self._get_index_label_loc(start)
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 383, in _get_index_label_loc
    self._get_index_loc(key, base_index))
  File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 308, in _get_index_loc
    freq=base_index.freq)
  File "C:\Py\lib\site-packages\pandas\util\decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 301, in __new__
    ambiguous=ambiguous)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 506, in _generate
    index = _generate_regular_range(start, end, periods, offset)
  File "C:\Py\lib\site-packages\pandas\tseries\index.py", line 1977, in _generate_regular_range
    dates = list(xdr)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 2894, in generate_range
    end = start + (periods - 1) * offset
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 395, in __radd__
    return self.__add__(other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 390, in __add__
    return self.apply(other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 70, in wrapper
    result = func(self, other)
  File "C:\Py\lib\site-packages\pandas\tseries\offsets.py", line 2041, in apply
    other = other + relativedelta(months=3 * n - monthsSince, day=1)
  File "C:\Py\lib\site-packages\dateutil\relativedelta.py", line 383, in __radd__
    return self.__add__(other)
  File "C:\Py\lib\site-packages\dateutil\relativedelta.py", line 365, in __add__
    ret = (other.replace(**repl)
  File "pandas\tslib.pyx", line 697, in pandas.tslib.Timestamp.replace (pandas\tslib.c:14489)
  File "pandas\tslib.pyx", line 691, in pandas.tslib.Timestamp.replace.validate (pandas\tslib.c:14143)
ValueError: value must be an integer, received <type 'long'> for year

```

**Comment by jreback** [comment]
here is a replicated failure in [pandas](https://ci.appveyor.com/project/jreback/pandas/build/job/4evdeu8bxd4ot4du) with this commit
https://github.com/jreback/pandas/commit/dcef5f2afe8671bde467333c71551b0164374bfc

I have a fix prepared for pandas, but easiest for you to change is to pass ``int(keys + 1)`` rather than ``keys + 1``. annoying I know, but only checking for ints here (and not compat with 2.7 longs)..... 

File "C:\projects\statsmodels\statsmodels\tsa\base\tsa_model.py", line 308, in _get_index_loc
 (do the change here)

**Comment by josef-pkt** [comment]
@jreback  Thanks, I will make the change.

Debian is currently adopting pandas 0.19.2. statsmodels is green there.

Just as background information: Is there anything specific about Windows with python 2.7 that it fails only there?

**Comment by josef-pkt** [comment]
my mistake: I think this is refactored code in master and is not in statsmodels 0.8, so not relevant for current Debian testing and backporting

**Comment by jreback** [comment]
so on py2.7, on 32-bit platforms, ints are generally longs (and not actual ints). We have a compat routine (e.g. for py2 and py3) that checks these things as ``isinstance(value, int)`` is not sufficient.

**Comment by stonebig** [comment]
I don't see it on 0.8 branch. is it normal ?

**Comment by josef-pkt** [comment]
@stonebig  I thought this is from the recent datetime refactoring in tsa that is not backported to statsmodels 0.8.

Did you see a problem in the 0.8 version?

**Comment by stonebig** [comment]
Ah., ok. the pull request 3350 was tagged "backport-0.8.0", so I thought it was impacting 0.8. my mistake, sorry.

**Comment by stonebig** [comment]
How do I launh statsmodels nose tests from IDLE command line ?

**Comment by josef-pkt** [comment]
In idle or any python interpreter you can can do either statsmodels.test() or statsmodels.api.test() after the appropriate import. (the api: `sm.test()` is just for convenience, both are the same.)

aside: I had added and removed the backport tags when I got myself confused.
There are still some compatibility backports commits/PRs that are not backported yet to the maintenance branch. (Debian testing is about 3 merges ahead of maintenance/0.8.)

**Comment by stonebig** [comment]
there are a lot of messages in my python-3.6 23 bit test, of statsmodels-0.8.0rc1 master of december 28th. I will post a few. maybe it's normal, maybe it's my fault

**Comment by josef-pkt** [comment]
@stonebig  Thanks for testing
We dropped the 32bit python testing a while ago. I don't remember what the reason was.

to your test results:
- the pandas sort fix hasn't been backported yet, fix is in master
- the runtime warnings are test noise if there is no failure or error. Maybe some of it is 32bit specific, but there is also some test noise with 64bit python.
- the last two for test_corrpsd look like 32bit specific errors. I never looked at those, if I ever saw them. They might be precision problems for convergence. We need to look into those, but I'm using now only 64bit python versions.

- I'm not sure if there are any new Future and Deprecation warning. The numpy int case looks serious, but I don't remember seeing it.  Some fixes are in #3348 but I haven't looked close enough yet about backporting (and about how much it applies to 0.8).

(aside: the kids will be back at school next week, then I will have some quite time to look at merging and backporting.)

**Comment by stonebig** [comment]
I rarely test 32bit also,  until I read that it may run on my next Samsung smartphone.

**Comment by stonebig** [comment]
under 64 bit instead of 32, I get in the end:
````

======================================================================
ERROR: statsmodels.tools.tests.test_grouputils.TestIndexGrouping.test_transform_slices
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.0.amd64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.0.amd64\lib\site-packages\statsmodels\tools\tests\test_grouputils.py", line 108, in test_transform_slices
    level=0)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.0.amd64\lib\site-packages\statsmodels\tools\grouputils.py", line 489, in transform_slices
    self.get_slices(level=level)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.0.amd64\lib\site-packages\statsmodels\tools\grouputils.py", line 406, in get_slices
    groups.sort()
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.0.amd64\lib\site-packages\pandas\indexes\base.py", line 1733, in sort
    raise TypeError("cannot sort an Index object in-place, use "
TypeError: cannot sort an Index object in-place, use sort_values instead

======================================================================
ERROR: statsmodels.tools.tests.test_grouputils.TestMultiIndexGrouping.test_transform_slices
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.0.amd64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.0.amd64\lib\site-packages\statsmodels\tools\tests\test_grouputils.py", line 108, in test_transform_slices
    level=0)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.0.amd64\lib\site-packages\statsmodels\tools\grouputils.py", line 489, in transform_slices
    self.get_slices(level=level)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.0.amd64\lib\site-packages\statsmodels\tools\grouputils.py", line 406, in get_slices
    groups.sort()
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.1\python-3.6.0.amd64\lib\site-packages\pandas\indexes\base.py", line 1733, in sort
    raise TypeError("cannot sort an Index object in-place, use "
TypeError: cannot sort an Index object in-place, use sort_values instead

----------------------------------------------------------------------
Ran 4913 tests in 1461.713s

FAILED (SKIP=36, errors=2)
<nose.result.TextTestResult run=4913 errors=2 failures=0>
````
