### ISSUE TITLE
ImportError: No module named compat

### ISSUE THREAD

**Issue by Gun1tSurya** [statsmodels/statsmodels#3354]
Working Environment: Ubuntu16.04, Django1.6.4, Python2.7 
After successful installation of django-tracking2 it will gives an error No module name compat

  File "/home/dharmesh/envs/act_env/local/lib/python2.7/site-packages/south/migration/base.py", line 312, in migration
    raise exceptions.UnknownMigration(self, sys.exc_info())
south.exceptions.UnknownMigration: Migration 'tracking:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/home/dharmesh/envs/act_env/local/lib/python2.7/site-packages/south/migration/base.py", line 310, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/home/dharmesh/envs/act_env/local/lib/python2.7/site-packages/tracking/south_migrations/0001_initial.py", line 7, in <module>
    from tracking.compat import User
ImportError: No module named compat

**Comment by josef-pkt** [comment]
You got the wrong package and github organization. `statsmodels` is not related to Django
