### ISSUE TITLE
Python 2.6 Multivariate Test Errors

### ISSUE THREAD

**Issue by bfcondon** [statsmodels/statsmodels#3376]
For the "PYTHON=2.6 dateutil= NUMPY=\"1.6.2=py26_4\" SCIPY=\"0.11.0=np16py26_3\" MATPLOTLIB=1.2", config, I received the following unrelated errors in Travis CI.  These passed on all other test configurations.

======================================================================
ERROR: statsmodels.multivariate.tests.test_cancorr.test_cancorr
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/tests/test_cancorr.py", line 37, in test_cancorr
    r = mod.corr_test()
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/cancorr.py", line 126, in corr_test
    stats.loc[i, 'Canonical Correlation'] = self.cancorr[i]
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 84, in __setitem__
    indexer = self._convert_tuple(key)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 96, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 615, in _convert_to_indexer
    return labels.get_loc(obj)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/index.py", line 716, in get_loc
    return self._engine.get_loc(key)
  File "index.pyx", line 128, in pandas.index.IndexEngine.get_loc (pandas/index.c:3542)
  File "index.pyx", line 148, in pandas.index.IndexEngine.get_loc (pandas/index.c:3422)
  File "hashtable.pyx", line 670, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:10682)
  File "hashtable.pyx", line 676, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:10636)
KeyError: 'Canonical Correlation'

======================================================================
ERROR: statsmodels.multivariate.tests.test_manova.test_manova_sas_example
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/tests/test_manova.py", line 33, in test_manova_sas_example
    r = mod.mv_test()
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/manova.py", line 74, in mv_test
    self.exog_names, self.endog_names)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 256, in _multivariate_ols_test
    return _multivariate_test(hypotheses, exog_names, endog_names, fn)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 317, in _multivariate_test
    stat_table = multivariate_stats(eigv2, p, q, df_resid)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 175, in multivariate_stats
    results.loc["Wilksâ€™ lambda", 'Value'] = fn(np.prod(1 - eigv2))
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 84, in __setitem__
    indexer = self._convert_tuple(key)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 96, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 615, in _convert_to_indexer
    return labels.get_loc(obj)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/index.py", line 716, in get_loc
    return self._engine.get_loc(key)
  File "index.pyx", line 128, in pandas.index.IndexEngine.get_loc (pandas/index.c:3542)
  File "index.pyx", line 150, in pandas.index.IndexEngine.get_loc (pandas/index.c:3477)
KeyError: 'Wilks\xe2\x80\x99 lambda'

======================================================================
ERROR: statsmodels.multivariate.tests.test_manova.test_manova_test_input_validation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/tests/test_manova.py", line 79, in test_manova_test_input_validation
    mod.mv_test(hypothesis)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/manova.py", line 74, in mv_test
    self.exog_names, self.endog_names)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 256, in _multivariate_ols_test
    return _multivariate_test(hypotheses, exog_names, endog_names, fn)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 317, in _multivariate_test
    stat_table = multivariate_stats(eigv2, p, q, df_resid)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 175, in multivariate_stats
    results.loc["Wilksâ€™ lambda", 'Value'] = fn(np.prod(1 - eigv2))
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 84, in __setitem__
    indexer = self._convert_tuple(key)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 96, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 615, in _convert_to_indexer
    return labels.get_loc(obj)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/index.py", line 716, in get_loc
    return self._engine.get_loc(key)
  File "index.pyx", line 128, in pandas.index.IndexEngine.get_loc (pandas/index.c:3542)
  File "index.pyx", line 150, in pandas.index.IndexEngine.get_loc (pandas/index.c:3477)
KeyError: 'Wilks\xe2\x80\x99 lambda'

======================================================================
ERROR: statsmodels.multivariate.tests.test_multivariate_ols.test_glm_dogs_example
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/tests/test_multivariate_ols.py", line 74, in test_glm_dogs_example
    compare_r_output_dogs_data(method='svd')
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/tests/test_multivariate_ols.py", line 50, in compare_r_output_dogs_data
    r = r.mv_test()
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 433, in mv_test
    self.exog_names, self.endog_names)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 256, in _multivariate_ols_test
    return _multivariate_test(hypotheses, exog_names, endog_names, fn)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 317, in _multivariate_test
    stat_table = multivariate_stats(eigv2, p, q, df_resid)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 175, in multivariate_stats
    results.loc["Wilksâ€™ lambda", 'Value'] = fn(np.prod(1 - eigv2))
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 84, in __setitem__
    indexer = self._convert_tuple(key)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 96, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 615, in _convert_to_indexer
    return labels.get_loc(obj)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/index.py", line 716, in get_loc
    return self._engine.get_loc(key)
  File "index.pyx", line 128, in pandas.index.IndexEngine.get_loc (pandas/index.c:3542)
  File "index.pyx", line 150, in pandas.index.IndexEngine.get_loc (pandas/index.c:3477)
KeyError: 'Wilks\xe2\x80\x99 lambda'

======================================================================
ERROR: statsmodels.multivariate.tests.test_multivariate_ols.test_specify_L_M_by_string
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/tests/test_multivariate_ols.py", line 83, in test_specify_L_M_by_string
    r1 = r.mv_test(hypotheses=[['Intercept', ['Intercept'], None]])
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 433, in mv_test
    self.exog_names, self.endog_names)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 256, in _multivariate_ols_test
    return _multivariate_test(hypotheses, exog_names, endog_names, fn)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 317, in _multivariate_test
    stat_table = multivariate_stats(eigv2, p, q, df_resid)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 175, in multivariate_stats
    results.loc["Wilksâ€™ lambda", 'Value'] = fn(np.prod(1 - eigv2))
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 84, in __setitem__
    indexer = self._convert_tuple(key)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 96, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 615, in _convert_to_indexer
    return labels.get_loc(obj)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/index.py", line 716, in get_loc
    return self._engine.get_loc(key)
  File "index.pyx", line 128, in pandas.index.IndexEngine.get_loc (pandas/index.c:3542)
  File "index.pyx", line 150, in pandas.index.IndexEngine.get_loc (pandas/index.c:3477)
KeyError: 'Wilks\xe2\x80\x99 lambda'

======================================================================
ERROR: statsmodels.multivariate.tests.test_multivariate_ols.test_from_formula_vs_no_formula
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/tests/test_multivariate_ols.py", line 120, in test_from_formula_vs_no_formula
    r0 = r.mv_test()
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 433, in mv_test
    self.exog_names, self.endog_names)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 256, in _multivariate_ols_test
    return _multivariate_test(hypotheses, exog_names, endog_names, fn)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 317, in _multivariate_test
    stat_table = multivariate_stats(eigv2, p, q, df_resid)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 175, in multivariate_stats
    results.loc["Wilksâ€™ lambda", 'Value'] = fn(np.prod(1 - eigv2))
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 84, in __setitem__
    indexer = self._convert_tuple(key)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 96, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 615, in _convert_to_indexer
    return labels.get_loc(obj)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/index.py", line 716, in get_loc
    return self._engine.get_loc(key)
  File "index.pyx", line 128, in pandas.index.IndexEngine.get_loc (pandas/index.c:3542)
  File "index.pyx", line 150, in pandas.index.IndexEngine.get_loc (pandas/index.c:3477)
KeyError: 'Wilks\xe2\x80\x99 lambda'

======================================================================
ERROR: statsmodels.multivariate.tests.test_multivariate_ols.test_exog_1D_array
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/tests/test_multivariate_ols.py", line 167, in test_exog_1D_array
    r0 = r.mv_test()
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 433, in mv_test
    self.exog_names, self.endog_names)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 256, in _multivariate_ols_test
    return _multivariate_test(hypotheses, exog_names, endog_names, fn)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 317, in _multivariate_test
    stat_table = multivariate_stats(eigv2, p, q, df_resid)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 175, in multivariate_stats
    results.loc["Wilksâ€™ lambda", 'Value'] = fn(np.prod(1 - eigv2))
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 84, in __setitem__
    indexer = self._convert_tuple(key)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 96, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 615, in _convert_to_indexer
    return labels.get_loc(obj)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/index.py", line 716, in get_loc
    return self._engine.get_loc(key)
  File "index.pyx", line 128, in pandas.index.IndexEngine.get_loc (pandas/index.c:3542)
  File "index.pyx", line 150, in pandas.index.IndexEngine.get_loc (pandas/index.c:3477)
KeyError: 'Wilks\xe2\x80\x99 lambda'

======================================================================
ERROR: Testing affine hypothesis, compared with R car linearHypothesis
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/tests/test_multivariate_ols.py", line 195, in test_affine_hypothesis
    r0 = r.mv_test(hypotheses=[('test1', L, M, C)])
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 433, in mv_test
    self.exog_names, self.endog_names)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 256, in _multivariate_ols_test
    return _multivariate_test(hypotheses, exog_names, endog_names, fn)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 317, in _multivariate_test
    stat_table = multivariate_stats(eigv2, p, q, df_resid)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/statsmodels-0.8.0-py2.6-linux-x86_64.egg/statsmodels/multivariate/multivariate_ols.py", line 175, in multivariate_stats
    results.loc["Wilksâ€™ lambda", 'Value'] = fn(np.prod(1 - eigv2))
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 84, in __setitem__
    indexer = self._convert_tuple(key)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 96, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/indexing.py", line 615, in _convert_to_indexer
    return labels.get_loc(obj)
  File "/home/travis/miniconda2/envs/statsmodels-test/lib/python2.6/site-packages/pandas/core/index.py", line 716, in get_loc
    return self._engine.get_loc(key)
  File "index.pyx", line 128, in pandas.index.IndexEngine.get_loc (pandas/index.c:3542)
  File "index.pyx", line 150, in pandas.index.IndexEngine.get_loc (pandas/index.c:3477)
KeyError: 'Wilks\xe2\x80\x99 lambda'

**Comment by TomAugspurger** [comment]
This was closed by #3390

**Comment by bashtage** [comment]
Closeable now.
