### ISSUE TITLE
ImportError: cannot import name URLError

### ISSUE THREAD

**Issue by lzhw520110** [statsmodels/statsmodels#3494]
when i import statsmodels,i got a error as follows,anyone can help me?

```
import statsmodels.api as sm
Traceback (most recent call last):

  File "<ipython-input-8-6030a6549dc0>", line 1, in <module>
    import statsmodels.api as sm

  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\statsmodels\__init__.py", line 8, in <module>
    from .tools.sm_exceptions import (ConvergenceWarning, CacheWriteWarning,

  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\statsmodels\tools\__init__.py", line 1, in <module>
    from .tools import add_constant, categorical

  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\statsmodels\tools\tools.py", line 11, in <module>
    from statsmodels.datasets import webuse

  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\statsmodels\datasets\__init__.py", line 5, in <module>
    from . import (anes96, cancer, committee, ccard, copper, cpunish, elnino,

  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\statsmodels\datasets\anes96\__init__.py", line 1, in <module>
    from .data import *

  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\statsmodels\datasets\anes96\data.py", line 90, in <module>
    from statsmodels.datasets import utils as du

  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\statsmodels\datasets\utils.py", line 2, in <module>
    from statsmodels.compat.python import (range, StringIO, urlopen,

ImportError: cannot import name URLError
```

**Comment by bashtage** [comment]
what does

```
python -c "import pandas;pandas.show_versions()"
```

report?

**Comment by josef-pkt** [comment]
doesn't sound like an error coming from our side
not enough information
closing
