### ISSUE TITLE
BUG: MixedLM.fit blocks optimizer keywords

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3605]
I wanted to try the new minimize optimization with dogleg, but MixedLM uses a whitelist for `kwargs`.

using example from #3604

```
>>> mdf = md.fit(method='minimize', min_method = 'dogleg')
  File "...\statsmodels\regression\mixed_linear_model.py", line 1936, in fit
    raise ValueError("Argument %s not allowed for MixedLM.fit" % x)
ValueError: Argument min_method not allowed for MixedLM.fit
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```

**Comment by kshedden** [comment]
Maybe we should change to a warning?

I have had a lot of bad experiences with silent errors due to mis-spelled
or incorrect kwargs.

**Comment by bashtage** [comment]
Fixed by commit e6f2f8458: the hard ValueError was replaced with a RuntimeWarning for disallowed optimizer kwargs, exactly as suggested in this thread. Note: min_method still is not in the allowed-kwargs list, so it is silently stripped (with a warning) rather than passed through - happy to file that as a narrow follow-up enhancement if you want method=minimize sub-methods to actually take effect. Closing as fixed for the reported crash.
