### ISSUE TITLE
datetools.dates_from_range ValueError

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3672]
```
from statsmodels.tsa.base.datetools import date_range_str

>>> dates_from_range("1999qIV", "2003QII")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/statsmodels/tsa/base/datetools.py", line 279, in dates_from_range
    dates = date_range_str(start, end, length)
  File "/usr/local/lib/python2.7/site-packages/statsmodels/tsa/base/datetools.py", line 216, in date_range_str
    yr1, offset1 = lmap(int, start.replace(":","").split(split))
ValueError: invalid literal for int() with base 10: 'iv'
```

This isn't _that_ hard to fix and I'll get around to it before long if no one beats me to it.  But there are a bunch of other small problems in `datetools` that require a decision on how robust we want to get.  Handling dates carefully is a rabbit hole I've been down, an experience I'm not eager to repeat.

It looks like the only place datetools is used is `examples.ex_pandas`.  Is this something we want to consider deprecating?

**Comment by jbrockmendel** [comment]
Technical debt; not worth worrying about.  Closing.
