### ISSUE TITLE
some errors when using ARIMA to make prediction

### ISSUE THREAD

**Issue by hehehechenlina** [statsmodels/statsmodels#3829]
Hi all,

     I am getting some Errors when forecasting on an ARIMA. I don't know where is the problem.Here is my code:
`#-*- coding: utf-8 -*-

#from __future__ import print_function
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import xlrd

#读取Excel数据
#discfile = 'data_test.xls'
discfile = 'forecast-python.xls'
bk = xlrd.open_workbook(discfile)
sh = bk.sheet_by_name("Sheet1")
for iCol in range(0, 1):
	data = sh.col_values(iCol)
	#data = zip(*data)
	GridID = int(data[0])
	testData = data[1:433]
	#testData = data[1:433]
	#data = pd.read_excel(discfile,index_col = 0,parse_cols = 0)

	#testData = np.array(testData,dtype=np.float)

	testData = pd.Series(testData)

	testData.index = pd.Index(sm.tsa.datetools.dates_from_range('2001','2432'))
	#testData.index = pd.Index(sm.tsa.datetools.dates_from_range('2001','2048'))

	#####输出文件路径
	PredictFilePath = "predict_value.txt"
	PFP = open(PredictFilePath,'w')

	# data=data['number']
	# data.head()

	testData.plot(figsize = (12,8))
	print(testData)

	#使用一阶差分
	diff_1 = testData.diff(1)
	diff1 = diff_1.dropna()

	###确认最小值
	arma_mod00 = sm.tsa.ARMA(diff1,(1,1)).fit()
	minAIC = arma_mod00.aic

	######计算p,q值
	for i in range(1, 5):
		for j in range(1, 5):
			try:
				arma_mod61 = sm.tsa.ARMA(diff1,(i,j)).fit()
				aic = arma_mod61.aic
				print(i,j)
				if aic < minAIC:
					p = i
					q = j
					minAIC = aic
			except Exception, e:
				print (0)
			#print(arma_mod61.aic,arma_mod61.bic,arma_mod61.hqic)

	####arma模型值
	arma_mod61 = sm.tsa.ARMA(diff1, (p, q)).fit()

	#用模型预测
	#predict_data = arma_mod61.predict('2048','2096',dynamic=False)
	predict_data = arma_mod61.predict('2432','2480',dynamic=False)
	print(predict_data)

	####还原预测值
	diff1_shift = predict_data.shift(48)
	print(diff1_shift)
	diff_recover_1 = predict_data.add(diff1_shift)
	diff_recover_1 = diff_recover_1.dropna() # 最终还原的预测值
	print('预测值')
	print(diff_recover_1)

	for i in range(0, 48):
		print >> PFP, int(diff_recover_1.values[i]),
	print >> PFP

PFP.close()
`
here is the sample data:(27230 is the ID,the first 48 values are the train data,the last 48 is the test data,I am trying to predict the last 48 values)

27370
--
1678
1678
1651
1636
1656
1663
1663
1700
1697
1730
1716
1826
2115
2963
4415
5223
6532
6296
5804
5275
4852
4602
4488
4395
4287
4414
4490
4365
4190
4279
4413
4201
4152
4293
4479
4589
4714
4343
4197
4196
3901
3615
3680
3394
3341
3181
3167
3070
1703
1648
1609
1568
1612
1633
1662
1661
1660
2008
2054
1902
2069
2736
3824
5163
5649
6064
5696
5605
5235
5128
4609
4341
4340
4467
4341
4407
4269
4191
4062
4014
4377
4546
4518
4480
4691
4516
4060
3765
3736
3545
3494
3380
3237
3051
2989

And here is the error:
`Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2017.1\helpers\pydev\pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2017.1\helpers\pydev\pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/  ʿ о / ҵ  о /arima/arima.py", line 48, in <module>
    arma_mod00 = sm.tsa.ARMA(testData,(1,1)).fit()
  File "C:\Python27\lib\site-packages\statsmodels\tsa\arima_model.py", line 452, in __init__
    super(ARMA, self).__init__(endog, exog, dates, freq, missing=missing)
  File "C:\Python27\lib\site-packages\statsmodels\tsa\base\tsa_model.py", line 44, in __init__
    self._init_dates(dates, freq)
  File "C:\Python27\lib\site-packages\statsmodels\tsa\base\tsa_model.py", line 64, in _init_dates
    raise ValueError("Frequency inference failed. Use `freq` "
ValueError: Frequency inference failed. Use `freq` keyword.
`

**Comment by ChadFulton** [comment]
The error means that the index you have provided does not have any frequency information, and so predict fails because it doesn't know how to extend your date index to new values.

Your index is:

```python
testData.index = pd.Index(sm.tsa.datetools.dates_from_range('2001','2432'))
```

but I'm not sure what index that is meant to represent? Is it supposed to be years?

**Comment by hehehechenlina** [comment]
thank you for your answers! As you supposed,the index  is meant to represent the years,but I still can't solve this problemT T

**Comment by ChadFulton** [comment]
This case is somewhat difficult because Pandas' `DatetimeIndex` only supports years up to 2262 (see [here](https://pandas.pydata.org/pandas-docs/stable/timeseries.html#timestamp-limitations)). You may want to just use an integer index instead of a date index in this case.
