### ISSUE TITLE
BUG/TST statespace pickling error in statsmodels 0.8

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3892]
new Debian bug report

with cython 2.6 and statsmodels version 0.8
there is no error in master with cython 2.6, so this must be fixed by the statespace refactoring in master 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873512
4 cases like the following
```
======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_save.test_sarimax
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/1st/statsmodels-0.8.0/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/tsa/statespace/tests/test_save.py", line 22, in test_sarimax
    res.save('test_save_sarimax.p')
  File "/build/1st/statsmodels-0.8.0/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/base/wrapper.py", line 72, in save
    save_pickle(self, fname)
  File "/build/1st/statsmodels-0.8.0/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/iolib/smpickle.py", line 15, in save_pickle
    cPickle.dump(obj, fout, protocol=-1)
  File "stringsource", line 2, in statsmodels.tsa.statespace._statespace.zStatespace.__reduce_cython__
TypeError: self._design,self._initial_state,self._initial_state_cov,self._obs,self._obs_cov,self._obs_intercept,self._selected_state_cov,self._selection,self._state_cov,self._state_intercept,self._transition cannot be converted to a Python object for pickling
```

**Comment by bashtage** [comment]
Didn't I fix this in master?

**Comment by josef-pkt** [comment]
@bashtage Thanks, with that hint I found the PR

It looks like #3402 hasn't been backported and is not included in 0.8, but I don't know if it would apply to 0.8 (given the statespace refactoring).
also Debian uses python 2.7 and I don't see whether #3402 is only relevant for python 3.6.

Based on the Debian report it looks like it only showed up after upgrading cython

**Comment by tillea** [comment]
Hi,
I was watching at the Debian bug report which causes some pressure due to several packages depending from statsmodels.  Is there any solution at the horizon?

**Comment by bashtage** [comment]
It is fixed in Master and will be fixed in 0.9.  I don't know what the
release target is for that though.

**Comment by tillea** [comment]
Hi Kevin,
On Tue, Sep 26, 2017 at 06:58:30AM +0000, Kevin Sheppard wrote:
> It is fixed in Master and will be fixed in 0.9.
Cool.  Could you point to the actual commit which would enable us to
backport the fix more easily?
Thanks a lot, Andreas.

-- 
http://fam-tille.de

**Comment by bashtage** [comment]
https://github.com/statsmodels/statsmodels/commit/f81cde31421288e669e859d0e798d843ca2ecabe

**Comment by bashtage** [comment]
https://github.com/statsmodels/statsmodels/commit/f81cde31421288e669e859d0e798d843ca2ecabe

**Comment by bashtage** [comment]
@ChadFulton Fixed.
