### ISSUE TITLE
RuntimeError: Kernel died before replying to kernel_info

### ISSUE THREAD

**Issue by tillea** [statsmodels/statsmodels#4116]
Hi,
during a rebuild of all packages in sid, your package failed to build on amd64.  You can find the according [bug report](https://bugs.debian.org/880245) in the Debian BTS.  Here is the hopefully relevant part of the log:

    python3 ../tools/nbgenerate.py --execute=True --allow_errors=True
    Traceback (most recent call last):
      File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/lib/python3/dist-packages/ipykernel_launcher.py", line 16, in <module>
        app.launch_new_instance()
      File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 657, in launch_instance
        app.initialize(argv)
      File "<decorator-gen-121>", line 2, in initialize
      File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 448, in initialize
        self.init_sockets()
      File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 251, in init_sockets
        self.init_iopub(context)
      File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 256, in init_iopub
       self.iopub_port = self._bind_socket(self.iopub_socket, self.iopub_port)
      File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 180, in _bind_socket
        s.bind("tcp://%s:%i" % (self.ip, port))
      File "zmq/backend/cython/socket.pyx", line 495, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5662)
      File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:8400)
    zmq.error.ZMQError: Address already in use
    RUNNING THE L-BFGS-B CODE
    ...

Any hint what might be the problem?
Kind regards, Andreas.

**Comment by josef-pkt** [comment]
This is a ipython/jupyter issue, and not related to statsmodels. You can ask at their issue tracker.
