### ISSUE TITLE
RuntimeError: Running cythonize failed!

### ISSUE THREAD

**Issue by BalajiRang** [statsmodels/statsmodels#4150]
Hi All,
When I try to run the setup.py from the source of **Statsmodels** in cmd, it is throwing the error, although the cython installed is cython.version '0.27.3'

statsmodels-master>python setup.py install
Cythonizing sources
Processing statsmodels\nonparametric\linbin.pyx
Fatal error in launcher: Unable to create process using '"'
Traceback (most recent call last):
  File "C:\Users\Test\statsmodels-master\tools\cythonize.py", line 215, in <module>
    main()
  File "C:\Users\Test\statsmodels-master\tools\cythonize.py", line 211, in main
    find_process_files(root_dir)
  File "C:\Users\Test\statsmodels-master\tools\cythonize.py", line 203, in find_process_files
    process(cur_dir, fromfile, tofile, function, hash_db)
  File "C:\Users\Test\statsmodels-master\tools\cythonize.py", line 174, in process
    processor_function(fromfile, tofile)
  File "C:\Users\Test\statsmodels-master\tools\cythonize.py", line 72, in process_pyx
    raise Exception('Cython failed')
Exception: Cython failed
Traceback (most recent call last):
  File "setup.py", line 546, in <module>
    generate_cython()
  File "setup.py", line 90, in generate_cython
    raise RuntimeError("Running cythonize failed!")
RuntimeError: Running cythonize failed!

Any help would be much appreciated,
Thanks in advance.

**Comment by jbrockmendel** [comment]
The traceback doesn't help much for troubleshooting.  Is this still failing with up-to-date statsmodels/cython?

**Comment by bashtage** [comment]
Closing since no follow-up.  Please reopen if this continues.
