### ISSUE TITLE
Error when fitting a mixed model on a toy example

### ISSUE THREAD

**Issue by Rodolphe2005** [statsmodels/statsmodels#4152]
```
import statsmodels.formula.api as smf
df = pd.DataFrame({'group': [0, 0, 0, 1, 1, 1],
                        'x': [1, 2, 3, 4, 5, 6],
                        'y': [False, True, True, False, True, True]})
md = smf.mixedlm("y~x", df, groups=df['group'])
md.fit()
```

yields 

```
Traceback (most recent call last):
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-131-776d448d067d>", line 5, in <module>
    md.fit()
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/statsmodels/regression/mixed_linear_model.py", line 1988, in fit
    **kwargs)
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/statsmodels/base/model.py", line 451, in fit
    full_output=full_output)
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/statsmodels/base/optimizer.py", line 184, in _fit
    hess=hessian)
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/statsmodels/base/optimizer.py", line 286, in _fit_bfgs
    disp=disp, retall=retall, callback=callback)
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 889, in fmin_bfgs
    res = _minimize_bfgs(f, x0, args, fprime, callback=callback, **opts)
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 943, in _minimize_bfgs
    gfk = myfprime(x0)
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/statsmodels/base/model.py", line 430, in <lambda>
    score = lambda params, *args: -self.score(params, *args) / nobs
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/statsmodels/regression/mixed_linear_model.py", line 1466, in score
    params.fe_params = self.get_fe_params(params.cov_re, params.vcomp)
  File "/Users/rodolphe/anaconda/envs/python-decision/lib/python3.6/site-packages/statsmodels/regression/mixed_linear_model.py", line 1166, in get_fe_params
    mat = np.concatenate((self.exog_li[group_ix], self.endog_li[group_ix][:, None]), axis=1)
ValueError: all the input arrays must have same number of dimensions
```

**Comment by kshedden** [comment]
It works for me if I replace y with [0, 1, 1, 0, 1, 1].  Note that we only
have mixed linear models, not generalized linear mixed models.  We do not
have mixed logistic regression, etc.  In any case, the dependent variable
needs to be numeric.
