### ISSUE TITLE
results_arima unloadable

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4412]
@ChadFulton since I'm trying to give jkpt some space, but someone should be aware of this crap.

```
from statsmodels.tsa.tests.results import results_arima
ra = results_arima.ARIMA112()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "statsmodels/tsa/tests/results/results_arima.py", line 290, in __init__
    self.forecast = forecast_results['fc112c'][-25:]
ValueError: no field of name fc112c
```

and even if that error were fixed, `ARIMA112.__init__` would set a bunch of attributes and then overwrite them all by setting `self.__dict__`.  I don't know how we're expected to trust any of this old code.

**Comment by josef-pkt** [comment]
112 mle is currently not unit tested, obviously there are problems across packages, most likely with getting stuck in local (near) optima.

see also starting here https://github.com/statsmodels/statsmodels/issues/4357#issuecomment-374055883

A useful issue for this would be "convergence problems in ARIMA test case"
and investigate what's going on.

Running quickly a few versions of this ARIMA 112  case (mistakes in my usage not ruled out):
- SARIMAX converges but produces very different numbers, but has larger llf, i.e. better MLE.
- SARIMAX seems to converge to the same params from different start_params
- ARIMA mle converges to the Stata params, if I start with the css params or with SARIMAX params.
- For other start params, ARIMA mle runs into convergence failure or converges to something else.

Based on the numbers, (old versions of) Stata, R and Gretl also don't seem to produce the same results either.

this might be a good test case to check how auto_arima order search can handle a difficult case

**Comment by josef-pkt** [comment]
It is also possible that in this case the estimated params are very sensitive to initial conditions and small differences in how they are defined have a large impact on the results.

**Comment by josef-pkt** [comment]
or that the results are screwed up because of outliers or heavy tails.
