### ISSUE TITLE
VARProcess `exog` vs `intercept`

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4442]
New issue taking place of #4436, where discussion has become unproductive.

Code to reproduce error:
```
from statsmodels.tsa.vector_ar.var_model import *
endog = np.random.randn(100, 3)
exog = np.random.randn(100, 1)
model = VAR(endog=endog , exog=exog)
res = model.fit(maxlags=2)
>>> res.mean()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "statsmodels/tsa/vector_ar/var_model.py", line 820, in mean
    return np.linalg.solve(self._char_mat, self.exog)
  File "/usr/local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 390, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 100 is different from 3)
```

**Comment by jbrockmendel** [comment]
`VARResults.plotsim` also breaks with exog.

```
data = sm.datasets.macrodata.load_pandas().data
endog = data[['realgdp', 'realcons', 'realinv']]
exog = np.zeros((203, 3))
exog[::4, 0] = 1
exog[1::4, 1] = 1
exog[2::4, 2] = 1

model = sm.tsa.VAR(endog=endog, exog=exog)
res = model.fit(trend="c")
res.plotsim()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "statsmodels/tsa/vector_ar/var_model.py", line 810, in plotsim
    Y = util.varsim(self.coefs, self.exog, self.sigma_u, steps=steps)
  File "statsmodels/tsa/vector_ar/util.py", line 203, in varsim
    result[p:] = intercept + ugen[p:]
ValueError: operands could not be broadcast together with shapes (203,3) (999,3) 
```

`forecast` and `forecast_interval` are broken:
```
res.forecast_interval(y=endog.values[:5], steps=10, exog_future=exog[:5])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "statsmodels/tsa/vector_ar/var_model.py", line 995, in forecast_interval
    point_forecast = self.forecast(y, steps, exog_future=exog_future)
  File "statsmodels/tsa/vector_ar/var_model.py", line 934, in forecast
    exog_future = np.column_stack(exogs)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 369, in column_stack
    return _nx.concatenate(arrays, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

`__str__` is broken:
```
>>> res._results.__str__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "statsmodels/tsa/vector_ar/var_model.py", line 786, in __str__
    output += '\nmean: %s' % self.mean()
  File "statsmodels/tsa/vector_ar/var_model.py", line 820, in mean
    return np.linalg.solve(self._char_mat, self.exog)
  File "/usr/local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 390, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 203 is different from 3)
```

`plot_forecast` is broken.  It doesn't take an `exog_future` kwarg.

**Comment by josef-pkt** [comment]
@jbrockmendel  Thanks for collecting these.

Do those methods still work without an exog?   

I really want to get finally rid of statsmodels 0.9, so I only want to fix bugs that break earlier code (that worked) for 0.9.   
E.g. I think we have to add the `intercept` property/attribute back in.

Fixing incomplete support for exog can be done for 0.10, and we add a warning about experimental support for exog to the docstring (if it doesn't have it already).

**Comment by jbrockmendel** [comment]
I'm now reasonably confident that `plotsim` will silently be incorrect in the no-exog case.  It passes `self.exog` where it used to pass `self.intercept`, so `util.varsim` will incorrectly go down the `intercept=None` branch.

For that matter I expect `plotsim` to _also_ break in the non-null `exog` case because it will usually be the wrong shape.

**Comment by jbrockmendel** [comment]
What if VECM were to override the relevant methods so that VAR/VARResults could be unchanged/unbroken?

> For example, I think trend (including constant) should become part of exog.

I tend to agree, but that gets into the whole `__init__` vs `fit` topic that our descendants will be discussing for generations.

I should have taken a more active part in reviewing vecm earlier on.  It is much easier to prevent these mistakes than to fix them after they are in master.

**Comment by josef-pkt** [comment]
> What if VECM were to override the relevant methods so that VAR/VARResults could be unchanged/unbroken?

No that's not possible, VECM itself needs to delegate to VAR for the short-run analysis given the cointegrating vectors. So we needed to add exog to VAR.
(This reminds me: there should be a test or example for VAR with stochastic exog, because the cointegrating vectors where the main reason to add exog to VAR. Seasonal deterministic were a bonus.)

The problem here was that VAR has insufficient unit tests (not even regression or smoke tests) for those extra things which I didn't even know are there, e.g. I never looked at `mean` or the VAR simulation functions, and don't even know if they were working properly before (given the lack of unit tests).
(And of course time constraints, more reviewers would help a lot in those cases.)

**Comment by jbrockmendel** [comment]
OK.  I'll make my peace with 0.9's impending breakage of var_model, and the likely "it'll get fixed in 2028" fallout.

**Comment by bashtage** [comment]
Fixed by the same PR #4538 (commit f315d5593): mean() (renamed intercept_longrun()), simulate_var/plotsim, and forecast all now correctly use self.intercept instead of misusing self.exog, with clear ValueErrors instead of crashes for bad exog_future. Closing as fixed.
