### ISSUE TITLE
VAR cov_params pandas wrapping broken

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4485]
VARResults.cov_params breaks when wrapping with pandas.

```
data = sm.datasets.macrodata.load_pandas().data
endog = data[['realgdp', 'realcons', 'realinv']].diff().iloc[1:]
endog.index = pd.date_range('2016-01-01', periods=len(endog))
model = sm.tsa.VAR(endog)
res = model.fit(3)

>>> res.cov_params
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/statsmodels/base/wrapper.py", line 41, in __getattribute__
    obj = data.wrap_output(obj, how=how)
  File "/usr/local/lib/python2.7/site-packages/statsmodels/base/data.py", line 411, in wrap_output
    return self.attach_cov(obj)
  File "/usr/local/lib/python2.7/site-packages/statsmodels/base/data.py", line 531, in attach_cov
    columns=self.param_names)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 361, in __init__
    copy=copy)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 533, in _init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 4631, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 4608, in construction_error
    passed, implied))
ValueError: Shape of passed values is (30, 30), indices imply (10, 10)
```

**Comment by jbrockmendel** [comment]
Also, VARResults.cov_params is a cache_readonly, while LikelihoodModelResults.cov_params is a method.  (note VARResults does not subclass any Results classes)

**Comment by bashtage** [comment]
Fixed in master.
