### ISSUE TITLE
DOC/BUG: notebook build error categorical_interaction_plot.ipynb

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4659]
https://travis-ci.org/statsmodels/statsmodels/jobs/380861770

There is also a Debian bug report with a ZMQError

I don't see anything suspicious.

```
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/statsmodels-test/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/travis/miniconda/envs/statsmodels-test/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/travis/miniconda/envs/statsmodels-test/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/travis/miniconda/envs/statsmodels-test/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/home/travis/miniconda/envs/statsmodels-test/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/travis/miniconda/envs/statsmodels-test/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/home/travis/miniconda/envs/statsmodels-test/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 238, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/travis/miniconda/envs/statsmodels-test/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 180, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
***************************************************************************************************
ERROR: Error occured when running /home/travis/build/statsmodels/statsmodels/examples/notebooks/categorical_interaction_plot.ipynb
Kernel died before replying to kernel_info
Kernel died before replying to kernel_info
```

**Comment by bashtage** [comment]
Random travis bug that happens when some port ranges are used.  Can be closed.

**Comment by josef-pkt** [comment]
Ok, closing

@bashtage Thanks for checking
