### ISSUE TITLE
Error importing statsmodels

### ISSUE THREAD

**Issue by tmartinma** [statsmodels/statsmodels#4744]
>>import statsmodels.api as sm
Traceback (most recent call last):
  File "<pyshell#38>", line 1, in <module>
    import statsmodels.api as sm
  File "C:\Users\mm22\AppData\Local\Programs\Python\Python36\lib\site-packages\statsmodels\api.py", line 35, in <module>
    from .stats import api as stats
  File "C:\Users\mm22\AppData\Local\Programs\Python\Python36\lib\site-packages\statsmodels\stats\api.py", line 65, in <module>
    from .mediation import Mediation
  File "C:\Users\mm22\AppData\Local\Programs\Python\Python36\lib\site-packages\statsmodels\stats\mediation.py", line 22, in <module>
    import statsmodels.compat.pandas as pdc  # pragma: no cover
AttributeError: module 'statsmodels' has no attribute 'compat'

the statsmodels version I'm using is 0.9.0. 
Can someone help me out?

Thanks!

**Comment by josef-pkt** [comment]
no idea, something wrong with the install

does `import pandas` work?

also a general check is to run the test suite which will error somewhere in this case but maybe with a more informative message
import statsmodels
statsmodels.test()

**Comment by tmartinma** [comment]
Import pandas works fine.
Just tried
>>> statsmodels.test()
Traceback (most recent call last):
  File "C:\Users\mm22\AppData\Local\Programs\Python\Python36\lib\site-packages\statsmodels\__init__.py", line 41, in __call__
    import pytest
ModuleNotFoundError: No module named 'pytest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#47>", line 1, in <module>
    statsmodels.test()
  File "C:\Users\mm22\AppData\Local\Programs\Python\Python36\lib\site-packages\statsmodels\__init__.py", line 49, in __call__
    raise ImportError('pytest>=3 required to run the test')
ImportError: pytest>=3 required to run the test
