### ISSUE TITLE
Singular matrix - seemingly regardless of data

### ISSUE THREAD

**Issue by TheChymera** [statsmodels/statsmodels#4782]
For [this fully self-contained minimal example](chymera.eu/debug/statsmodels/singular_matrix.zip), I keep getting the following traceback:

```
Traceback (most recent call last):
  File "script.py", line 7, in <module>
    fit = model.fit()
  File "/usr/lib64/python3.4/site-packages/statsmodels/regression/mixed_linear_model.py", line 2041, in fit
    **kwargs)
  File "/usr/lib64/python3.4/site-packages/statsmodels/base/model.py", line 466, in fit
    full_output=full_output)
  File "/usr/lib64/python3.4/site-packages/statsmodels/base/optimizer.py", line 191, in _fit
    hess=hessian)
  File "/usr/lib64/python3.4/site-packages/statsmodels/base/optimizer.py", line 327, in _fit_bfgs
    disp=disp, retall=retall, callback=callback)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/optimize.py", line 909, in fmin_bfgs
    res = _minimize_bfgs(f, x0, args, fprime, callback=callback, **opts)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/optimize.py", line 963, in _minimize_bfgs
    gfk = myfprime(x0)
  File "/usr/lib64/python3.4/site-packages/scipy/optimize/optimize.py", line 293, in function_wrapper
    return function(*(wrapper_args + args))
  File "/usr/lib64/python3.4/site-packages/statsmodels/base/model.py", line 451, in score
    return -self.score(params, *args) / nobs
  File "/usr/lib64/python3.4/site-packages/statsmodels/regression/mixed_linear_model.py", line 1508, in score
    params.fe_params = self.get_fe_params(params.cov_re, params.vcomp)
  File "/usr/lib64/python3.4/site-packages/statsmodels/regression/mixed_linear_model.py", line 1223, in get_fe_params
    fe_params = np.linalg.solve(xtxy[:, 0:-1], xtxy[:, -1])
  File "/usr/lib64/python3.4/site-packages/numpy/linalg/linalg.py", line 375, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/usr/lib64/python3.4/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```

I have tried adding noise to my data, or structured artificial confounds, as well as looking at only one factor, and yet the error always persists.

This is reproducible with the latest commit from master (c819000bf409f329d1dd9536ea7190a874ebb202).

**Comment by kshedden** [comment]
You should use


> groups='subject'


not

| groups=['subject']

It works for me with this change.

Kerby

**Comment by TheChymera** [comment]
Thank you!

**Comment by umangdadhaniya** [comment]
logit_model = sm.logit('Result ~ Year + Amount_Spent + Popularity_Rank', data = a1).fit()
Warning: Maximum number of iterations has been exceeded.
         Current function value: inf
         Iterations: 35
Traceback (most recent call last):

  File "<ipython-input-426-a9d6c56296df>", line 1, in <module>
    logit_model = sm.logit('Result ~ Year + Amount_Spent + Popularity_Rank', data = a1).fit()

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 1963, in fit
    bnryfit = super().fit(start_params=start_params,

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 227, in fit
    mlefit = super().fit(start_params=start_params,

  File "C:\Users\UMANG\anaconda3\lib\site-packages\statsmodels\base\model.py", line 534, in fit
    Hinv = np.linalg.inv(-retvals['Hessian']) / nobs

  File "<__array_function__ internals>", line 5, in inv

  File "C:\Users\UMANG\anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)

  File "C:\Users\UMANG\anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")

LinAlgError: Singular matrix

**Comment by bashtage** [comment]
Try rescaling your regressors, e.g., rescale them to have unit variance.

**Comment by josef-pkt** [comment]
also try another optimizer, e.g. method="bfgs" or "nm"
