### ISSUE TITLE
varmax with TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by lightnino** [statsmodels/statsmodels#4791]
Hi, 

I pull the raw data that i want to run VARMAX on by codes below (inserted the snapshot of how the dataframe looks like) 

endog=blp.historicalRequest(['USGG2YR Index','USGG5YR Index','USGG10YR Index','USGG30YR Index'], 'PX_LAST', "19911231", date.today().replace(day=calendar.monthrange(date.today().year, date.today().month)[1]).strftime('%Y%m%d'),periodicitySelection='MONTHLY')
endog['Date'] =endog.index
endog['Date']= pd.to_datetime(endog['Date']).apply(lambda x: x.date())
endog.index=endog['Date']
endog.drop(endog.iloc[:,4:],inplace=True,axis=1)
![image](https://user-images.githubusercontent.com/40484063/42448591-31c8b910-83b0-11e8-99b3-49654539c8fe.png)

When i run the following codes. 

mod_var1 = statsmodels.tsa.statespace.varmax.VARMAX(endog[['USGG2YR Index','USGG5YR Index','USGG10YR Index','USGG30YR Index']], exog=None, order=(3, 0), trend='c', error_cov_type='unstructured', measurement_error=False, enforce_stationarity=True, enforce_invertibility=True) 

res_var1 = mod_var1.fit()

I got the following error - 
    for i in range(self.k_endog)

TypeError: not all arguments converted during string formatting

Does anyone has any idea what was the issue and how to resolve it? 
Thanks very much

**Comment by lightnino** [comment]
hi Chad - thanks for coming back to me. 

don't know why the bug described above is gone now, and in run into a slightly different issue - 


res_var1 = mod_var1.fit()
Traceback (most recent call last):

  File "<ipython-input-70-346bc4362a15>", line 1, in <module>
    res_var1 = mod_var1.fit()

  File "C:\Users\chzhu\AppData\Local\Continuum\anaconda3\envs\myenv\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 432, in fit
    start_params = self.start_params

  File "C:\Users\chzhu\AppData\Local\Continuum\anaconda3\envs\myenv\lib\site-packages\statsmodels\tsa\statespace\varmax.py", line 295, in start_params
    if np.any(np.isnan(endog)):

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

I checked my endog type - 
type (endog)
Out[71]: pandas.core.frame.DataFrame

Which format should I turn my dataframe into in order for np.isnan()function working? Or should I go to the original file and change the function of np.isnan() to pd.isnull to fulfill the same checking purpose? 

Let me know and thanks again for your help as always

**Comment by lightnino** [comment]
endog.dtypes
Out[81]: 
Security        Field  
USGG2YR Index   PX_LAST    float64
USGG5YR Index   PX_LAST    float64
USGG10YR Index  PX_LAST    float64
USGG30YR Index  PX_LAST    float64
dtype: object

**Comment by ChadFulton** [comment]
I'm not sure - it should work if you have float inputs. Usually this kind of problem happens if some kind of strange dtype makes its way in.

What is the output of `print(mod_var1.endog.dtype)`?

**Comment by lightnino** [comment]
Hi Chad - thanks so much for coming back. 

 dtype('<U14') - this is the result. I amended the mod_var1 to get back to normal float64
mod_var1.endog.dtype
Out[127]: dtype('float64')

Then if i run res_var1 = mod_var1.fit() again - 
i go back to the original error - 

    for i in range(self.k_endog)

TypeError: not all arguments converted during string formatting

Sorry for the mess.. but in case you have any idea to share with me. would be very much appreciated. thanks

**Comment by fr-chrismargach** [comment]
I also received this error when passing endogs as a dataframe slice having a two-level column multiindex. I worked around the issue by converting to a multidimensional array via .values().

**Comment by ChadFulton** [comment]
@fr-chrismargach thanks, that is very helpful! I'll try to replicate and maybe we can get a fix.

**Comment by fr-chrismargach** [comment]
You're welcome @ChadFulton. FYI I revisited this part of my code today and confirmed that reverting the df in question to single-index columns resolved the issue.
