### ISSUE TITLE
MNLogit.initialize() cannot operate on a 1-d vector

### ISSUE THREAD

**Issue by dangeles** [statsmodels/statsmodels#4838]
I initialize using `normed`, an obs x vars np array, and feed it `dummyDS` as an endogenous obs x 1 vector:
 
`mnlogit = discrete_model.MNLogit(dummyDS, otu_vars)`

Then I call the initialize function:
`mnlogit.initialize()`

I get the following error:

> ---------------------------------------------------------------------------
> AxisError                                 Traceback (most recent call last)
> <ipython-input-39-fa0f9013df49> in <module>()
>       1 normed = StandardScaler().fit_transform(otu[otu_vars].values)
>       2 mnlogit = discrete_model.MNLogit(otu.dummyDS.values, normed)
> ----> 3 mnlogit.initialize()
> 
> /anaconda3/lib/python3.5/site-packages/statsmodels/discrete/discrete_model.py in initialize(self)
>     555         super(MultinomialModel, self).initialize()
>     556         # This is also a "whiten" method in other models (eg regression)
> --> 557         self.endog = self.endog.argmax(1)  # turn it into an array of col idx
>     558         self.J = self.wendog.shape[1]
>     559         self.K = self.exog.shape[1]
> 
> AxisError: axis 1 is out of bounds for array of dimension 1

However, initializing the object by calling it returns no error, and I can even fit the data to a log function....

**Comment by josef-pkt** [comment]
Does the exception go away if you use a 2-D x, e.g. `otu_vars[:, None]`?
Is there a reason that you do not include a constant among the explanatory variables?

**Comment by josef-pkt** [comment]
I will delete my comments again, I misunderstood the question

**Comment by josef-pkt** [comment]
can you add part or all of `dummyDS` in a comment?  with type and dtype

Based on the current information, I cannot see why `MultinomialModel._handle_data` didn't create a 2-D array.

**Comment by dangeles** [comment]
`dummyDS` is a vector of integers (0, 1 and 2) extracted from a pandas DataFrame using the .values call.

**Comment by josef-pkt** [comment]
What's `dummyDS.dtype`?

I checked a simple example with np.int64 endog in {0, 1, 2} created with np.random.randint and there are no problems.
So there must be something specific to your data.

Can you make up a reproducible example? It just needs a few observations, enough to raise the exception in `__init__`?

**Comment by josef-pkt** [comment]
ok, I can replicate it when calling initialize

I haven't checked yet what the reason for the exception is. 
However, the user is NOT supposed to call `initialize`. It is called in `__init__` already to set up the endog array.

i.e. drop the `mnlogit.initialize()` and just call `mnlogit.fit()`

minimal example

```
>>> import numpy as np
>>> from statsmodels.discrete.discrete_model import MNLogit
>>> y = np.array([1, 2, 2, 1, 2, 1, 2, 1, 1, 1])
>>> x = np.ones(len(y) )
>>> mnlogit = MNLogit(y, x)
>>> mnlogit.initialize()
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    mnlogit.initialize()
  File "m:\...\statsmodels\discrete\discrete_model.py", line 557, in initialize
    self.endog = self.endog.argmax(1)  # turn it into an array of col idx
ValueError: axis(=1) out of bounds
```

**Comment by dangeles** [comment]
I figured initialize was not required, but the docs could be better written to reflect this. As it stands, initialize() reads like the StandardScaler() from `sklearn`.  Thanks for the help!

**Comment by josef-pkt** [comment]
It might be possible to make a repeated call to `initialize` into a no-op, but I haven't checked.

The general pattern for statsmodels is that nothing needs to be called between model instantiation and `fit` under standard usage (excluding backdoors and cheating, which are not ruled out in Python, but are not officially supported).

**Comment by josef-pkt** [comment]
> It might be possible to make a repeated call to initialize into a no-op, but I haven't checked.

My guess is that we would not want to do that in general, e.g. in OLS/WLS/GLS there is no obvious and cheap way to check whether `whiten` has already been applied.

**Comment by dangeles** [comment]
Yeah, I wasn't thinking when I called `initialize`. However, it is now concerning to me that `initialize` is described purely as a normalization, so it is concerning that calling it twice results in an error....

**Comment by josef-pkt** [comment]
Where does it say that `initialize` is for normalization?

I agree that the docstring needs to be improved and should explicitly mention that it is an internal method, even though it doesn't have a leading underline in the name.
http://www.statsmodels.org/devel/generated/statsmodels.discrete.discrete_model.MNLogit.initialize.html#statsmodels.discrete.discrete_model.MNLogit.initialize

**Comment by dangeles** [comment]
Ack, my reading skills suck, and this is a sign I should probably lay off of this now.

> initialize() | Preprocesses the data for MNLogit.

I interpreted this as a normalization step, since that's the main pre-processing that goes into these cases a lot.

**Comment by josef-pkt** [comment]
the only thing to do here are docstring improvements.

I guess we could privatize `initialize`.
In standard usage, users only needs to call the `fit` method(s) of the models, but other methods like predict, score, ... can at least be called from the outside without problems.
