### ISSUE TITLE
BUG VAR.predict is broken (again)

### ISSUE THREAD

**Issue by realdtrump** [statsmodels/statsmodels#4945]
[same as #4784]

The bug has reappeared when trying to use predict method for VAR:
AttributeError: 'super' object has no attribute '_get_predict_start'

**Comment by ChadFulton** [comment]
Thanks for the report. Can you give the version of statsmodels you're using:

```python
import statsmodels.api as sm
print(sm.version.version)
```

Along with code that reproduces the error, and the full exception traceback (including line numbers?)

**Comment by realdtrump** [comment]
It is version 0.9.0

The code goes something along this way:
import statsmodels.api as sm
from statsmodels.tsa.api import VAR
...
model = VAR(data)
results = model.fit(3)
predictions = model.predict( results.params )

The error is
Traceback (most recent call last):
  File "/n/home04/userX/.conda/envs/pd2/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-ae54ba5d5862>", line 1, in <module>
    predictions = model.predict( results.params )
  File "/n/home04/userX/.conda/envs/pd2/lib/python3.6/site-packages/statsmodels/tsa/vector_ar/var_model.py", line 535, in predict
    start = self._get_predict_start(start, lags)
  File "/n/home04/userX/.conda/envs/pd2/lib/python3.6/site-packages/statsmodels/tsa/vector_ar/var_model.py", line 529, in _get_predict_start
    return super(VAR, self)._get_predict_start(start)
AttributeError: 'super' object has no attribute '_get_predict_start'
