### ISSUE TITLE
Zero-Inflated Poisson/Negative Binomial: not predicting for arrays of different size?

### ISSUE THREAD

**Issue by Irene-GM** [statsmodels/statsmodels#4952]
Hi,

I am modelling a discrete skewed distribution with several of the available methods in `statsmodels`, namely:  `Poisson`, `Negative Binomial`, `Zero Inflated Poisson`, and `Zero Inflated Negative Binomial`. What I am doing is training with 60% of my samples, and testing the model with the remaining 40%. For this 40%, I obtain the RMSE to have a performance metric for each method.

There are no problems with the Poisson and the Negative Binomial: I use the `.fit()` method on my training samples, and the `.predict()` method on the test samples. However, I observed that for the Zero-Inflated models, **I cannot predict for the testing set**, as you can see in this snippet:

 ```
    print("Model: Zero Inflated Poisson")
    zip_mod = sm.ZeroInflatedPoisson(ytrain, xtrain).fit(method="newton", maxiter=50)
    **zip_mean_pred = zip_mod.predict(xtest)**
    zip_ppf_obs = stats.poisson.ppf(q=0.95, mu=zip_mean_pred)
    zip_rmse = np.sqrt(mean_squared_error(ytest, zip_ppf_obs))
    print("RMSE Zero-Inflated Poisson", zip_rmse)

    print("Model: Zero Inflated Neg. Binomial")
    zinb_mod = sm.ZeroInflatedNegativeBinomialP(ytrain, xtrain).fit(method="newton", maxiter=50)
    zinb_pred = zinb_mod.predict(xtest)
    zinb_rmse = np.sqrt(mean_squared_error(ytest, zinb_pred))
    print("RMSE Zero-Inflated Negative Binomial: ", zinb_rmse)
```

The error that I get says: 
```
Traceback (most recent call last):
  File "/home/irene/.../four_models.py", line 569, in <module>
    test_poi_nb_zip_zinb_tiny_subset(meta_m, m)
  File "/home/irene/.../four_models.py", line 325, in test_poi_nb_zip_zinb_tiny_subset
    **zinb_pred = zinb_mod.predict(xtest)**
  File "/home/irene/.conda/envs/defaultpy34/lib/python2.7/site-packages/statsmodels/base/model.py", line 854, in predict
    **kwargs)
  File "/home/irene/.conda/envs/defaultpy34/lib/python2.7/site-packages/statsmodels/discrete/count_model.py", line 444, in predict
    prob_zero = (1 - prob_main) + prob_main * np.exp(llf)
**ValueError: operands could not be broadcast together with shapes (480,) (320,)** 
```
Perhaps I am doing something wrong, but I do not understand why these two methods require a test sample for the predict method as big as the one used in the fitting. Is there any way to pass to these methods a test array with a different size than the training? I tried training and testing with the same dataset and it works.

Thanks a lot for all the work! :-)

**Comment by Irene-GM** [comment]
I forgot to mention that the same procedure that you see here for the zero inflated models is applied above it to the normal poisson and negative binomial with not problem. Thanks.

**Comment by josef-pkt** [comment]
Hi, there is a good chance that this is a bug. Given that the models are new, there might be cases that are not included in the test suite and that could be buggy.

Can you make a reproducible example? 
It can have random number, just so I can reproduce the shape mismatch.

(temporarily prio-high, at least until I know what's going on.)

**Comment by josef-pkt** [comment]
Based on a quick look at the source.
If exog_infl is not specified in predict, then the one of the model is used which will conflict with the predict exog.

Try to specify `exog_infl`. 
In the case of constant inflation probability as in your case, you need `exog_infl=np.ones(len(exog_predict))`

**Comment by josef-pkt** [comment]
the same is true for `exposure`, which also uses the model exposure if it is available but no predict exposure is specified.

**Comment by Irene-GM** [comment]
Thanks for the quick response! I made the following dummy code causing the error I was mentioning, I hope it is useful to trace the bug in the code.
```
import numpy as np
import statsmodels.api as sm
from scipy import stats
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

X = np.random.randint(99, size=(800, 21))
Y = np.random.randint(2, size=(800, 1))

xtrain, xtest, ytrain, ytest = train_test_split(X, Y, train_size=0.60, random_state=42)

print(xtrain.shape, ytrain.shape, xtest.shape, ytest.shape)

print("Model: Zero Inflated Poisson")
zip_mod = sm.ZeroInflatedPoisson(ytrain, xtrain).fit(method="newton", maxiter=50)
zip_mean_pred = zip_mod.predict(xtest)
zip_ppf_obs = stats.poisson.ppf(q=0.95, mu=zip_mean_pred)
zip_rmse = np.sqrt(mean_squared_error(ytest, zip_ppf_obs))

print("Model: Zero Inflated Neg. Binomial")
zinb_mod = sm.ZeroInflatedNegativeBinomialP(ytrain, xtrain).fit(method="newton", maxiter=50)
zinb_pred = zinb_mod.predict(xtest)
zinb_rmse = np.sqrt(mean_squared_error(ytest, zinb_pred))

print("RMSE Poisson: ", poi_rmse)
print("RMSE Neg. Bin.: ", nb_rmse)
print("RMSE ZIP", zip_rmse)
print("RMSE ZINB: ", zinb_rmse)
```

**Comment by Irene-GM** [comment]
If I add to the `.predict()` methods the `exog_infl` as follows:
```
zip_mean_pred = zip_mod.predict(xtest, exog_infl=np.ones(len(xtest)))
zinb_pred = zinb_mod.predict(xtest, exog_infl=np.ones(len(xtest)))
```

I get the following error:
```
Traceback (most recent call last):
  File "/home/irene/.../test_zip_zinb.py", line 29, in <module>
    zip_mean_pred = zip_mod.predict(xtest, exog_infl=np.ones(len(xtest)))
  File "/home/irene/.conda/envs/defaultpy34/lib/python2.7/site-packages/statsmodels/base/model.py", line 854, in predict
    **kwargs)
  File "/home/irene/.conda/envs/defaultpy34/lib/python2.7/site-packages/statsmodels/discrete/count_model.py", line 415, in predict
    prob_main = 1 - self.model_infl.predict(params_infl, exog_infl)
  File "/home/irene/.conda/envs/defaultpy34/lib/python2.7/site-packages/statsmodels/discrete/discrete_model.py", line 447, in predict
    return self.cdf(np.dot(exog, params))
ValueError: shapes (320,) and (1,) not aligned: 320 (dim 0) != 1 (dim 0)
```
The `.shape` of the `np.ones(len(xtest))` is `(320,)` just in case it is important.

**Comment by josef-pkt** [comment]
I just tried it. exog_infl in predict needs to be 2dim

`zip_mean_pred = zip_mod.predict(xtest, exog_infl=np.ones((len(xtest), 1)))`
this works, but the example has convergence problems or hessian inversion problem if I use method='nm' as optimizer. (The data doesn't generate anything close to ZIP or ZINB)

general aside: 
Estimation of a NegativBinomial(P) model and ZI variant **needs** overdispersion relative to Poisson in the data. If there is no overdispersion, then the loglike and derivative computation end with a zero division. Poisson is the limit of NegativeBinomial as overdispersion disappears, but computationally we need to stay away from that boundary case.
GeneralizedPoisson and it's ZI version allow for overdispersion, no excess dispersion and a small amount of underdispersion, i.e. the Poisson special case is in the interior of the GP parameter space.
(In the zi version excess dispersion refers to the non-zero inflated part.)

**Comment by Irene-GM** [comment]
I tried your fix and it works! 
```
print("Model: Zero Inflated Poisson")
zip_mod = sm.ZeroInflatedPoisson(ytrain, xtrain).fit(method="nm", maxiter=50)
zip_mean_pred = zip_mod.predict(xtest, exog_infl=np.ones((len(xtest), 1)))
zip_ppf_obs = stats.poisson.ppf(q=0.95, mu=zip_mean_pred)
zip_rmse = np.sqrt(mean_squared_error(ytest, zip_ppf_obs))

print("Model: Zero Inflated Neg. Binomial")
zinb_mod = sm.ZeroInflatedNegativeBinomialP(ytrain, xtrain).fit(method="nm", maxiter=50)
zinb_pred = zinb_mod.predict(xtest, exog_infl=np.ones((len(xtest), 1)))
zinb_rmse = np.sqrt(mean_squared_error(ytest, zinb_pred))
```
It gives some warnings as you said, like this:
```
HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  'available', HessianInversionWarning)
```
But it processes my testing dataset. Tried the "nm" and "newton" optimizers.
So now i can compute the RMSE:
```
RMSE ZIP: 1.5642490210960658
RMSE ZINB:  0.50817991749367819
```
Thanks for the super fast reaction, much appreciated!

PS - Regarding this "overdispersion", is there any paper/manual you recommend to learn more about it? :-)
