### ISSUE TITLE
Non-positive-definite forecast error covariance matrix encountered at period

### ISSUE THREAD

**Issue by StefanEkstromFFCG** [statsmodels/statsmodels#5374]
Hi,

I'm trying to get the model to work but keep getting the error message: "Non-positive-definite forecast error covariance matrix encountered at period X" 

I've used the following code:

`import pandas as pd

dataset = pd.read_csv("all_data_by_date.csv",
                      sep=",",
                     index_col=0)
dataset.index = pd.to_datetime(dataset.index)

from calendar import monthrange
from pyramid.arima import auto_arima

def number_of_days_in_month(date):
    """Takes a date as datetime and return the number of days in that month"""
    number_of_days = monthrange(date.year, date.month)[1]
    return number_of_days

#Get first weekday of month
def first_weekday_of_month(date):
    """Takes a date as datetime and return the first weekday of the month. 
    0 is Monday and 6 is Sunday."""
    first_weekday = monthrange(date.year, date.month)[0]
    return first_weekday

def get_next_predictors(predict_date):
    """Takes a datetime object and returns the predictors for that specific datetime as a pandas dataset"""
    import numpy as np
    predictors = []
    predictors.append(number_of_days_in_month(predict_date))
    predictors.append(first_weekday_of_month(predict_date))
    
    #Convert to pandas
    predictors = pd.DataFrame([predictors], index=[predict_date], columns=["n_days", "first_day"])
    
    #Convert first_day to categorical and get dummies (only 6 categories since the 7th is captured when all the other are 0)
    predictors["first_day"] = predictors["first_day"].astype('category', categories = [0, 1, 2, 3, 4, 5, 6])
    predictors = pd.get_dummies(predictors, columns=["first_day"], drop_first=True)
    return predictors

def initalize_supervised_dataset(dataset):
    """Takes in a pandas series or dataframe and return dataset with predictors"""
    predictors = None
    for date in dataset.index:
        if predictors is None:
            predictors = get_next_predictors(date)
        else:
            predictors = pd.concat([predictors, get_next_predictors(date)])
    return pd.concat([dataset, predictors], axis=1)

super_dataset = initalize_supervised_dataset(dataset)

y = super_dataset.iloc[:, :1]
X = super_dataset.iloc[:, 1:]
stepwise_model = auto_arima(y, exogenous=X, start_p=1, start_q=1,
                            max_p=3, max_q=3, m=12,
                            start_P=0, seasonal=True,
                            d=1, D=1, trace=True,
                            error_action="ignore",
                            suppress_warnings=True,
                            stepwise=True
                           )

print(stepwise_model.aic())

#Split the data
train_size = int(len(super_dataset) * 0.5)
super_train, super_test = super_dataset.iloc[:train_size,:], super_dataset.iloc[train_size:,:]
print("Train size %d months, Test size %d months" % (len(super_train), len(super_test)))

#Train the model and make predictions
history_y = super_train.iloc[:, :1]
history_X = super_train.iloc[:, 1:]
predictions = list()

for t in range(len(super_test)):
    stepwise_model.fit(history_y, exogenous=history_X)
    future_X = get_next_predictors(super_test.index[t])
    output = stepwise_model.predict(n_periods = 1, exogenous = future_X)
    yhat = output[0]
    predictions.append(yhat)
    obs = super_test.iloc[[t]]
    obs_y = obs.iloc[:,:1]
    obs_X = obs.iloc[:,1:]
    history_y = pd.concat([history_y, obs_y])
    history_X = pd.concat([history_X, obs_X])
    print('predicted=%f, expected=%f' % (yhat, obs_y.iloc[0,0]))
[all_data_by_date.zip](https://github.com/statsmodels/statsmodels/files/2565402/all_data_by_date.zip)
`

When I'm only fitting the data with number_of_days_in_month as exogenous features it works. Also, when only having dummy data like "1200" for every month, it works as well. Now I've used the pyramid arima wrapper, but the same issue occurs when using SARIMAX directly.

Statsmodels version: 0.9.0

Any help to identify the issue would be greatly appreciated! It's a great package!

**Comment by ChadFulton** [comment]
Thanks for the report!

The most likely candidate seems like something strange in your exog array -
does the data have dtype float? Are you sure there aren’t any missing
values?

If possible, please post a reproducible example.

**Comment by StefanEkstromFFCG** [comment]
Thank you for a quick answer! 
The ones that make it break are of type uint8, the number_of_days_in_month is of type int64. 

Is it not possible to run the example above? I attached the csv as a zip... Didn't know how to post it otherwise...

**Comment by ChadFulton** [comment]
> Is it not possible to run the example above? I attached the csv as a zip... Didn't know how to post it otherwise...

The example above is pretty involved, and I'm not sure where you're getting the error. For example, if  I go to just before the `auto_arima` part and instead just do:

```python
y = super_dataset.iloc[:, :1]
X = super_dataset.iloc[:, 1:]

mod = sm.tsa.SARIMAX(y, exog=X, order=(3, 1, 3), seasonal_order=(1, 0, 0, 12))
res = mod.fit()
```

this works fine for me, but it sounded like there was some SARIMAX model you were running where it didn't work?

**Comment by StefanEkstromFFCG** [comment]
Sorry for being unclear and pasting such a long snippet of code, I didn't know any good way of including the example data otherwise...

I updated the example to only use SARIMAX. When training the model the first time, everything works fine, just as you noted. However, when adding another observation and retraining the model, it breaks with the error message described above. I cannot see anything difference in the input data in the added observation from the rest

'''python

import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX

dataset = pd.read_csv("all_data_by_date.csv",
                      sep=",",
                     index_col=0)
dataset.index = pd.to_datetime(dataset.index)


from calendar import monthrange
from pyramid.arima import auto_arima

def number_of_days_in_month(date):
    """Takes a date as datetime and return the number of days in that month"""
    number_of_days = monthrange(date.year, date.month)[1]
    return number_of_days

#Get first weekday of month
def first_weekday_of_month(date):
    """Takes a date as datetime and return the first weekday of the month. 
    0 is Monday and 6 is Sunday."""
    first_weekday = monthrange(date.year, date.month)[0]
    return first_weekday


def get_next_predictors(predict_date):
    """Takes a datetime object and returns the predictors for that specific datetime as a pandas dataset"""
    import numpy as np
    predictors = []
    predictors.append(number_of_days_in_month(predict_date))
    predictors.append(first_weekday_of_month(predict_date))
    
    #Convert to pandas
    predictors = pd.DataFrame([predictors], index=[predict_date], columns=["n_days", "first_day"])
    
    #Convert first_day to categorical and get dummies (only 6 categories since the 7th is captured when all the other are 0)
    predictors["first_day"] = predictors["first_day"].astype('category', categories = [0, 1, 2, 3, 4, 5, 6])
    predictors = pd.get_dummies(predictors, columns=["first_day"], drop_first=True)
    return predictors

def initalize_supervised_dataset(dataset):
    """Takes in a pandas series or dataframe and return dataset with predictors"""
    predictors = None
    for date in dataset.index:
        if predictors is None:
            predictors = get_next_predictors(date)
        else:
            predictors = pd.concat([predictors, get_next_predictors(date)])
    return pd.concat([dataset, predictors], axis=1)

super_dataset = initalize_supervised_dataset(dataset)

y = super_dataset.iloc[:, :1]
X = super_dataset.iloc[:, 1:]


#Split the data
train_size = int(len(super_dataset) * 0.5)
super_train, super_test = super_dataset.iloc[:train_size,:], super_dataset.iloc[train_size:,:]
print("Train size %d months, Test size %d months" % (len(super_train), len(super_test)))

#Train the model and make predictions
history_y = super_train.iloc[:, :1]
history_X = super_train.iloc[:, 1:]
predictions = list()

for t in range(len(super_test)):
    sarima_model = SARIMAX(history_y, exog=history_X, 
                       order=(0, 1, 0),
                       seasonal_order=(0, 1, 0, 12))
    sarima_model = sarima_model.fit()
    future_X = get_next_predictors(super_test.index[t])
    output = sarima_model.predict(n_periods = 1, exog = future_X)
    yhat = output[0]
    predictions.append(yhat)
    obs = super_test.iloc[[t]]
    obs_y = obs.iloc[:,:1]
    obs_X = obs.iloc[:,1:]
    history_y = pd.concat([history_y, obs_y])
    history_X = pd.concat([history_X, obs_X])
    print('predicted=%f, expected=%f' % (yhat, obs_y.iloc[0,0]))'''

**Comment by ChadFulton** [comment]
Thanks for updating your example! I can't replicate this error on master, so can you let me know your version, i.e. the result of the command:

```python
import statsmodels.api as sm
print(sm.__version__)
```

**Comment by StefanEkstromFFCG** [comment]
Hmm, interesting. I'm on version 0.9.0

**Comment by ChadFulton** [comment]
Thanks! I'm able to replicate on version 0.9.0.

I guess this is a numerical issue of some kind, maybe related to the seasonal differencing at the start of the loop when you have relatively few observations. It appears to be fixed in master.

If you don't want to update, you could:

- Start your loop with more base observations (I suggest at least 25 observations here)
- Use `simple_differencing=True` in your `SARIMAX`

**Comment by StefanEkstromFFCG** [comment]
GREAT! Thank you very much for your help solving this! 😃 
I was totally lost

**Comment by rubencarmona** [comment]
I'll join @steeks91 and I have to thank you very much for your help. I faced firstly this problem 4 months ago and, looking at some other threads I couldn't find the solution. Today, I wrote again "Non-positive-definite forecast error covariance matrix encountered at period 6" and found this. Thank you!

**Comment by ChadFulton** [comment]
Glad it helped!

**Comment by ChenChingChih** [comment]
@ChadFulton  I face the similar problem!    
    Traceback (most recent call last):
    
      File "D:\Users\ChingChih\Documents\GitHub\master_thesis\0326\ox.py", line 203, in <module>
        res = model.fit()
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 667, in fit
        skip_hessian=True, **kwargs)
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\statsmodels\base\model.py", line 526, in fit
        full_output=full_output)
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\statsmodels\base\optimizer.py", line 218, in _fit
        hess=hessian)
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\statsmodels\base\optimizer.py", line 440, in _fit_lbfgs
        **extra_kwargs)
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py", line 199, in fmin_l_bfgs_b
        **opts)
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py", line 345, in _minimize_lbfgsb
        f, g = func_and_grad(x)
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py", line 290, in func_and_grad
        f = fun(x, *args)
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 327, in function_wrapper
        return function(*(wrapper_args + args))
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\statsmodels\base\model.py", line 500, in f
        return -self.loglike(params, *args) / nobs
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 897, in loglike
        loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py", line 983, in loglike
        kfilter = self._filter(**kwargs)
    
      File "C:\Users\ChingChih\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py", line 906, in _filter
        kfilter()
    
      File "statsmodels\tsa\statespace\_kalman_filter.pyx", line 2116, in statsmodels.tsa.statespace._kalman_filter.dKalmanFilter.__call__
    
      File "statsmodels\tsa\statespace\_kalman_filter.pyx", line 2196, in statsmodels.tsa.statespace._kalman_filter.dKalmanFilter.__next__
    
      File "statsmodels\tsa\statespace\_filters\_inversions.pyx", line 652, in statsmodels.tsa.statespace._filters._inversions.dsolve_cholesky
    
      File "statsmodels\tsa\statespace\_filters\_inversions.pyx", line 454, in statsmodels.tsa.statespace._filters._inversions.dfactorize_cholesky
    
    LinAlgError: Non-positive-definite forecast error covariance matrix encountered at period 0
#### data I use
[data](http://ymurasawa.web.fc2.com/bciq1m4.xls)
#### code I use
    # RNN forecasting monthly GDP, using RITS
    import pandas as pd
    import numpy as np
    from torch.nn.parameter import Parameter
    import pandas_datareader.data as web
    import datetime
    
    #torch.manual_seed(42)
    
    
    fredmd = pd.read_excel('bciq1m4.xls', header=0, index_col = 0) 
    
    from abc import ABC
    import statsmodels.api as sm
    import numpy as np
    #import matplotlib.pyplot as plt
    #import sys
    #if sys.platform == 'linux' or sys.platform == 'linux2':
    #    sys.path.append('/home/jennhong/linux_dsge')
    #    sys.path.append('/home/jennhong/octave/work')
    #else:
    #    sys.path.append("c:/uses/jennh/linux_dsge")
    np.random.seed(42)
    
    
    # Global parameters
    nburn = 0
    nsim = 100
    
    
    class MFVAR(sm.tsa.statespace.MLEModel, ABC):
        def __init__(self, endog):
    #        dummy_quarterly_obs = dummy_generator()
            n1 = 1   # number of quarterly variables (y)
            n2 = 4   # number of monthly variables (x)
            ns = (n1+n2)*5  # number of state variables
            tlen, nv = endog.shape   # number of observed v. & time length
            # actually, nv = n1+n2
            self.n1, self.n2, self.ns, self.nv = n1, n2, ns, nv
    
            super().__init__(endog, k_states=ns, k_posdef=nv,
                             initialization='stationary')
    
            # 1. time-varying design matrix Z[t]
            z0 = block_diag(1.0/3.0, 1.0, n1, n2)
            z1 = block_diag(2.0/3.0, 0.0, n1, n2)
            z2 = block_diag(1.0, 0.0, n1, n2)
            z3 = block_diag(2.0/3.0, 0.0, n1, n2)
            z4 = block_diag(1.0/3.0, 0.0, n1, n2)
            z = np.column_stack((z0, z1, z2, z3, z4))
            z0_u = block_diag(0.0, 1.0, n1, n2)
            z_u = np.column_stack((z0_u, np.zeros((nv, nv*4))))
            z_time = np.zeros((nv, ns, tlen))
            for t in range(tlen):
                #if dummy_quarterly_obs[t]:
                if np.isnan(endog[t]).any():     
                    z_time[:, :, t] = z
                else:
                    z_time[:, :, t] = z_u
            self['design'] = z_time
    
            # # 2. time-varying observation disturbance H[t]
            # when y is observable
            h = np.zeros((nv, nv))
            # when y is unobservable
            h_u = block_diag(1.0, 0.0, n1, n2)  # random variable N(0, 1)
            h_time = np.zeros((nv, nv, tlen))
            for t in range(tlen):
                #if dummy_quarterly_obs[t]:
                if np.isnan(endog[t]).any():
                    h_time[:, :, t] = h
                else:
                    h_time[:, :, t] = h_u
            self['obs_cov'] = h_time
            # self['obs_cov'] = np.eye(nv)
    
            # 3. time-invariant selection matrix R
            self['selection'] = np.eye(ns, nv)
    
        def update(self, params, transformed=True, **kwargs):
            n1, n2, ns, nv = self.n1, self.n2, self.ns, self.nv
            # nv = n1 + n2
            # ns = 5 * nv
    
            # 4. time-invariant transition matrix T
            var_coef = params[:nv**2].reshape(nv, nv)
            var_coef = np.column_stack((var_coef, np.zeros((nv, nv*4))))
            self['transition'] = np.row_stack((var_coef, np.eye(nv*4, ns)))
    
            # 5. time-invariant state covariance Q
            tril_state_cov = vec_tril(params[nv**2:])   # lower-triangular matrix
            self['state_cov'] = tril_state_cov @ tril_state_cov.transpose() #為何有@:矩陣相乘
    
        @property
        def start_params(self):
            phi_11, phi_12, phi_13, phi_14, phi_15 = 0.1, 0., 0., 0., 0.   # initial guess
            phi_21, phi_22, phi_23, phi_24, phi_25 = 0., 1.0, 0., 0., 0.  # initial guess
            phi_31, phi_32, phi_33, phi_34, phi_35 = 0., 0., 2.0, 0., 0.  # initial guess
            phi_41, phi_42, phi_43, phi_44, phi_45 = 0., 0., 0., 1.0, 0.  # initial guess
            phi_51, phi_52, phi_53, phi_54, phi_55 = 0.8, 0., 0., 0., 1.0  # initial guess
            sig_11 =  1.0
            sig_21, sig_22 =  0., 1.0
            sig_31, sig_32, sig_33 =  0., 0., 7.0
            sig_41, sig_42, sig_43, sig_44 =  0., 0., 0., 3.0
            sig_51, sig_52, sig_53, sig_54, sig_55 =  0., 0., 0., 0., 5.0
            return np.array([phi_11, phi_12, phi_13, phi_14, phi_15,
                             phi_21, phi_22, phi_23, phi_24, phi_25,
                             phi_31, phi_32, phi_33, phi_34, phi_35,
                             phi_41, phi_42, phi_43, phi_44, phi_45,
                             phi_51, phi_52, phi_53, phi_54, phi_55,
                            sig_11, 
                            sig_21, sig_22, 
                            sig_31, sig_32, sig_33, 
                            sig_41, sig_42, sig_43, sig_44, 
                            sig_51, sig_52, sig_53, sig_54, sig_55])
    
    
    def block_diag(a, b, n1, n2):
        """
        Create block diagonal matrix of this form:
         a*I |  0
        -----+-----
         0   |  b*I
         The size of the upper left corner is (n1, n1)
         The size of the lower right corner is (n2, n2)
        """
        upper_left = np.identity(n1)*a
        lower_right = np.identity(n2)*b
        upper_right = np.zeros((n1, n2))
        lower_left = np.zeros((n2, n1))
        upper = np.column_stack((upper_left, upper_right))
        lower = np.column_stack((lower_left, lower_right))
        z0 = np.row_stack((upper, lower))
        return z0
    
    
    def vec_tril(x, order='C'):
        """
        Reverse half-vectorization into a triangular matrix in the order of C or F(ortran)
        If x is complex, ivech(x) is conjugate symmetric.
        That is, ivech(x) = ivech(x).transpose().conj()
        """
        r = len(x)
        n = np.int((np.sqrt(1+8*r)-1)/2)
        # if all(np.isreal(x)):
        #     a_mat = np.zeros((n, n))
        # else:
        #     a_mat = np.zeros((n, n), 'complex')
        #although you want the dtype to be complex. i.e. np.isreal(np.array([1, 2, 3]) + 0j) returns True.
        a_mat = np.zeros((n, n), dtype=x.dtype)
        
        if order == 'C':
            d = np.tril_indices(n)
            a_mat[d] = x
        else:
            a_mat[:, 0] = x[0:n]
            oldindex = n
            for ii in np.arange(1, n):
                newindex = oldindex + n - ii
                a_mat[ii:n, ii] = x[oldindex:newindex]
                oldindex = newindex
        return a_mat
    
    
    def dummy_generator():
        dummy = [1, 0, 0]*nsim
        dummy = np.array(dummy, dtype=int)
        return dummy
    
    
    def data_generator():
        # % artificial data
        phi_11, phi_12, phi_21, phi_22 = 0.8, 0., 0., 0.5  # initial guess
        sig_11, sig_12, sig_22 = 0.5, 0.0, 0.5
        params = [phi_11, phi_12, phi_21, phi_22, sig_11, sig_12, sig_22]
        params = np.array(params)
        model_true = MFVAR(np.zeros((nsim*3, 2)))
        consumption = model_true.simulate(params, nsim*3)  # % consumption
        # consumption = np.delete(consumption, np.arange(burn))
        return consumption
    
    
    # SS fit
    #data_consumption = data_generator()
    fredmd1 = fredmd.to_numpy()
    model = MFVAR(fredmd1)
    res = model.fit()
    print(res.summary())
    
    mphi = res.params[0:25].reshape(5,5)
    a = np.zeros((5, 5), float)
    np.fill_diagonal(a, vec_tril(res.params[25:]).diagonal())
    msigma = vec_tril(res.params[25:]) + vec_tril(res.params[25:]).T - a

#### Output of ``import statsmodels.api as sm; sm.show_versions()``
    INSTALLED VERSIONS
    ------------------
    Python: 3.7.4.final.0
    
    statsmodels
    ===========
    
    Installed: 0.12.0.dev0+195.g1ccd5cdba (C:\Users\ChingChih\Anaconda3\lib\site-packages\statsmodels)
    
    Required Dependencies
    =====================
    
    cython: 0.29.15 (C:\Users\ChingChih\Anaconda3\lib\site-packages\Cython)
    numpy: 1.18.1 (C:\Users\ChingChih\Anaconda3\lib\site-packages\numpy)
    scipy: 1.4.1 (C:\Users\ChingChih\Anaconda3\lib\site-packages\scipy)
    pandas: 1.0.3 (C:\Users\ChingChih\Anaconda3\lib\site-packages\pandas)
        dateutil: 2.8.1 (C:\Users\ChingChih\Anaconda3\lib\site-packages\dateutil)
    patsy: 0.5.1 (C:\Users\ChingChih\Anaconda3\lib\site-packages\patsy)
    
    Optional Dependencies
    =====================
    
    matplotlib: 3.2.1 (C:\Users\ChingChih\Anaconda3\lib\site-packages\matplotlib)
        backend: module://ipykernel.pylab.backend_inline 
    cvxopt: Not installed
    joblib: 0.14.1 (C:\Users\ChingChih\Anaconda3\lib\site-packages\joblib)
    
    Developer Tools
    ================
    
    IPython: 7.13.0 (C:\Users\ChingChih\Anaconda3\lib\site-packages\IPython)
        jinja2: 2.11.1 (C:\Users\ChingChih\Anaconda3\lib\site-packages\jinja2)
    sphinx: 2.4.4 (C:\Users\ChingChih\Anaconda3\lib\site-packages\sphinx)
        pygments: 2.6.1 (C:\Users\ChingChih\Anaconda3\lib\site-packages\pygments)
    pytest: Not installed
    virtualenv: Not installed

**Comment by ChadFulton** [comment]
@ChenChingChih the problem seems to be that your starting parameters imply a non-stationary model (i.e. the VAR coefficient matrix has eigenvalues outside the unit circle) but you have specified `initialization='stationary'`, which is not valid for a non-stationary model.

If you want to allow for explosive dynamics, you can use diffuse initialization.

**Comment by ChenChingChih** [comment]
thank you @ChadFulton ! Sorry for a late reply...

**Comment by MIbrahimQuadri** [comment]
Hey @ChadFulton 
I am encountering a similar error which says the below. any chance you could please guide me on how to to fix this?
**LinAlgError: Non-positive-definite forecast error covariance matrix encountered at period 2**

Below is the full code that yields this error:

`#%% import data

df = pd.read_excel(input_path + 'DataInflShortLongUpdated.xlsx',
                   sheet_name = 'Data',
                   usecols = "A:V",
                   index_col = 0,
                   parse_dates = True)
df.index = df.index.to_period('a')

# restrict to the inflation dataset
df = df[[x for x in df.columns if 'cpi' in x]]

# log difference the cpi index to get annual inflation rate
df = np.log(df).diff() * 100

# restrict the data to US and UK
data = pd.concat([df['cpi_usa'], df['cpi_uk']], axis=1)


#%% write the state space model

# create a new class with parent MLEModel class
class SSM(sm.tsa.statespace.MLEModel):
    
    # define the starting/initial parameters
    param_dict = {
            'lam_us' : 1,
            'lam_gb' : 1,
            'phi_us' : 0.5, # guess
            'phi_gb' : 0.5, # guess
            'eps_var_w' : 1/50,
            'eps_var_us' : 1/50,
            'eps_var_gb' : 1/50,
            'eta_var_us' : 16,
            'eta_var_gb' : 16,
            }
    
    start_params = list(param_dict.values()) # 9 parameters in total
    param_names = list(param_dict.keys())
    
    # define model
    def __init__(self, endog):
        super(SSM, self).__init__(endog, k_states = 5, k_posdef = 5)
        
        
        # specify fixed elements of the model
        self['design'] = np.array([[1,1,0,1,0],
                                   [1,0,1,0,1]])
        self['transition'] = np.eye(5)
        self['selection'] = np.eye(5)
        
        
        # provide initial states and distribution
        init = initialization.Initialization(self.k_states)
        init.set((0, 3), 'known', constant = [2, 0, 0], stationary_cov = np.diag([4, 1, 1]))
        init.set((3, 5), 'stationary') # check if there is a way to provivde constant mean values while keeping the variance to be stationary
        self.ssm.initialize(init)
         
        
        # transform parameters (i.e., constrain the parameters as needed)
        def transform_params(self, unconstrained):
            constrained = np.zeros_like(unconstrained)
            constrained[0:2] = unconstrained[0:2] # no transformation applied to the loading factors
            constrained[2:4] = constrain_stationary_univariate(unconstrained[2:4])
            constrained[4:9] = unconstrained[4:9] ** 2
            return constrained
        
        def untransform_params(self, constrained):
            unconstrained = np.zeros_like(constrained)
            unconstrained[0:2] = constrained[0:2] # no transformation applied to the loading factors
            unconstrained[2:4] = unconstrain_stationary_univariate(constrained[2:4])
            constrained[4:9] = unconstrained[4:9] ** 0.5
            return unconstrained
        
        
        # update estimated parameters
        def update(self, params, **kwargs):
            params = super(SSM, self).update(params, **kwargs)
            
            # update the parameters vectors/matrices
            self['design', 0, 0] = params[0]
            self['design', 1, 0] = params[1]
            
            self['transition', 3, 3] = params[2]
            self['transition', 4, 4] = params[3]
            
            self['state_cov', 0, 0] = params[4]
            self['state_cov', 1, 1] = params[5]
            self['state_cov', 2, 2] = params[6]
            self['state_cov', 3, 3] = params[7]
            self['state_cov', 4, 4] = params[8]


#%% run state space model

ssm_model = SSM(data)
ssm_results = ssm_model.fit(method = 'nm', maxiter = 1000)
print(ssm_results.summary())`
