### ISSUE TITLE
error importing `statsmodels`

### ISSUE THREAD

**Issue by jbloom** [statsmodels/statsmodels#5411]
I have `statsmodels` that I just installed with `pip`. I get the following error when I try to import it:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fh/fast/bloom_j/software/conda/envs/BloomLab_v2/lib/python3.6/site-packages/statsmodels/__init__.py", line 10, in <module>
    from statsmodels.tools.sm_exceptions import (ConvergenceWarning, CacheWriteWarning,
ModuleNotFoundError: No module named 'statsmodels.tools'
```

**Comment by jbloom** [comment]
I think you are correct. I clean installed my `conda` environment and the problem went away. I'm closing the issue.
