### ISSUE TITLE
missing='drop' returning "Exception: Data must be 1-dimensional" error for sm.Logit

### ISSUE THREAD

**Issue by jtamerius** [statsmodels/statsmodels#5445]
I am trying to perform binary logit and my data has some NaN. It looks like I should be able to use the "missing='drop'" option but I am getting an exception ("Exception: Data must be 1-dimensional"). I am using statsmodel version 0.6.1.

```
import statsmodels.api as sm

...
logit = sm.Logit(y,x,missing='drop')
```

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Anaconda\envs\geo\lib\site-packages\statsmodels\discrete\discrete_model.py", line 418, in __init__
    super(BinaryModel, self).__init__(endog, exog, **kwargs)
  File "C:\Anaconda\envs\geo\lib\site-packages\statsmodels\discrete\discrete_model.py", line 171, in __init__
    super(DiscreteModel, self).__init__(endog, exog, **kwargs)
  File "C:\Anaconda\envs\geo\lib\site-packages\statsmodels\base\model.py", line 212, in __init__
    super(LikelihoodModel, self).__init__(endog, exog, **kwargs)
  File "C:\Anaconda\envs\geo\lib\site-packages\statsmodels\base\model.py", line 64, in __init__
    **kwargs)
  File "C:\Anaconda\envs\geo\lib\site-packages\statsmodels\base\model.py", line 87, in _handle_data
    data = handle_data(endog, exog, missing, hasconst, **kwargs)
  File "C:\Anaconda\envs\geo\lib\site-packages\statsmodels\base\data.py", line 633, in handle_data
    **kwargs)
  File "C:\Anaconda\envs\geo\lib\site-packages\statsmodels\base\data.py", line 65, in __init__
    **kwargs)
  File "C:\Anaconda\envs\geo\lib\site-packages\statsmodels\base\data.py", line 261, in handle_missing
    nan_mask = _nan_rows(*combined)
  File "C:\Anaconda\envs\geo\lib\site-packages\statsmodels\base\data.py", line 47, in _nan_rows
    return reduce(_nan_row_maybe_two_inputs, arrs).squeeze()
  File "C:\Anaconda\envs\geo\lib\site-packages\statsmodels\base\data.py", line 46, in _nan_row_maybe_two_inputs
    (x_is_boolean_array | _asarray_2d_null_rows(y)))
  File "C:\Anaconda\envs\geo\lib\site-packages\pandas\core\ops.py", line 936, in wrapper
    index=self.index)).__finalize__(self)
  File "C:\Anaconda\envs\geo\lib\site-packages\pandas\core\series.py", line 248, in __init__
    raise_cast_failure=True)
  File "C:\Anaconda\envs\geo\lib\site-packages\pandas\core\series.py", line 3027, in _sanitize_array
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional

**Comment by rgrasmus** [comment]
I'm having the same issue with my own dataset. It only occurs when missing='drop' is called. I tried it for a single column of the dataset that did not have any NaNs and the error is only raised when missing='drop' is called. The packages are imported properly (eg "import pandas as pd" and "import statsmodels.api as sm"). The package versions are statsmodels==0.9.0 and pandas==0.23.0

**Comment by josef-pkt** [comment]
Can you make a reproducible example?

I have no guess what might be wrong based on the traceback and without data.

**Comment by rgrasmus** [comment]
Ah, it looks like the error occurs when the endog is boolean data along with the above missing='drop'. Here is a minimal reproducible example:

`import pandas as pd
import numpy as np
import statsmodels.api as sm

x = np.linspace(0,1)
y = 5*x-3
Data = np.stack([x,y]).T
myDf = pd.DataFrame(data=Data,columns=['x','y'])
myDf['Bool_X'] = myDf['x']>0.5
mod = sm.Logit(myDf['Bool_X'], myDf['y'], missing='drop')`

**Comment by josef-pkt** [comment]
So, if you convert the bool to int, then the same example works?

It's a bug, but I'm not familiar with the code behind this.

**Comment by rgrasmus** [comment]
Yup, it worked fine on my dataset after casting the endog column to int.

**Comment by josef-pkt** [comment]
The problem could be that pandas creates an object dtype for the bool with missing values and then numpy does not work in the usual way as for numeric dtypes.

At least there is a clear workaround. 
Thanks @rgrasmus
