### ISSUE TITLE
SARIMAX python np.linalg.linalg.LinAlgError: LU decomposition error

### ISSUE THREAD

**Issue by ncabay** [statsmodels/statsmodels#5459]
Hello,
I have a problem with time series analysis. I have a dataset with 5 features. Following is the subset of my input dataset:

date,price,year,day,totaltx
1/1/2016 0:00,434.46,2016,1,126762
1/2/2016 0:00,433.59,2016,2,147449
1/3/2016 0:00,430.36,2016,3,148661
1/4/2016 0:00,433.49,2016,4,185279
1/5/2016 0:00,432.25,2016,5,178723
1/6/2016 0:00,429.46,2016,6,184207

My endogenous data is price column and exogenous data is totaltx price.
**This is the code I am running and getting an error:**

```
import statsmodels.api as sm
import pandas as pd
import numpy as np
from numpy.linalg import LinAlgError

def arima(filteredData, coinOutput, window, horizon, trainLength):
    start_index = 0
    end_index = 0
    inputNumber = filteredData.shape[0]
    predictions = np.array([], dtype=np.float32)
    prices = np.array([], dtype=np.float32)
    # sliding on time series data with 1 day step
    while ((end_index) < inputNumber - 1):
        end_index = start_index + trainLength
        trainFeatures = filteredData[start_index:end_index]["totaltx"]
        trainOutput = coinOutput[start_index:end_index]["price"]

        arima = sm.tsa.statespace.SARIMAX(endog=trainOutput.values, exog=trainFeatures.values, order=(window, 0, 0))
        arima_fit = arima.fit(disp=0)
        testdata=filteredData[end_index:end_index+1]["totaltx"]
        total_sample = end_index-start_index
        predicted = arima_fit.predict(start=total_sample, end=total_sample, exog=np.array(testdata.values).reshape(-1,1))
        price = coinOutput[end_index:end_index + 1]["price"].values

        predictions = np.append(predictions, predicted)
        prices = np.append(prices, price)

        start_index = start_index + 1
    return predictions, prices

def processCoins(bitcoinPrice, window, horizon):
    output = bitcoinPrice[horizon:][["date", "day", "year", "price"]]
    return output

trainLength=100;
for window in [3,5]:
    for horizon in [1,2,5,7,10]:
        bitcoinPrice = pd.read_csv("..\\prices.csv", sep=",")
        coinOutput = processCoins(bitcoinPrice, window, horizon)
        predictions, prices = arima(bitcoinPrice, coinOutput, window, horizon, trainLength)

```
In this code, I am using rolling window regression technique. I am training arima for start_index:end_index and predicting the test data with end_index:end_index+1

**This the error that is thrown from my code:**
```
Traceback (most recent call last):
  File "C:/PycharmProjects/coinLogPrediction/src/arima.py", line 115, in <module>
    predictions, prices = arima(filteredBitcoinPrice, coinOutput, window, horizon, trainLength, outputFile)
  File "C:/PycharmProjects/coinLogPrediction/src/arima.py", line 64, in arima
    arima_fit = arima.fit(disp=0)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 469, in fit
    skip_hessian=True, **kwargs)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\base\model.py", line 466, in fit
    full_output=full_output)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\base\optimizer.py", line 191, in _fit
    hess=hessian)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\base\optimizer.py", line 410, in _fit_lbfgs
    **extra_kwargs)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py", line 328, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py", line 273, in func_and_grad
    f = fun(x, *args)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\base\model.py", line 440, in f
    return -self.loglike(params, *args) / nobs
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 646, in loglike
    loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py", line 825, in loglike
    kfilter = self._filter(**kwargs)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py", line 747, in _filter
    self._initialize_state(prefix=prefix, complex_step=complex_step)
  File "C:\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\representation.py", line 723, in _initialize_state
    self._statespaces[prefix].initialize_stationary(complex_step)
  File "_representation.pyx", line 1351, in statsmodels.tsa.statespace._representation.dStatespace.initialize_stationary
  File "_tools.pyx", line 1151, in statsmodels.tsa.statespace._tools._dsolve_discrete_lyapunov
numpy.linalg.linalg.LinAlgError: LU decomposition error.
```

I believe that there is a bug in statsmodels if I do not have any error. Can you please help me to solve it?

**Comment by SureshArr** [comment]
I have run into the same issue on Python 3.7.2, statsmodels 0.9.0. Setting initialization='approximate_diffuse' in the SARIMAX call helps to avoid the error.

Per your suggestion on https://stackoverflow.com/questions/54136280/sarimax-python-np-linalg-linalg-linalgerror-lu-decomposition-error,
from scipy import linalg
print(linalg.lapack.dgetrf([np.nan]))
print(linalg.lapack.dgetrf([np.inf]))
... outputs ... 
(array([nan]), array([0], dtype=int32), 0)
(array([inf]), array([0], dtype=int32), 0)

Thank you.

**Comment by alexsmartens** [comment]
I've got this problem too. I'm seeing `numpy.linalg.LinAlgError: LU decomposition error`
### Replication example
* dataset:  [my_data_sample.csv](https://drive.google.com/file/d/1hNdI65sRd_MmeK_FpS-Ec4zrQ4gAtW-O/view)

* code:
```
import pandas as pd
import statsmodels.api as sm

endog = pd.read_csv('my_data_sample.csv', index_col=[0])['1b']
order = (25, 1, 21)
seasonal_order = (0, 0, 0, 0)

mod = sm.tsa.SARIMAX(endog, order=order, seasonal_order=seasonal_order)
res = mod.fit(disp=0)
print(res.llf)
```

**Comment by alexsmartens** [comment]
As per previous suggestion, 
```
import numpy as np
from scipy import linalg
print(linalg.lapack.dgetrf([np.nan]))
print(linalg.lapack.dgetrf([np.inf]))
```
Output:
```
(array([nan]), array([0], dtype=int32), 0)
(array([inf]), array([0], dtype=int32), 0)
```

**Comment by alexsmartens** [comment]
@ChadFulton, @bashtage,
were you able to replicate this error?

**Comment by bashtage** [comment]
Model estimates for me without issue on Windows.
```
import pandas as pd
import statsmodels.api as sm

endog = pd.read_csv('my_data_sample.csv', index_col=[0])['1b']
order = (25, 1, 21)
seasonal_order = (0, 0, 0, 0)

mod = sm.tsa.SARIMAX(endog, order=order, seasonal_order=seasonal_order)
res = mod.fit(disp=0)
print(res.llf)
c:\git\statsmodels\statsmodels\tsa\statespace\sarimax.py:959: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
27662.36341690524
```

**Comment by bashtage** [comment]
This does not look liek a sensible model
```
ar.L1     0.002454
ar.L2    -0.001238
ar.L3    -0.004040
ar.L4    -0.003733
ar.L5     0.000023
ar.L6     0.003945
ar.L7     0.003790
ar.L8     0.000220
ar.L9    -0.003202
ar.L10   -0.003236
ar.L11   -0.000019
ar.L12    0.001810
ar.L13    0.001179
ar.L14   -0.000020
ar.L15    0.000488
ar.L16    0.001268
ar.L17   -0.000188
ar.L18   -0.002657
ar.L19   -0.002871
ar.L20    0.000396
ar.L21    0.004333
ar.L22    0.003714
ar.L23   -0.000790
ar.L24   -0.004197
ar.L25   -0.003927
ma.L1     0.405848
ma.L2     0.970924
ma.L3     0.619739
ma.L4     0.510109
ma.L5     0.594587
ma.L6     0.456341
ma.L7     0.738567
ma.L8     0.335967
ma.L9     0.230263
ma.L10    0.494425
ma.L11    0.238442
ma.L12    0.554102
ma.L13    0.095503
ma.L14    0.009116
ma.L15   -0.147249
ma.L16   -0.159329
ma.L17    0.155134
ma.L18   -0.055530
ma.L19   -0.081475
ma.L20   -0.112965
ma.L21   -0.336345
sigma2    0.002654
```

**Comment by alexsmartens** [comment]
I ran this model fitting on multiple `Ubuntu 18.04` systems with `Statsmodels 0.11.0.dev0+563.g044456ca7`. I just double checked and reran the code, and I'm still having the same error. Here is my full error log:
```
/home/ubuntu/anaconda3/envs/my_env/bin/python /home/ubuntu/Projects/my_project/my_program.py
/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:959: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
Traceback (most recent call last):
  File "/home/ubuntu/Projects/my_project/my_program .py", line 9, in <module>
    res = mod.fit(disp=0)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 633, in fit
    skip_hessian=True, **kwargs)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/statsmodels/base/model.py", line 526, in fit
    full_output=full_output)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/statsmodels/base/optimizer.py", line 218, in _fit
    hess=hessian)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/statsmodels/base/optimizer.py", line 440, in _fit_lbfgs
    **extra_kwargs)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 199, in fmin_l_bfgs_b
    **opts)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 335, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 280, in func_and_grad
    f = fun(x, *args)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 326, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/statsmodels/base/model.py", line 500, in f
    return -self.loglike(params, *args) / nobs
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 864, in loglike
    loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 879, in loglike
    kfilter = self._filter(**kwargs)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 799, in _filter
    self._initialize_state(prefix=prefix, complex_step=complex_step)
  File "/home/ubuntu/anaconda3/envs/my_env/lib/python3.7/site-packages/statsmodels/tsa/statespace/representation.py", line 760, in _initialize_state
    complex_step=complex_step)
  File "statsmodels/tsa/statespace/_representation.pyx", line 1328, in statsmodels.tsa.statespace._representation.dStatespace.initialize
  File "statsmodels/tsa/statespace/_representation.pyx", line 1321, in statsmodels.tsa.statespace._representation.dStatespace.initialize
  File "statsmodels/tsa/statespace/_initialization.pyx", line 288, in statsmodels.tsa.statespace._initialization.dInitialization.initialize
  File "statsmodels/tsa/statespace/_initialization.pyx", line 406, in statsmodels.tsa.statespace._initialization.dInitialization.initialize_stationary_stationary_cov
  File "statsmodels/tsa/statespace/_tools.pyx", line 1206, in statsmodels.tsa.statespace._tools._dsolve_discrete_lyapunov
numpy.linalg.LinAlgError: LU decomposition error.
```

**Comment by ChadFulton** [comment]
Ultimately the issue here is the behavior when the parameters imply a non-stationary model, but only barely. I would guess that the symptom of an exception being raised (or not) has to do with the underlying LAPACK library.

Can you check what happens if you run the following?

```python
mod = sm.tsa.SARIMAX(np.zeros(10))
res = mod.filter([1, 1.])
res.filter_results.initial_state_cov
```

I'm guessing that you will get an exception.  When I run this, I get:

```
```

**Comment by ChadFulton** [comment]
(previous comment was submitted too fast)

Ultimately the issue here is the behavior when the parameters imply a non-stationary model, but only barely. I would guess that the symptom of an exception being raised (or not) has to do with the underlying LAPACK library.

Can you check what happens if you run the following?

```python
mod = sm.tsa.SARIMAX(np.zeros(10))
res = mod.filter([1, 1.])
res.filter_results.initial_state_cov
```

I'm guessing that you will get an exception.  When I run this, I get:

```python
[[-4.98960077e+291]]
```

and of course this is not a valid covariance matrix. That is because there when the process is not covariance stationary then of course there is no stationary distribution, but the default initialization method, "stationary", tries to solve for such a distribution. That's why @SureshArr was able to solve the problem by using diffuse initialization, which does not assume a stationary distribution.

The problem is not the above example, though, where an error is appropriate because I have specified a non-stationary model. Solving for the stationary covariance requires solving a discrete Lyapunov equation, and the problem is what precision the underlying solver is able to handle.

To see this, just consider using `scipy.linalg.solve_discrete_lyapunov`. For me, I get:

```python
> print(solve_discrete_lyapunov([[1 - 6e-17]], [[1.]]))
array([[4.50359963e+15]])
> print(solve_discrete_lyapunov([[1 - 5e-17]], [[1.]]))
...
LinAlgError: Matrix is singular.
```

Both of these models are theoretically stationary, but somewhere between `1-6e-17` and `1-5e-17`, we lose enough precision that the model appears non-stationary.

Anyway, we use an internal Cython version of the discrete Lyapunov solver, and when you get the LU error, that's basically responding to the same numerical problem that causes the `LinAlgError: Matrix is singular.` above.

Okay, so what should be done?

1. In the example I gave above, we should probably raise an exception rather than run the Kalman filter with that invalid (negative) covariance matrix.
2. Rather than the LU decomposition error, we should raise a more information error ('Implied model is not stationary to numerical precision' or something).

But I don't think we can prevent this error condition from developing in all cases. We use a parameter transformation method to enforce parameters implying stationary models, but we can't (as far as I know) enforce that it will be stationary to whatever precision is required by the discrete Lyapunov solver.

**Comment by alexsmartens** [comment]
My results are the same as yours:
```
mod = sm.tsa.SARIMAX(np.zeros(10))
res = mod.filter([1, 1.])

print(res.filter_results.initial_state_cov)
print(scipy.linalg.solve_discrete_lyapunov([[1 - 6e-17]], [[1.]]))
print(scipy.linalg.solve_discrete_lyapunov([[1 - 5e-17]], [[1.]]))
```
```
> [[-4.98960077e+291]]
> [[4.50359963e+15]]
> numpy.linalg.LinAlgError: Matrix is singular.
```

**Comment by ChadFulton** [comment]
Thanks for checking in. I guess that the linear algebra error doesn't show up in all non-stationary cases, but I can replicate the LU decomposition error with e.g.:

```python
mod = sarimax.SARIMAX(np.zeros(10), order=(2, 0, 0))
res = mod.filter([1, 2., 1.])
```

**Comment by alexsmartens** [comment]
> ```python
> mod = sarimax.SARIMAX(np.zeros(10), order=(2, 0, 0))
> res = mod.filter([1, 2., 1.])
> ```

I see the LU decomposition error with this example too

**Comment by AlexFuster** [comment]
Same error here

**Comment by bashtage** [comment]
> ```python
> mod = sarimax.SARIMAX(np.zeros(10), order=(2, 0, 0))
> res = mod.filter([1, 2., 1.])
> ```

This throwing an error that suggests the matrix being factorized is exactly singular, and so there is no solution to the set of equations.

**Comment by i-pk** [comment]
Hi folks,
I was having the same error,

Erroneous code:
mod = sm.tsa.SARIMAX(y, order=(0 1,0), seasonal_order=(1,0,0,12))
res = mod.fit()

This gave me error : 
LinAlgError: Schur decomposition solver error

I was able to solve this error after doing some modification in code:
mod = sm.tsa.SARIMAX(y, order=(0 1,0), seasonal_order=(1,0,0,12),enforce_stationarity=False)
res = mod.fit()


Hope this helps..🙂

**Comment by FoxFenya** [comment]
Good  morning.
I have the following model:
```
x8=[11862, 13079.4, 15704.1, 16117.5, 16175.9, 16172.1, 19346.1, 38204.5, 49605.5, 33171, 12728.3, 13951.5, 11343.3, 13157.5, 13839.3, 14497.5, 15427.3, 14420.4, 24202.3, 30710.2, 24675.3, 22392.1, 15182.5, 16155.2, 13123.3, 12768.6, 16292.3, 16617.2, 17164.3, 17145.4, 23225.3,  31324.2, 42991.3, 31658.2, 15718.4, 12853.6, 13397.1, 13681.5,  15182.5, 7623.843544, 4133.86649, 2737.872985]
print(x8)
arimats = sm.tsa.statespace.SARIMAX(x8, order=((1,1,0,0,0,0,1,1,0,0,0,1), 1, (1,1,1,1,0,0,0,1,1,1,1,1)), trend='c')
results = arimats.fit(disp=0)
print(results.summary())
```
which give me following error:
```
G:\work\Python\venv\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:901: RuntimeWarning: Mean of empty slice.
  params_variance = (residuals[k_params_ma:]**2).mean()
G:\work\Python\venv\lib\site-packages\numpy\core\_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
G:\work\Python\venv\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:963: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
G:\work\Python\venv\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:1027: RuntimeWarning: invalid value encountered in less
  params_variance = np.atleast_1d(max(np.array(params_variance), 1e-10))
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.4\plugins\python-ce\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.4\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "G:/work/Python/work.py", line 272, in <module>
    results = arimats.fit(disp=0)
  File "G:\work\Python\venv\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 659, in fit
    skip_hessian=True, **kwargs)
  File "G:\work\Python\venv\lib\site-packages\statsmodels\base\model.py", line 526, in fit
    full_output=full_output)
  File "G:\work\Python\venv\lib\site-packages\statsmodels\base\optimizer.py", line 218, in _fit
    hess=hessian)
  File "G:\work\Python\venv\lib\site-packages\statsmodels\base\optimizer.py", line 440, in _fit_lbfgs
    **extra_kwargs)
  File "G:\work\Python\venv\lib\site-packages\scipy\optimize\lbfgsb.py", line 199, in fmin_l_bfgs_b
    **opts)
  File "G:\work\Python\venv\lib\site-packages\scipy\optimize\lbfgsb.py", line 345, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "G:\work\Python\venv\lib\site-packages\scipy\optimize\lbfgsb.py", line 290, in func_and_grad
    f = fun(x, *args)
  File "G:\work\Python\venv\lib\site-packages\scipy\optimize\optimize.py", line 327, in function_wrapper
    return function(*(wrapper_args + args))
  File "G:\work\Python\venv\lib\site-packages\statsmodels\base\model.py", line 500, in f
    return -self.loglike(params, *args) / nobs
  File "G:\work\Python\venv\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 889, in loglike
    loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)
  File "G:\work\Python\venv\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py", line 977, in loglike
    kfilter = self._filter(**kwargs)
  File "G:\work\Python\venv\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py", line 897, in _filter
    self._initialize_state(prefix=prefix, complex_step=complex_step)
  File "G:\work\Python\venv\lib\site-packages\statsmodels\tsa\statespace\representation.py", line 950, in _initialize_state
    complex_step=complex_step)
  File "statsmodels\tsa\statespace\_representation.pyx", line 1341, in statsmodels.tsa.statespace._representation.dStatespace.initialize
  File "statsmodels\tsa\statespace\_representation.pyx", line 1334, in statsmodels.tsa.statespace._representation.dStatespace.initialize
  File "statsmodels\tsa\statespace\_initialization.pyx", line 288, in statsmodels.tsa.statespace._initialization.dInitialization.initialize
  File "statsmodels\tsa\statespace\_initialization.pyx", line 406, in statsmodels.tsa.statespace._initialization.dInitialization.initialize_stationary_stationary_cov
  File "statsmodels\tsa\statespace\_tools.pyx", line 1284, in statsmodels.tsa.statespace._tools._dsolve_discrete_lyapunov
numpy.linalg.LinAlgError: Schur decomposition solver error.
```
but if I estimate same model in EViews 8 everything is fine and get following resalts:
```
Dependent Variable: D(X8_SELH)				
Method: Least Squares							
Sample (adjusted): 14 42				
Included observations: 29 after adjustments				
Convergence achieved after 27 iterations				
MA Backcast: 2 13				
				
Variable	Coefficient	Std. Error	t-Statistic	Prob.  
				
C	-141.7014351111465	2411.692491347072	-0.05875601289117833	0.9539768830154852
AR(1)	0.4888321752359961	0.3032011216523018	1.612237357738301	0.1292177441320149
AR(2)	-0.269073872605583	0.2759878673985239	-0.9749481929835809	0.3461319285956381
AR(7)	-0.07480108655403679	0.2345011535973987	-0.3189796101492038	0.7544514341212291
AR(8)	-0.09598503257169881	0.3338611796218039	-0.287499830559606	0.7779413864768987
AR(12)	0.5366312922904591	0.2793446293137732	1.921036726600852	0.07532728154533474
MA(1)	-0.4550973692816319	0.3593869062383028	-1.266315943574931	0.2260649585838845
MA(2)	-0.1111162656550283	0.5085687740381292	-0.2184881796275945	0.8302016300068391
MA(3)	-0.1790735773867052	0.1993304358476184	-0.8983754870410313	0.3841760196103828
MA(4)	-0.07394037635414821	0.1858564372478969	-0.3978359719417516	0.6967512681648265
MA(8)	-0.2795817257592794	0.2716593100934508	-1.029163055972951	0.3208564539230987
MA(9)	0.07547670561898145	0.2291571834633819	0.3293665268452831	0.7467544973419736
MA(10)	-0.751443500342628	0.1638699652117488	-4.5856084693228	0.0004239199815789558
MA(11)	0.4445429747690641	0.3591100637960734	1.237901745414478	0.2361110616686708
MA(12)	0.418387381540578	0.2836378559074345	1.475075956282504	0.1623244425028538
				
R-squared	0.7461266664269699	    Mean dependent var		-296.7388625862064
Adjusted R-squared	0.4922533328539399	    S.D. dependent var		5860.105173174856
S.E. of regression	4175.696746690447	    Akaike info criterion		19.81819434225076
Sum squared resid	244110206.4844966	    Schwarz criterion		20.52541632327824
Log likelihood	-272.3638179626359	    Hannan-Quinn criter.		20.03968744354025
F-statistic	2.938972187137318	    Durbin-Watson stat		2.22774360866717
Prob(F-statistic)	0.02637520109075338			
				
Inverted AR Roots	      .95	     .87-.48i	   .87+.48i	 .50-.86i
	 .50+.86i	     .06+.95i	   .06-.95i	-.43+.84i
	-.43-.84i	    -.78-.47i	  -.78+.47i	     -.90
Inverted MA Roots	 .96-.06i	     .96+.06i	   .77+.63i	 .77-.63i
	 .26-.96i	     .26+.96i	  -.28+.95i	-.28-.95i
	     -.49	    -.76+.63i	  -.76-.63i	     -.97
				
```

Is there any way to fix it or any workaround for this error?

Thanks in advance.

**Comment by pradyut23** [comment]
> Hi folks,
> I was having the same error,
> 
> Erroneous code:
> mod = sm.tsa.SARIMAX(y, order=(0 1,0), seasonal_order=(1,0,0,12))
> res = mod.fit()
> 
> This gave me error :
> LinAlgError: Schur decomposition solver error
> 
> I was able to solve this error after doing some modification in code:
> mod = sm.tsa.SARIMAX(y, order=(0 1,0), seasonal_order=(1,0,0,12),enforce_stationarity=False)
> res = mod.fit()
> 
> Hope this helps..🙂

This fixed the error, but what was the problem that was fixed by adding _'enforce_stationarity=False'_?
What did this parameter do differently?

**Comment by stripedpumpkin** [comment]
@ChadFulton Using statsmodels==0.12.0, scipy==1.5.2 and numpy==1.19.1 on two different machines, both on Ubuntu 18.04.5, the following script raises (an LU decomposition error) in one case and is being solved in the other:
```python
import numpy as np
from statsmodels.tsa.arima.model import ARIMA

data = np.linspace(0, 2 * np.pi, 1000)
res = ARIMA(endog=data, order=(15, 0, 0)).fit()
res.summary()
```

The result, on the machine that solves it, is:
```bash
                               SARIMAX Results                                
==============================================================================
Dep. Variable:                      y   No. Observations:                 1000
Model:                ARIMA(15, 0, 0)   Log Likelihood                7014.970
Date:                Tue, 23 Mar 2021   AIC                         -13995.940
Time:                        09:30:36   BIC                         -13912.508
Sample:                             0   HQIC                        -13964.230
                               - 1000                                         
Covariance Type:                  opg                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.1416      0.000   2.08e+04      0.000       3.141       3.142
ar.L1         -6.0715      0.001  -5296.783      0.000      -6.074      -6.069
ar.L2        -17.2462      0.002  -9519.194      0.000     -17.250     -17.243
ar.L3        -29.0517      0.001  -3.86e+04      0.000     -29.053     -29.050
ar.L4        -28.2015      0.002  -1.56e+04      0.000     -28.205     -28.198
ar.L5         -5.2284      0.001  -8335.077      0.000      -5.230      -5.227
ar.L6         31.8979      0.002   1.84e+04      0.000      31.895      31.901
ar.L7         59.3725      0.000   1.38e+05      0.000      59.372      59.373
ar.L8         56.9406      0.001   1.06e+05      0.000      56.940      56.942
ar.L9         26.5174      0.001   4.44e+04      0.000      26.516      26.519
ar.L10        -9.6627      0.000  -3.15e+04      0.000      -9.663      -9.662
ar.L11       -29.3404      0.000   -6.8e+04      0.000     -29.341     -29.340
ar.L12       -27.6095      0.002  -1.32e+04      0.000     -27.614     -27.605
ar.L13       -15.4022      0.001  -1.82e+04      0.000     -15.404     -15.401
ar.L14        -5.1188      0.002  -2409.615      0.000      -5.123      -5.115
ar.L15        -0.7954   8.23e-05  -9661.256      0.000      -0.796      -0.795
sigma2      4.724e-08   4.45e-09     10.622      0.000    3.85e-08     5.6e-08
===================================================================================
Ljung-Box (L1) (Q):                 849.71   Jarque-Bera (JB):            689014.32
Prob(Q):                              0.00   Prob(JB):                         0.00
Heteroskedasticity (H):               0.16   Skew:                             9.20
Prob(H) (two-sided):                  0.00   Kurtosis:                       130.27
===================================================================================
Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
[2] Covariance matrix is singular or near-singular, with condition number 8.95e+17. Standard errors may be unstable.
```

Given your previous comments, I went ahead and tried the following script on both machines:
```python
import numpy as np
from numpy.linalg import LinAlgError
import statsmodels.api as sm
from scipy.linalg import solve_discrete_lyapunov


print('Debub script')
print('')

print('solve_discrete_lyapunov with 1 - 6e-17')
print(solve_discrete_lyapunov([[1 - 6e-17]], [[1.]]))

try:
    print('')
    print('solve_discrete_lyapunov with 1 - 5e-17')
    print(solve_discrete_lyapunov([[1 - 5e-17]], [[1.]]))
except LinAlgError as exc:
    print(str(exc))


mod = sm.tsa.SARIMAX(np.zeros(10))
try:
    print('')
    print('first sarimax')
    res = mod.filter([1, 1.])
    print(res.filter_results.initial_state_cov)
except LinAlgError as exc:
    print(str(exc))


mod = sm.tsa.SARIMAX(np.zeros(10), order=(2, 0, 0))

try:
    print('')
    print('second sarimax with order=(2, 0, 0)')
    res = mod.filter([1, 2., 1.])
    print(res.filter_results.initial_state_cov)
except LinAlgError as exc:
    print(str(exc))

print('')
print('Done with debug script.')
print('')
```

And both machines give the same output:

```bash
Debub script

solve_discrete_lyapunov with 1 - 6e-17
[[4.50359963e+15]]

solve_discrete_lyapunov with 1 - 5e-17
Matrix is singular.

first sarimax
[[-4.98960077e+291]]

second sarimax with order=(2, 0, 0)
LU decomposition error.

Done with debug script.
```

So I am assuming this has to do with `np.linspace(0, 2 * np.pi, 1000)` differing to some extent. On inspection they look identical on both machines (could their machine representation might be different?).

I can live with the LU decomposition error, but I am wondering if there is a way to reproduce that behavior consistently.

**Comment by saranachu** [comment]
> Thanks for the bug report!
> 
> This must have something to do with a bad value getting into one of the arrays being decomposed. I can't replicate any LU decomposition error on my machine, can you try the following and see what you get:
> 
> ```python
> from scipy import linalg
> print(linalg.lapack.dgetrf([np.nan]))
> print(linalg.lapack.dgetrf([np.inf]))
> ``` if its an bug how can i solve this error as my sarima and walk forwardation  is giving this error please guide me on this.

**Comment by karaage-kkkris** [comment]
> 
`'enforce_stationarity=False` did help with the error. But it may lower the precise of the training model. Is there any other way to fix the error - `LinAlgError: Schur decomposition solver error.`?

**Comment by karaage-kkkris** [comment]
> Hi folks, I was having the same error,
> 
> Erroneous code: mod = sm.tsa.SARIMAX(y, order=(0 1,0), seasonal_order=(1,0,0,12)) res = mod.fit()
> 
> This gave me error : LinAlgError: Schur decomposition solver error
> 
> I was able to solve this error after doing some modification in code: mod = sm.tsa.SARIMAX(y, order=(0 1,0), seasonal_order=(1,0,0,12),enforce_stationarity=False) res = mod.fit()
> 
> Hope this helps..🙂

'enforce_stationarity=False did help with the error. But it may lower the precise of the training model. Is there any other way to fix the error - LinAlgError: Schur decomposition solver error.?

**Comment by supercode-r** [comment]
My solution for this error, was to manually check if the last value is 0 or not. I noticed that if last value of time series was 0, it would give me LU decomposition error. Therefore, I changed the last value to the date when the value is not 0 and the error was gone. 
![output](https://user-images.githubusercontent.com/25903584/186006677-306d1bb5-8194-4dda-a002-63098ee29ef8.png) It gave me error for this, note the last value was 0.

![altered](https://user-images.githubusercontent.com/25903584/186006924-2f468b84-f181-4b69-841d-c7c1943c66a3.png) But it worked fine for this, when I altered the last value.
