### ISSUE TITLE
Can't to build documentation

### ISSUE THREAD

**Issue by elch10** [statsmodels/statsmodels#5464]
While I try to build document, I get many errors about syntax error of `__feature__` importing like this:
```
An error occurred while executing the following cell:
------------------
%matplotlib inline

from __future__ import print_function
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
from statsmodels.sandbox.regression.predstd import wls_prediction_std

np.random.seed(9876789)
------------------

  File "cell_name", line 6
SyntaxError: from __future__ imports must occur at the beginning of the file

SyntaxError: from __future__ imports must occur at the beginning of the file (cell_name, line 6)

```
It is because the first line in cell is `matplotlib %inline`
And may be that is reason why in the end of building html I get following error:
```
/home/elch10/.local/lib/python3.6/site-packages/sphinx/application.py:402: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  RemovedInSphinx20Warning)
Initializing GitHub plugin
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://matthew-brett.github.io/pydagogue/objects.inv...
loading intersphinx inventory from https://patsy.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
[autosummary] generating autosummary for: about.rst, anova.rst, contingency_tables.rst, contrasts.rst, datasets/dataset_proposal.rst, datasets/generated/anes96.rst, datasets/generated/cancer.rst, datasets/generated/ccard.rst, datasets/generated/china_smoking.rst, datasets/generated/co2.rst, ..., release/version0.8.rst, release/version0.9.rst, rlm.rst, rlm_techn1.rst, sandbox.rst, statespace.rst, stats.rst, tools.rst, tsa.rst, vector_ar.rst
WARNING: [autosummary] failed to import 'statsmodels.tsa.innovations.arma_loglike': no module named statsmodels.tsa.innovations.arma_loglike
WARNING: [autosummary] failed to import 'statsmodels.tsa.innovations.arma_loglikeobs': no module named statsmodels.tsa.innovations.arma_loglikeobs
WARNING: [autosummary] failed to import 'statsmodels.tsa.innovations.arma_score': no module named statsmodels.tsa.innovations.arma_score
WARNING: [autosummary] failed to import 'statsmodels.tsa.innovations.arma_scoreobs': no module named statsmodels.tsa.innovations.arma_scoreobs
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3639 source files that are out of date
updating environment: 3639 added, 0 changed, 0 removed
reading sources... [  0%] contrasts                                                                                                                                      
Exception occurred:
  File "/home/elch10/.local/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py", line 1018, in run
    raise RuntimeError(message)
RuntimeError: Code input with no code at /home/elch10/statsmodels/docs/source/contrasts.rst, line 54
The full traceback has been saved in /tmp/sphinx-err-1f5rveg1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:43: recipe for target 'html' failed
make: *** [html] Error 2
```
And content of file /tmp/sphinx-err-1f5rveg1.log is:
```
# Sphinx version: 1.8.1
# Python version: 3.6.7 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   3639 added, 0 changed, 0 removed
#   
#   reading sources... [  0%] about
#   
#   reading sources... [  0%] anova
#   
#   reading sources... [  0%] contingency_tables
#   
#   reading sources... [  0%] contrasts
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.1) from /home/elch10/.local/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /home/elch10/.local/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.8.1) from /home/elch10/.local/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (1.8.1) from /home/elch10/.local/lib/python3.6/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (1.8.1) from /home/elch10/.local/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (1.8.1) from /home/elch10/.local/lib/python3.6/site-packages/sphinx/ext/todo.py
#   sphinx.ext.viewcode (1.8.1) from /home/elch10/.local/lib/python3.6/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.autosummary (1.8.1) from /home/elch10/.local/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.graphviz (1.8.1) from /home/elch10/.local/lib/python3.6/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.inheritance_diagram (1.8.1) from /home/elch10/.local/lib/python3.6/site-packages/sphinx/ext/inheritance_diagram.py
#   matplotlib.sphinxext.plot_directive (unknown version) from /home/elch10/.local/lib/python3.6/site-packages/matplotlib/sphinxext/plot_directive.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /home/elch10/.local/lib/python3.6/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   IPython.sphinxext.ipython_directive (unknown version) from /home/elch10/.local/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py
#   github (unknown version) from /home/elch10/statsmodels/docs/sphinxext/github.py
#   sphinx.ext.napoleon (1.8.1) from /home/elch10/.local/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py
Traceback (most recent call last):
  File "/home/elch10/.local/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/elch10/.local/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/elch10/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/elch10/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/elch10/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/elch10/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/elch10/.local/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/elch10/.local/lib/python3.6/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/elch10/.local/lib/python3.6/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/elch10/.local/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/elch10/.local/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py", line 1018, in run
    raise RuntimeError(message)
RuntimeError: Code input with no code at /home/elch10/statsmodels/docs/source/contrasts.rst, line 54
```

```
$ git clone https://github.com/statsmodels/statsmodels.git
$ cd statsmodels
$ pip install -r requirements.txt
$ cd docs
$ make html
```

**Environment info**
- OS: `Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Python version: 3.6.7
- Sphinx version: 1.8.1

**Comment by kbhutani0001** [comment]
I got some errors too. Some of them were due to pandas_reader which was initially not installed on my system and it wasn't mentioned in the requirements.txt either.

**Comment by josef-pkt** [comment]
@thequackdaddy  This sounds like something that you looked into.

possibly a problem with ipython version
https://github.com/statsmodels/statsmodels/pull/5322#issuecomment-451102294

**Comment by thequackdaddy** [comment]
Yes. Pin `ipython<7.0` and you should be set.
