### ISSUE TITLE
statsmodels 0.9.0 and scipy incompatibility

### ISSUE THREAD

**Issue by avieor** [statsmodels/statsmodels#5782]
Running my python code containing the following imports:

```python
import scipy
import statsmodels.api as sm
from statsmodels.tsa.ar_model import AR
from sklearn.metrics import mean_squared_error
from statsmodels.tsa.stattools import adfuller
```
yields the following error messages:

```
Traceback (most recent call last):
  File "arima.py", line 7, in <module>
    import statsmodels.api as sm
  File "/usr/local/lib/python3.7/dist-packages/statsmodels/api.py", line 16, in <module>
    from .discrete.discrete_model import (Poisson, Logit, Probit,
  File "/usr/local/lib/python3.7/dist-packages/statsmodels/discrete/discrete_model.py", line 45, in <module>
    from statsmodels.distributions import genpoisson_p
  File "/usr/local/lib/python3.7/dist-packages/statsmodels/distributions/__init__.py", line 2, in <module>
    from .edgeworth import ExpandedNormal
  File "/usr/local/lib/python3.7/dist-packages/statsmodels/distributions/edgeworth.py", line 7, in <module>
    from scipy.misc import factorial
ImportError: cannot import name 'factorial' from 'scipy.misc' (/usr/local/lib/python3.7/dist-packages/scipy/misc/__init__.py)
```
These are the software versions I am running:

```
avieor@xps9343:~$ p3 work/pandas-demos/arima.py
Python 3.7.3 (default, Mar 26 2019, 01:59:45) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import statsmodels
>>> statsmodels.version.full_version
'0.9.0'
>>> import scipy
>>> scipy.__version__
'1.3.0'
>>> 
```
And here is my neofetch:
```
avieor@xps9343:~$ neofetch
            .-/+oossssoo+/-.               avieor@xps9343 
        `:+ssssssssssssssssss+:`           -------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 16.04.6 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: XPS 13 9343 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.15.0-50-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hour, 20 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2229 (dpkg) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.3.48 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 3200x1800 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Unity 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Compiz 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Ambiance 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Ambiance [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: ubuntu-mono-dark [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-5500U (4) @ 3.000GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel HD Graphics 5500 
      -+sssssssssssssssssyyyssss+-         Memory: 2447MiB / 7511MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
```

**Comment by bashtage** [comment]
See #5759
