### ISSUE TITLE
Q: Logit model with cov_type = "cluster"

### ISSUE THREAD

**Issue by emilmirzayev** [statsmodels/statsmodels#6287]
#### Describe the bug

This is more of a question and a possible bug. When I try to run:

```python
m = sm.Logit(y, X).fit(cov_type = "cluster", groups = groups)
Optimization terminated successfully.
         Current function value: 0.064115
         Iterations 9
Traceback (most recent call last):

  File "<ipython-input-15-2414b74c0cf0>", line 1, in <module>
    m = sm.Logit(y, X).fit(cov_type = "cluster", groups = groups)

  File "C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 1902, in fit
    disp=disp, callback=callback, **kwargs)

  File "C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 217, in fit
    disp=disp, callback=callback, **kwargs)

  File "C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\statsmodels\base\model.py", line 503, in fit
    mlefit = LikelihoodModelResults(self, xopt, Hinv, scale=1., **kwds)

  File "C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\statsmodels\base\model.py", line 1247, in __init__
    use_t=use_t, **cov_kwds)

  File "C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\statsmodels\base\covtype.py", line 256, in get_robustcov_results
    groups = kwds['groups']

KeyError: 'groups'
```
My groups variable is just the column that I want my errors clustered on. in this case, for every unique ID group that I have. Instead, I get this error that there is no group keyword. Am I doing something wrong here?
Even more interesting it for some reason converges and then error pops up
sm version is **0.10.1**

**Comment by josef-pkt** [comment]
API is different, those kwds need to be combined in a dict
`m = sm.Logit(y, X).fit(cov_type = "cluster", cov_kwds(dict(groups = groups))`

**Comment by bashtage** [comment]
Use GLM with the Logit link, set cov_type and pass cov_kwargs (a dict).  I
don't think Logit supports alternative covariance estimators.

>

**Comment by josef-pkt** [comment]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/tests/test_sandwich_cov.py#L465
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/tests/test_sandwich_cov.py#L182
I don't remember where the docs are, unit tests show what currently works

**Comment by emilmirzayev** [comment]
Thanks for quick reply!

Maybe we add this in the docs? about passing dictionary with the arguments as keys and also some example of keys ?

**Comment by bashtage** [comment]
That would be helpful. I read the docstring and then followed the fit function up a few levels and never detected that cov_type and cov_kwargs were important arguments that are used in Logit to change the covariance type.

**Comment by emilmirzayev** [comment]
Also, I did not detect any checks made which could force a user to use those arguments. Because error was kinda not much informative.
I will come up with PR on this weekend.
Where can I find all dict keys that can be used ?
