### ISSUE TITLE
TypeError when getting conf_int

### ISSUE THREAD

**Issue by alexsmartens** [statsmodels/statsmodels#6296]
#### Describe the bug
The following type error occurs when `conf_int` called on `pd.Series` with `MultiIndex`:
```
Traceback (most recent call last):
  File "/home/user/Projects/subfolder/my_project/test1.py", line 42, in <module>
    pred_ci = pred_res.conf_int(alpha=0.01)
  File "/home/user/Programs/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 3707, in conf_int
    names = (['lower %s' % name for name in ynames] +
  File "/home/user/Programs/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 3707, in <listcomp>
    names = (['lower %s' % name for name in ynames] +
TypeError: not all arguments converted during string formatting
```

#### Code Sample, a copy-pastable example if possible
data: [my_data_sample1.csv](https://drive.google.com/file/d/1bQhM9fLiE8UaE-I9Kys0HjH__UiEA9DW/view?usp=sharing)

```python
df = pd.read_csv("my_data_sample1.csv", header=[0, 1], index_col=0, parse_dates=True)
df = df.iloc[:500, :]

endog = df[("Sens", "1b")]

mod = sm.tsa.SARIMAX(endog, order=(1, 0, 0), trend='c')
res = mod.fit(disp=False)

pred_res = res.get_prediction(start=0, end=len(endog), full_results=True)
pred_means = pred_res.predicted_mean
pred_ci = pred_res.conf_int(alpha=0.01)
```

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

No `TypeError`

#### Output of ``import statsmodels.api as sm; sm.show_versions()``
`
0.11.0dev0+592.gd4593c7c1`

**Comment by bashtage** [comment]
Workaround is to not use a multiindex.

**Comment by alexsmartens** [comment]
Yeah, I've figured it the hard way. A multiindex dataframe column also works fine as a workaround
