### ISSUE TITLE
Fit ARIMA Error: exog contains inf or nans 

### ISSUE THREAD

**Issue by alexsmartens** [statsmodels/statsmodels#6540]
#### Describe the bug

I am getting `statsmodels.tools.sm_exceptions.MissingDataError: exog contains inf or nans` with `d=0`. This does not happen when say `d=1`.

Error log:
```
/my_path/test.py
/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/tsa/innovations/arma_innovations.py:83: RuntimeWarning: invalid value encountered in sqrt
  v05 = v**0.5
Traceback (most recent call last):
  File "/my_path/test.py", line 19, in <module>
    cov_type="none")
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/tsa/arima/model.py", line 307, in fit
    **gls_kwargs)
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/tsa/arima/estimators/gls.py", line 251, in gls
    mod_gls = OLS(u, x)
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/regression/linear_model.py", line 858, in __init__
    hasconst=hasconst, **kwargs)
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/regression/linear_model.py", line 701, in __init__
    weights=weights, hasconst=hasconst, **kwargs)
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/regression/linear_model.py", line 189, in __init__
    super(RegressionModel, self).__init__(endog, exog, **kwargs)
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/base/model.py", line 236, in __init__
    super(LikelihoodModel, self).__init__(endog, exog, **kwargs)
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/base/model.py", line 77, in __init__
    **kwargs)
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/base/model.py", line 100, in _handle_data
    data = handle_data(endog, exog, missing, hasconst, **kwargs)
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/base/data.py", line 667, in handle_data
    **kwargs)
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/base/data.py", line 83, in __init__
    self._handle_constant(hasconst)
  File "/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels/base/data.py", line 129, in _handle_constant
    raise MissingDataError('exog contains inf or nans')
statsmodels.tools.sm_exceptions.MissingDataError: exog contains inf or nans
```

#### Code Sample, a copy-pastable example if possible

```python
endog = pd.read_csv("my_data_sample2.csv", index_col=0, parse_dates=True)
endog = endog.asfreq(pd.infer_freq(endog.index))

mod = sm.tsa.arima.ARIMA(
                endog,
                order=(18, 0, 39),
                enforce_stationarity=False,
                enforce_invertibility=False,
            )
res = mod.fit(
                method="hannan_rissanen",
                low_memory=True,
                cov_type="none")
```

[Edit] link to my data sample: [my_data_sample2.csv](https://drive.google.com/file/d/185CkaiFpeKsy978PnawqoclwVS3tIOzQ/view?usp=sharing)

#### Expected Output

No `exog contains inf or nans` error

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

```
INSTALLED VERSIONS
------------------
Python: 3.7.4.final.0
OS: Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8

statsmodels
===========

Installed: 0.11.0dev0+628.g17f7c3481 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.13 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/Cython)
numpy: 1.17.0 (/my_path3/.local/lib/python3.7/site-packages/numpy)
scipy: 1.3.1 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/scipy)
pandas: 0.25.3 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.1 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.1.1 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/matplotlib)
    backend: Qt5Agg 
cvxopt: Not installed
joblib: 0.14.0 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.9.0 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/IPython)
    jinja2: 2.10.3 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.4.2 (/my_path2/anaconda3/envs/vision/lib/python3.7/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed
```

**Comment by ChadFulton** [comment]
Thanks for the report!

**Comment by ChadFulton** [comment]
Thanks again. This is a bug.

By default, `sm.tsa.arima.ARIMA` includes a constant for stationary models (`d=0`) but does not include a constant for integrated models (`d=1`).

When there is a constant (or some other regression effect) and you're not using `method='statespace'`, then GLS with ARMA errors is used. However, it can't handle ARIMA errors, and it is possible with the Hannan-Rissanen method that we get estimates that imply a non-stationary (i.e. ARIMA) process.

So I think what we need to do is check for parameters for stationarity in GLS and raise an exception if that's not satisfied.

**Comment by alexsmartens** [comment]
Just wanted to add a bit of context to this situation:
when I run `arima` I am seeing the following warning ```/my_path/envs/conda-default/lib/python3.7/site-packages/statsmodels/tsa/arima/model.py:340: UserWarning: Provided `endog` series has been differenced to eliminate integration prior to parameter estimation by method "hannan_rissanen".' estimation by method "%s".' % method)```.
Because I run grid search with multiprocessing, I decided to differentiate the data myself. Isn't that what `arima`  does under the hood?

Also, here is an example where I do differentiate the data myself but still get the same error:
```
endog = pd.read_csv("my_data_sample2.csv", index_col=0, parse_dates=True)
endog = endog.asfreq(pd.infer_freq(endog.index))
endog = endog.diff().dropna()

mod = sm.tsa.arima.ARIMA(
    endog,
    order=(2, 0, 2),
    enforce_stationarity=False,
    enforce_invertibility=False,
)
res = mod.fit(
    method="hannan_rissanen",
    low_memory=True,
    cov_type="none")
```

**Comment by ChadFulton** [comment]
The issue is that the parameter estimates for the *differenced* data are coming up as non-stationary. That's why differencing the data yourself doesn't improve things have an effect.

**Comment by saraswathykrk** [comment]
Any update on this. How do we use this if we encounter the issue again?
