### ISSUE TITLE
ImportError: cannot import name 'assert_equal' from 'statsmodels.compat.pandas'

### ISSUE THREAD

**Issue by lucassbroto** [statsmodels/statsmodels#6786]
Hello,

I am facing a very simple problem importing the library, my system cannot import 'assert_equal'

All my other libraries are up to date, since I saw this was a common problem in other issues. What should I do?

This is the error I get:

FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  data_klasses = (pandas.Series, pandas.DataFrame, pandas.Panel)
Traceback (most recent call last):
  File "C:/Users/lucas/PycharmProjects/Radar_acconeer/forecasting.py", line 4, in <module>
    import statsmodels.api as sm
  File "C:\Users\lucas\PycharmProjects\Radar_acconeer\venv\lib\site-packages\statsmodels\__init__.py", line 2, in <module>
    from .compat import PY3
  File "C:\Users\lucas\PycharmProjects\Radar_acconeer\venv\lib\site-packages\statsmodels\compat\__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "C:\Users\lucas\PycharmProjects\Radar_acconeer\venv\lib\site-packages\statsmodels\tools\__init__.py", line 2, in <module>
    from statsmodels.tools._testing import PytestTester
  File "C:\Users\lucas\PycharmProjects\Radar_acconeer\venv\lib\site-packages\statsmodels\tools\_testing.py", line 11, in <module>
    from statsmodels.compat.pandas import assert_equal
ImportError: cannot import name 'assert_equal' from 'statsmodels.compat.pandas'

**Comment by bashtage** [comment]
Try running 

pip uninstall statsmodels -y

until it tells you statsmodel sis not installed, then pip install statsmodels.

**Comment by lucassbroto** [comment]
hi, thanks for your answer,

I have tried doing so, but still, the problem persists.

**Comment by bashtage** [comment]
Which version of statsmodels do you have installed?  What if you pip install statsmodels==0.11.1 ?  Which platform?

**Comment by lucassbroto** [comment]
Yes, I have checked and it is the 0.11.1 version. 

I have tried through pycharm package installing and through pip. I have a windows  10, 64 bit

**Comment by bashtage** [comment]
What python are you using?  

Have you tried Anaconda?

**Comment by lucassbroto** [comment]
My python version is 3.6. I haven't tried anaconda yet, I'll set up the environment and try again

**Comment by bashtage** [comment]
This isn't a statsmodel bug. Some users seem to have similar configuration errors.
