### ISSUE TITLE
numpy.linalg.LinAlgError: 14-th leading minor of the array is not positive definite

### ISSUE THREAD

**Issue by Chethan-Babu-stack** [statsmodels/statsmodels#7232]
Traceback (most recent call last):
  File "/home/chve882b/VAR_baseline.py", line 82, in <module>
    results = model.fit(maxlags = 1, ic = 'aic') # maxlags = 15, ic = 'aic'
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.7/site-packages/statsmodels/tsa/vector_ar/var_model.py", line 621, in fit    selections = self.select_order(maxlags=maxlags)
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.7/site-packages/statsmodels/tsa/vector_ar/var_model.py", line 768, in select_order
    for k, v in result.info_criteria.items():
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.7/site-packages/statsmodels/base/wrapper.py", line 34, in __getattribute__
    obj = getattr(results, attr)
  File "pandas/_libs/properties.pyx", line 33, in pandas._libs.properties.CachedProperty.__get__
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.7/site-packages/statsmodels/tsa/vector_ar/var_model.py", line 2117, in info_criteria
    ld = logdet_symm(self.sigma_u_mle)
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.7/site-packages/statsmodels/tools/linalg.py", line 28, in logdet_symm
    c, _ = linalg.cho_factor(m, lower=True)
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 153, in cho_factor    check_finite=check_finite)
  File "/home/chve882b/chethan-kernel/my-kernel/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 38, in _cholesky
    "definite" % info)

**Comment by bashtage** [comment]
What code are you running?  The TB by itself is not useful.

**Comment by Chethan-Babu-stack** [comment]
VAR with 100 features, maxlags = 1. The training dataset has 490 records.

**Comment by bashtage** [comment]
The regressor latrix which consists of the first lag of each variable is numerically singular.  This is telling you that a 100 dimensional VAR is a bad idea.

**Comment by bashtage** [comment]
Fitting high dimensional VARs is not a goal of statsmodels at the present.  Some other approach such as a ridge penalty might help you.  I don't think there is anything that we can do here.
