### ISSUE TITLE
wrong matrix dimensions:can't do fit_regularized with multivariate endogenous and exogenous variables

### ISSUE THREAD

**Issue by moonj94** [statsmodels/statsmodels#7269]
#### Describe the bug

I want to do regularized multivariate regression with sqrt_lasso. the endogenous variable dy is of shape 128x64 and exogenous variable x is of shape 128x64 also. When I try running this, I get the following error:

```
Traceback (most recent call last):

  File "/Users/jaemoon/Desktop/python/my_eegnet/pyregress_st_backup", line 357, in <module>
    est=sm.GLS(dy,x).fit_regularized(method='sqrt_lasso')

  File "/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/statsmodels/regression/linear_model.py", line 630, in fit_regularized
    refit=refit, **kwargs)

  File "/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/statsmodels/regression/linear_model.py", line 1053, in fit_regularized
    params = self._sqrt_lasso(alpha, refit, defaults["zero_tol"])

  File "/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/statsmodels/regression/linear_model.py", line 1098, in _sqrt_lasso
    h1[1:, 0] = cvxopt.matrix(self.endog, (n, 1))

TypeError: wrong matrix dimensions
```
#### Code Sample, a copy-pastable example if possible
            `est=sm.GLS(dy,x).fit_regularized(method='sqrt_lasso')`

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
Python: 3.7.7.final.0
OS: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: en_CA.UTF-8
LANG: en_CA.UTF-8

statsmodels
===========

Installed: 0.12.1 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.19.2 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/numpy)
scipy: 1.6.0 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/scipy)
pandas: 1.2.0 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.1 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.3.2 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: 1.2.0 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/cvxopt)
joblib: 1.0.0 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.18.1 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/IPython)
    jinja2: 2.11.2 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/jinja2)
sphinx: 3.2.1 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/sphinx)
    pygments: 2.7.4 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed
</details>

**Comment by kshedden** [comment]
I don't think it was ever intended that most of the regression methods would work with a multidimensional response.  In pariticular, when using more advanced fitting methods like sqrt_lasso it almost certainly won't work (and if it does appear to work, I would be skeptical of the results).

In general, for fitting purposes, multivariate regression with a d-dimensional outcome gives the same fitted values and predictions as doing d separate univariate regressions.  I believe we do have multivariate LS and canonical correlation which is one place where there really is something gained by doing all the regressions together (in multivariate LS the inferences are different, and in canonical correlation the goal is different).
