### ISSUE TITLE
LU decomposition error when predicting time series

### ISSUE THREAD

**Issue by antoinecomp** [statsmodels/statsmodels#7290]
#### Describe the bug

I would like to predict the next element of the series `[2697. 1198. 599. 2997. 1199.]`.

#### Code Sample

I tried:

```python
    import statsmodels.tsa.arima.model as smt
    import pandas as pd

    print(statsmodels.__version__)
    ts = pd.DataFrame([2697. 1198.  599. 2997. 1199.])
    print(ts.values)
    if ts.values != [] or len(ts.values) > 2:
        best_aic = np.inf
        best_order = None
        best_model = None

        ranges = range(1, 5)
        for difference in ranges:
            # try:
            tmp_model = smt.ARIMA(ts.values, order=(list(ranges), difference, list(ranges)), trend='n').fit()
            tmp_aic = tmp_model.aic
            if tmp_aic < best_aic:
                best_aic = tmp_aic
                best_difference = difference
                best_model = tmp_model
                # except Exception as e:
                #     print(e)
                #     continue
        if best_model is not None:
            y_hat = best_model.forecast()[0]
            if y_hat < 0:
                y_hat = 0
        else:
            y_hat = 0
    else:
        y_hat = 0
    print("predicted:", y_hat)
```

But it returns:

```
    0.12.1
    [2697. 1198.  599. 2997. 1199.]
    C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\base\model.py:568: ConvergenceWarning: Maximum Likelihood op
    timization failed to converge. Check mle_retvals
      ConvergenceWarning)
    Traceback (most recent call last):
      File "main.py", line 38, in <module>
        tmp_model = smt.ARIMA(ts.values, order=(list(ranges), difference, list(ranges)), trend='n').fit()
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\tsa\arima\model.py", line 345, in fit
        cov_type=cov_type, cov_kwds=cov_kwds, **method_kwargs)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 695, in fit
        skip_hessian=True, **kwargs)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\base\model.py", line 527, in fit
        full_output=full_output)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\base\optimizer.py", line 227, in _fit
        hess=hessian)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\base\optimizer.py", line 632, in _fit_lbfgs
        **extra_kwargs)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\scipy\optimize\lbfgsb.py", line 198, in fmin_l_bfgs_b
        **opts)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\scipy\optimize\lbfgsb.py", line 360, in _minimize_lbfgsb
        f, g = func_and_grad(x)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 200, in fun_a
    nd_grad
        self._update_fun()
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 166, in _upda
    te_fun
        self._update_fun_impl()
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 73, in update
    _fun
        self.f = fun_wrapped(self.x)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 70, in fun_wr
    apped
        return fun(x, *args)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\base\model.py", line 501, in f
        return -self.loglike(params, *args) / nobs
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 925, in loglike
        loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py", line 983, in logli
    ke
        kfilter = self._filter(**kwargs)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py", line 903, in _filt
    er
        self._initialize_state(prefix=prefix, complex_step=complex_step)
      File "C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels\tsa\statespace\representation.py", line 986, in _ini
    tialize_state
        complex_step=complex_step)
      File "statsmodels\tsa\statespace\_representation.pyx", line 1373, in statsmodels.tsa.statespace._representation.dStatespace.initialize
      File "statsmodels\tsa\statespace\_representation.pyx", line 1362, in statsmodels.tsa.statespace._representation.dStatespace.initialize
      File "statsmodels\tsa\statespace\_initialization.pyx", line 288, in statsmodels.tsa.statespace._initialization.dInitialization.initialize
      File "statsmodels\tsa\statespace\_initialization.pyx", line 406, in statsmodels.tsa.statespace._initialization.dInitialization.initialize_stationary_stationary_cov
    
      File "statsmodels\tsa\statespace\_tools.pyx", line 1206, in statsmodels.tsa.statespace._tools._dsolve_discrete_lyapunov
    numpy.linalg.LinAlgError: LU decomposition error.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

I was expecting a normal number.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

>>> import statsmodels.api as sm; sm.show_versions()

INSTALLED VERSIONS
------------------
Python: 3.6.7.final.0

statsmodels
===========

Installed: 0.12.1 (C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.19.5 (C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\numpy)
scipy: 1.5.4 (C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\scipy)
pandas: 1.1.5 (C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\pandas)
    dateutil: 2.8.1 (C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales\venv\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: Not installed
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: Not installed
    jinja2: Not installed
sphinx: Not installed
    pygments: Not installed
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
You are asking the impossible.  You have only 5 data points are you are trying to estimate an ARIMA(4,4,4).

**Comment by antoinecomp** [comment]
@bashtage  I am up for anything. I first tried with ARMA with the deprecated model. It's just to try predict from very simple trends.

**Comment by bashtage** [comment]
Try simple models, like a pure time trend => order(0,1,0), trend="t"

**Comment by ChadFulton** [comment]
Going to close this as answered.
