### ISSUE TITLE
summary_params requires result instance params

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#741]
summary_params is written that it can take a tuple instead of a result instance

However, `_getnames` accesses params directly

```
>>> summary_params((tt, tt.effect, tt.sd, tt.tvalue, tt.pvalue, np.ones((2,5))))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-josef_new\statsmodels\iolib\summary.py", line 464, in summary_params
    _, xname = _getnames(results, yname=yname, xname=xname)
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-josef_new\statsmodels\iolib\summary.py", line 272, in _getnames
    xname = ['var_%d' % i for i in range(len(self.params))]
AttributeError: 'ContrastResults' object has no attribute 'params'
```

I'm trying to get summary_params to work with t_test results

**Comment by josef-pkt** [comment]
I guess I fixed this a long time ago.
t_test uses summary_params and I used it again in a current PR

closing
