### ISSUE TITLE
UnboundLocalError: local variable 'warnings' referenced before assignment

### ISSUE THREAD

**Issue by aliyurtsevenn** [statsmodels/statsmodels#7417]
#### Describe the bug

[A clear and concise description of what the bug is. This should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Code Sample, a copy-pastable example if possible

Hi, I have installed statsmodels v0.13.0.dev0 and tried to perform ordinal logistic regression . I have encountered with the error below. 

Traceback (most recent call last):
  File "logistic.py", line 250, in <module>
    distr='logit')
  File "/home/a/statsmodels/statsmodels/miscmodels/ordinal_model.py", line 124, in __init__
    endog, labels, is_pandas = self._check_inputs(endog, exog)
  File "/home/a/statsmodels/statsmodels/miscmodels/ordinal_model.py", line 196, in _check_inputs
    warnings.warn("the endog has ordered == False, "
UnboundLocalError: local variable 'warnings' referenced before assignment

My code is below;

my_label=reversed_one["Labels"]
Attributes= reversed_one.drop(["Labels"],axis=1)

my_label=my_label.astype("category")
Attributes=Attributes.astype(float)

mod_log = OrderedModel(my_label,
                        Attributes,
                        distr='logit')
res_log = mod_log.fit(method='bfgs', disp=False)
res_log.summary()

Would you inform me about the problem. Thank you in advance! 

Best regards,

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by josef-pkt** [comment]
the endog "mylabel" should be a pandas **ordered** categorical

but it's only a warning
```
if not endog.dtype.ordered:
                    warnings.warn("the endog has ordered == False, "
                                  "risk of capturing a wrong order for the "
                                  "categories. ordered == True preferred.",
                                  Warning)
```

**Comment by aliyurtsevenn** [comment]
Hello, I couldn't understand how to solve the problem , is the problem because of my label order?

**Comment by josef-pkt** [comment]
I messed up in a cleanup commit when moving the import statement
https://github.com/statsmodels/statsmodels/commit/c1664d989c4eea864180e69b200bef687494a234#diff-90f3651f92a4d83cb51aba94427bcc256ad527efa51cb3ffaaf829ae2bd2abfb

**Comment by josef-pkt** [comment]
Pandas has an option to make Categorical variables into **ordered** categorical variables. pandas Categorical that are not ordered might have an undesired implicit ordering.
 
Because the ordering is crucial here we prefer or require ordered Categorical and not plain Categorical.

**Comment by josef-pkt** [comment]
I'm not an expert on pandas usage.

The unit tests create both ordered and not ordered categorical variables for testing
https://github.com/statsmodels/statsmodels/blob/main/statsmodels/miscmodels/tests/results/results_ordinal_model.py#L49

**Comment by aliyurtsevenn** [comment]
Thank you very much for your help, it worked but this time another error came up.

  Traceback (most recent call last):
  File "logistic.py", line 251, in <module>
    distr='logit')
  File "/home/a/statsmodels/statsmodels/miscmodels/ordinal_model.py", line 144, in __init__
    raise ValueError("there should not be a constant in the model")

I didn't actually understand from this statement. Would you give me suggestions on this problem. I really appreciate for your help.

**Comment by josef-pkt** [comment]
What's in your design matrix `attributes`?
There should not be a constant in there, neither explicit nor implicit. 
For example if you have one categorical dummy design, then you need to drop one reference category so the sum of all dummies doesn't add to one in each observation.

e.g. some explanation for the case when using formulas
https://www.statsmodels.org/dev/examples/notebooks/generated/ordinal_regression.html#Using-formulas---no-constant-in-model

**Comment by aliyurtsevenn** [comment]
When I get the columns from 0 to 20, the model runs, but the columns between 0 to more than that  doesn't work. On the other hand, when I use attributes as columns of 20 to 35 let's say, it also works. I really didn't understand about the issue. I added my data. Would you help me to show where the constant columns are and how to remove them? I appreciate for your help. 

Best regards,
[results.xlsx](https://github.com/statsmodels/statsmodels/files/6320490/results.xlsx)

**Comment by josef-pkt** [comment]
Is this all your data? only 24 observations?

The model cannot be estimated if there are more explanatory variables than observations.

**Comment by aliyurtsevenn** [comment]
I see, I appreciate for the help, I will find a way to compose my data in a different way.

**Comment by bashtage** [comment]
Fixed by commit ae8bbb86e, which restored the missing `import warnings` in statsmodels/miscmodels/ordinal_model.py. Closing as fixed.
