### ISSUE TITLE
ValueError("there should not be a constant in the model")

### ISSUE THREAD

**Issue by aliyurtsevenn** [statsmodels/statsmodels#7418]
Thank you very much for your help, it worked but this time another error came up.

  Traceback (most recent call last):
  File "logistic.py", line 251, in <module>
    distr='logit')
  File "/home/a/statsmodels/statsmodels/miscmodels/ordinal_model.py", line 144, in __init__
    raise ValueError("there should not be a constant in the model")

I didn't actually understand from this statement. Would you give me suggestions on this problem. I really appreciate for your help.

_Originally posted by @aliyurtsevenn in https://github.com/statsmodels/statsmodels/issues/7417#issuecomment-820575569_

**Comment by pranavnerurkar** [comment]
same error - how to resolve

**Comment by pranavnerurkar** [comment]
> same error - how to resolve
> I am using
> OrderedModel.from_formula('measure ~ C(factor1) + C(factor2) + C(factor1):C(factor2)', distr='logit', data=df)
> where both factor1 factor2 and measure are ordinal

https://github.com/statsmodels/statsmodels/issues/7041
this worked!!!
