### ISSUE TITLE
Install failed on MacOS 11 with python3.9, using the latest 0.12.2-cp39

### ISSUE THREAD

**Issue by FlynnMa** [statsmodels/statsmodels#7499]
#### Describe the bug

download .whl manually, I get error
```
python3 -m pip install statsmodels-0.12.2-cp39-cp39-macosx_10_15_x86_64.whl 
ERROR: statsmodels-0.12.2-cp39-cp39-macosx_10_15_x86_64.whl is not a supported wheel on this platform.
```

Following https://github.com/statsmodels/statsmodels/issues/7392
```
python3 -m pip install statsmodels --upgrade
```

I get a lot more errors:
```
 ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/pip-build-env-j7t6pspu/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.29.14' 'numpy==1.15.4; python_version=='"'"'3.6'"'"'' 'numpy==1.15.4; python_version=='"'"'3.7'"'"'' 'numpy==1.17.5; python_version>='"'"'3.8'"'"'' 'scipy>=1.2'
       cwd: None
  Complete output (144 lines):
  Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
  Collecting setuptools
    Using cached setuptools-57.0.0-py3-none-any.whl (821 kB)
  Collecting wheel
    Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting cython>=0.29.14
    Using cached Cython-0.29.23-py2.py3-none-any.whl (978 kB)
  Collecting numpy==1.17.5
    Using cached numpy-1.17.5.zip (6.4 MB)
  Collecting scipy>=1.2
    Using cached scipy-1.6.3.tar.gz (27.2 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/tmpd6jcwtmq
           cwd: /private/var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/pip-install-podgqa43/scipy
      Complete output (120 lines):
      setup.py:462: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/pip-modern-metadata-654tuyzo'), proceeding with generating Cython sources and expanding templates
        warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
      Running from SciPy source directory.
      lapack_opt_info:
      lapack_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE
  
      openblas_lapack_info:
        libraries openblas not found in ['/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE
  
      openblas_clapack_info:
        libraries openblas,lapack not found in ['/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE
  
      flame_info:
        libraries flame not found in ['/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE
  
      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in /usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib
        libraries tatlas,tatlas not found in /usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries tatlas,tatlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries tatlas,tatlas not found in /usr/lib
        libraries lapack_atlas not found in /opt/local/lib
        libraries tatlas,tatlas not found in /opt/local/lib
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE
  
      atlas_3_10_info:
        libraries lapack_atlas not found in /usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib
        libraries satlas,satlas not found in /usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries satlas,satlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries satlas,satlas not found in /usr/lib
        libraries lapack_atlas not found in /opt/local/lib
        libraries satlas,satlas not found in /opt/local/lib
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE
  
      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in /usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib
        libraries lapack_atlas not found in /opt/local/lib
        libraries ptf77blas,ptcblas,atlas not found in /opt/local/lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE
  
      atlas_info:
        libraries lapack_atlas not found in /usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib
        libraries f77blas,cblas,atlas not found in /usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib
        libraries lapack_atlas not found in /usr/local/lib
        libraries f77blas,cblas,atlas not found in /usr/local/lib
        libraries lapack_atlas not found in /usr/lib
        libraries f77blas,cblas,atlas not found in /usr/lib
        libraries lapack_atlas not found in /opt/local/lib
        libraries f77blas,cblas,atlas not found in /opt/local/lib
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE
  
      accelerate_info:
        NOT AVAILABLE
  
      lapack_info:
        libraries lapack not found in ['/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib', '/usr/local/lib', '/usr/lib', '/opt/local/lib']
        NOT AVAILABLE
  
      /private/var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/pip-build-env-s5yri0sg/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1748: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      lapack_src_info:
        NOT AVAILABLE
  
      /private/var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/pip-build-env-s5yri0sg/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1748: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
        NOT AVAILABLE
  
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/pip-build-env-s5yri0sg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/pip-build-env-s5yri0sg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/pip-build-env-s5yri0sg/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 598, in <module>
          setup_package()
        File "setup.py", line 594, in setup_package
          setup(**metadata)
        File "/private/var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/pip-build-env-s5yri0sg/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 135, in setup
          config = configuration()
        File "setup.py", line 500, in configuration
          raise NotFoundError(msg)
      numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found. Note: Accelerate is no longer supported.
      To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
      See site.cfg.example in the Scipy source directory and
      https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/tmpd6jcwtmq Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/45/m3rmv_655gb2b0zxs82fbrsm0000gn/T/pip-build-env-j7t6pspu/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.29.14' 'numpy==1.15.4; python_version=='"'"'3.6'"'"'' 'numpy==1.15.4; python_version=='"'"'3.7'"'"'' 'numpy==1.17.5; python_version>='"'"'3.8'"'"'' 'scipy>=1.2' Check the logs for full command output.
```

**Comment by akhst7** [comment]
@FlynnMa, do you have openblas installed ?  `No BLAS/LAPACK libraries found.`indicates otherwise.  I installed the latest, 
`Successfully installed patsy-0.5.1 statsmodels-0.13.0.dev0+396.gf8420a0a0`

**Comment by bashtage** [comment]
You are failing on SciPy, not statsmodels.  

If you can get NumPy, SciPy and Cython installed, then you can install statsmodels with

```
pip install statsmodels --no-build-isolation
```

to use existing installations.
