### ISSUE TITLE
Some bugs in examples

### ISSUE THREAD

**Issue by alienx-zero** [statsmodels/statsmodels#7532]
Here I try to follow the code shown in https://www.statsmodels.org/stable/examples/notebooks/generated/mixed_lm_example.html ..

```
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.tools.sm_exceptions import ConvergenceWarning

data = sm.datasets.get_rdataset('dietox', 'geepack').data
md = smf.mixedlm("Weight ~ Time", data, groups=data["Pig"])
mdf = md.fit(method=["lbfgs"])
print(mdf.summary())`
```
And then here is the report..
```
`Traceback (most recent call last):

  File "<ipython-input-93-edc918b10d01>", line 1, in <module>
    mdf = md.fit(method=["lbfgs"])

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\statsmodels\regression\mixed_linear_model.py", line 2125, in fit
    **fit_kwargs)

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\statsmodels\base\model.py", line 527, in fit
    full_output=full_output)

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\statsmodels\base\optimizer.py", line 218, in _fit
    hess=hessian)

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\statsmodels\base\optimizer.py", line 455, in _fit_lbfgs
    **extra_kwargs)

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\scipy\optimize\lbfgsb.py", line 198, in fmin_l_bfgs_b
    **opts)

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\scipy\optimize\lbfgsb.py", line 308, in _minimize_lbfgsb
    finite_diff_rel_step=finite_diff_rel_step)

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\scipy\optimize\optimize.py", line 262, in _prepare_scalar_function
    finite_diff_rel_step, bounds, epsilon=epsilon)

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 136, in __init__
    self._update_fun()

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 226, in _update_fun
    self._update_fun_impl()

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 133, in update_fun
    self.f = fun_wrapped(self.x)

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\scipy\optimize\_differentiable_functions.py", line 130, in fun_wrapped
    return fun(x, *args)

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\statsmodels\base\model.py", line 501, in f
    return -self.loglike(params, *args) / nobs

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\statsmodels\regression\mixed_linear_model.py", line 1454, in loglike
    fe_params = self.get_fe_params(cov_re, vcomp)

  File "D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\statsmodels\regression\mixed_linear_model.py", line 1289, in get_fe_params
    self.endog_li[group_ix][:, None]), axis=1)

  File "<__array_function__ internals>", line 6, in concatenate

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)`
```

**Comment by bashtage** [comment]
Works correctly here.  What version of scipy are you using?

**Comment by bashtage** [comment]
Closing since no action for us to take.  Please feel free to post with more information if you need help.

**Comment by alienx-zero** [comment]
Sorry for the late response, I am busy last week..

scipy.__version__
Out[51]: '1.6.2'

statsmodels.__version__
Out[54]: '0.12.0'

**Comment by alienx-zero** [comment]
> Closing since no action for us to take. Please feel free to post with more information if you need help.

And I track the file to this sentence D:\Users\99488\Anaconda3\envs\deep_learning\lib\site-packages\statsmodels\regression\mixed_linear_model.py", line 1289, in get_fe_params
    self.endog_li[group_ix][:, None]), axis=1)

Here,, it try to concatenate two arrays, but I print their shape..it is in different size
self.endog_li[group_ix][:, None].shape
(12, 1, 1)
self.exog_li[group_ix].shape
(12, 2)

**Comment by alienx-zero** [comment]
It is fixed by intalling python in other anaconda environment. And in the previous environment, it also works after I reinstall it
