### ISSUE TITLE
numpy with AttributeError: 'module' object has no attribute '__version__'

### ISSUE THREAD

**Issue by eternal-bug** [statsmodels/statsmodels#7948]
## The raise Error with `statsmodels/compat/numpy.py` 

I have encountered following error when I import the statsmodels package.

**My environment**

+ python 2.7
+ conda env
+ statsmodels 0.11.0

```python
>>> from statsmodels.sandbox.stats.multicomp import multipletests

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/sandbox/__init__.py", line 4, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/tools/tools.py", line 8, in <module>
    from statsmodels.compat.python import lzip, lmap
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/tools/_testing.py", line 11, in <module>
    from statsmodels.compat.pandas import assert_equal
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/compat/pandas.py", line 4, in <module>
    import numpy as np
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/compat/numpy.py", line 50, in <module>
    NP_LT_114 = LooseVersion(np.__version__) < LooseVersion('1.14')
AttributeError: 'module' object has no attribute '__version__'
```

Next, I had done according to the [ipyparallel - #349](https://github.com/ipython/ipyparallel/issues/349). But the same error occurs.

```bash
pip uninstall -y numpy
pip uninstall -y setuptools
pip install setuptools or conda install setuptools
pip install bumpy or conda install numpy
```

Then, I add the one line code at header of `/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/compat/numpy.py`.

```python
__version__ = "1.16"
```

And I load package, The error had little change. `AttributeError: 'module' object has no attribute '__version__'` 
to `AttributeError: 'module' object has no attribute 'linalg'`. This indicates that the "numpy" version check has passed.

```python
>>> from statsmodels.sandbox.stats.multicomp import multipletests

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/sandbox/__init__.py", line 4, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/tools/tools.py", line 8, in <module>
    from statsmodels.compat.python import lzip, lmap
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/tools/_testing.py", line 11, in <module>
    from statsmodels.compat.pandas import assert_equal
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/compat/pandas.py", line 4, in <module>
    import numpy as np
  File "/dssg/home/XXX/miniconda3/envs/test/lib/python2.7/site-packages/statsmodels/compat/numpy.py", line 52, in <module>
    np_matrix_rank = np.linalg.matrix_rank
AttributeError: 'module' object has no attribute 'linalg'
```

So I guessed because the `statsmodels/compat/numpy.py` have the same name with the `numpy` package, and it import itself rather than the real `numpy` package. I don't know if my guess is correct. If so, how could I solve it.

Thanks!

I search the history issue. The others had also encountered the same error with the `statsmodels/compat/numpy.py` [#427](https://github.com/ipython/ipyparallel/issues/427), but import the other function.

**Comment by bashtage** [comment]
statsmodels 0.11 doesn't support Python 2.7. You need an older version. The best advice is to use Python 3.8 or 3.9 with the most recent statsmodels.

**Comment by bashtage** [comment]
Closing since no action for us.

**Comment by eternal-bug** [comment]
I get a 0.10.2 version, and it work well. Thanks!
