### ISSUE TITLE
`pip install git+https://github.com/statsmodels/statsmodels.git` fails with `numpy is installed but older (1.14.5) than required (1.17)`

### ISSUE THREAD

**Issue by harupy** [statsmodels/statsmodels#7992]
#### Describe the bug

As the title says, `pip install git+https://github.com/statsmodels/statsmodels.git` fails with `numpy is installed but older (1.14.5) than required (1.17)`.

#### Code Sample, a copy-pastable example if possible

```bash
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.

pip install git+https://github.com/statsmodels/statsmodels.git
```

This fails with:

```
+ pip install git+https://github.com/statsmodels/statsmodels.git
Collecting git+https://github.com/statsmodels/statsmodels.git
  Cloning https://github.com/statsmodels/statsmodels.git to /tmp/pip-req-build-se1gsaxj
  Running command git clone --filter=blob:none -q https://github.com/statsmodels/statsmodels.git /tmp/pip-req-build-se1gsaxj
  Resolved https://github.com/statsmodels/statsmodels.git to commit 19db7961b3388f85b4383d81f3caa3c9e809a532
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/hostedtoolcache/Python/3.7.12/x64/bin/python /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpuzaz9kp1
       cwd: /tmp/pip-req-build-se1gsaxj
  Complete output (25 lines):
  setup.py:61: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    req_ver = LooseVersion(SETUP_REQUIREMENTS[key])
  setup.py:64: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    ver = LooseVersion(mod.__version__)
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-c2wv8145/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-c2wv8145/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-c2wv8145/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 268, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-c2wv8145/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 66, in <module>
      raise RuntimeError(REQ_NOT_MET_MSG.format(key, ver, req_ver))
  RuntimeError:
  numpy is installed but older (1.14.5) than required (1.17). You must manually
  upgrade numpy before installing or install into a fresh virtualenv.
  
  ----------------------------------------
WARNING: Discarding git+https://github.com/statsmodels/statsmodels.git. Command errored out with exit status 1: /opt/hostedtoolcache/Python/3.7.12/x64/bin/python /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpuzaz9kp1 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /opt/hostedtoolcache/Python/3.7.12/x64/bin/python /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpuzaz9kp1 Check the logs for full command output.
```

GitHub Actions log: https://github.com/mlflow/mlflow/runs/4736147038?check_suite_focus=true#step:9:1

<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by bashtage** [comment]
Probably a result of trying oldest numpy version in pyproject yesterday. Might need to revert.

**Comment by bashtage** [comment]
Is this in an empty environment? Which os?

**Comment by harupy** [comment]
@bashtage Thanks for the quick response.

> Is this in an empty environment?
Yes

> Which os?
We observed this issue in Ubuntu: https://github.com/mlflow/mlflow/runs/4736147038?check_suite_focus=true#step:9:44

**Comment by harupy** [comment]
Here's a dockerfile to reproduce the issue:

```dockerfile
FROM python:3.7

RUN pip install git+https://github.com/statsmodels/statsmodels.git
```

**Comment by harupy** [comment]
With `oldest-supported-numpy`, pip attempts to build `statsmodels` with `numpy==1.14.5` but `1.14.5` is older the minimum version that `statsmodels` requires.

**Comment by bashtage** [comment]
Should be fixed now.  Please let me know if you have any further issues.

**Comment by harupy** [comment]
confirmed it's fixed. Thanks!
