### ISSUE TITLE
The xvals arg in smoothers_lowess gets ValueError

### ISSUE THREAD

**Issue by shuzhao-li** [statsmodels/statsmodels#8046]
#### Describe the bug

[A clear and concise description of what the bug is. This should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Code Sample, a copy-pastable example if possible

```
python3
Python 3.7.4 (default, Nov  2 2019, 13:31:25) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin

>>> import statsmodels
>>> statsmodels.__version__
'0.13.1'

>>> import numpy as np

>>> from statsmodels.nonparametric.smoothers_lowess import lowess

>>> np.ascontiguousarray(xvals)
array([ 6, 24, 25, 35, 31, 37, 38, 38, 38, 38, 39])
>>> 
>>> ff = lowess(yy3, xx3, frac= .2, it=1, xvals=None)
>>> 
>>> ff = lowess(yy3, xx3, frac= .2, it=1, xvals=yy3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shuzhao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/statsmodels/nonparametric/smoothers_lowess.py", line 241, in lowess
    frac=frac, it=0, delta=delta, given_xvals=True)
  File "statsmodels/nonparametric/_smoothers_lowess.pyx", line 24, in statsmodels.nonparametric._smoothers_lowess.lowess
ValueError: Buffer dtype mismatch, expected 'DTYPE_t' but got 'long'

```

**Comment by bashtage** [comment]
Cast your array to floats.

**Comment by shuzhao-li** [comment]
Yes that fix worked. Thanks!
