### ISSUE TITLE
`statsmodels.formula.api.ols` and `Python 3.11.1`

### ISSUE THREAD

**Issue by JasonMendoza2008** [statsmodels/statsmodels#8632]
#### Describe the bug

`from statsmodels.formula.api import ols` doesn't work on `Python 3.11.1`

#### Code Sample, a copy-pastable example if possible
```python
from statsmodels.formula.api import ols
```
After doing `pip install statsmodels`

####
This https://github.com/statsmodels/statsmodels/issues/8287 issue is closed so I thought `statsmodels` worked on Python 3.11?

####
Traceback:

```
Traceback (most recent call last):
  File "C:\Users\lhott\Documents\Formation scolaire\These\Travail\Foie divergence\stats.py", line 20, in <module>
    from statsmodels.formula.api import ols   # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhott\virtualenv\stats3.11\Lib\site-packages\statsmodels\formula\__init__.py", line 2, in <module>
    from .formulatools import handle_formula_data
  File "C:\Users\lhott\virtualenv\stats3.11\Lib\site-packages\statsmodels\formula\formulatools.py", line 2, in <module>
    from patsy import dmatrices, NAAction
  File "C:\Users\lhott\virtualenv\stats3.11\Lib\site-packages\patsy\__init__.py", line 77, in <module>
    import patsy.highlevel
  File "C:\Users\lhott\virtualenv\stats3.11\Lib\site-packages\patsy\highlevel.py", line 19, in <module>
    from patsy.design_info import DesignMatrix, DesignInfo
  File "C:\Users\lhott\virtualenv\stats3.11\Lib\site-packages\patsy\design_info.py", line 38, in <module>
    from patsy.desc import ModelDesc, Term
  File "C:\Users\lhott\virtualenv\stats3.11\Lib\site-packages\patsy\desc.py", line 14, in <module>
    from patsy.eval import EvalEnvironment, EvalFactor
  File "C:\Users\lhott\virtualenv\stats3.11\Lib\site-packages\patsy\eval.py", line 36, in <module>
    _ALL_FUTURE_FLAGS = _all_future_flags()
                        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lhott\virtualenv\stats3.11\Lib\site-packages\patsy\eval.py", line 32, in _all_future_flags
    if feature.getMandatoryRelease() > sys.version_info:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'sys.version_info'
```

**Comment by JasonMendoza2008** [comment]
I've deleted my virtual environment, and recreated it, it now works. I don't really know what happened.

**Comment by jameslin101** [comment]
I'm having the same issue
