### ISSUE TITLE
0.13.5: documentation not ready for sphonx 6.x?

### ISSUE THREAD

**Issue by kloczek** [statsmodels/statsmodels#8836]
Looks like it is not possible to build `statsmodels` documentation using latest sphinx 6.x
```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v6.2.0
making output directory... done
[autosummary] generating autosummary for: about.rst, anova.rst, api-structure.rst, api.rst, contingency_tables.rst, contrasts.rst, datasets/index.rst, dev/dataset_notes.rst, dev/examples.rst, dev/get_involved.rst, ..., release/version0.9.rst, rlm.rst, rlm_techn1.rst, sandbox.rst, statespace.rst, stats.rst, tools.rst, tsa.rst, user-guide.rst, vector_ar.rst

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autosummary/generate.py", line 455, in generate_autosummary_docs
    name, obj, parent, modname = import_by_name(entry.name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py", line 659, in import_by_name
    raise ImportExceptionGroup('no module named %s' % ' or '.join(tried), exceptions)
sphinx.ext.autosummary.ImportExceptionGroup: no module named statsmodels.base.distributed_estimation.DistributedModel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py", line 818, in process_generate_options
    generate_autosummary_docs(genfiles, suffix=suffix, base_path=app.srcdir,
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autosummary/generate.py", line 460, in generate_autosummary_docs
    name, obj, parent, modname = import_ivar_by_name(entry.name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py", line 717, in import_ivar_by_name
    real_name, obj, parent, modname = import_by_name(name, prefixes, grouped_exception)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py", line 659, in import_by_name
    raise ImportExceptionGroup('no module named %s' % ' or '.join(tried), exceptions)
sphinx.ext.autosummary.ImportExceptionGroup: no module named statsmodels.base.distributed_estimation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 341, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function process_generate_options at 0x7fca491280d0> for event 'builder-inited' threw an exception (exception: no module named statsmodels.base.distributed_estimation)

Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x7fca491280d0> for event 'builder-inited' threw an exception (exception: no module named statsmodels.base.distributed_estimation)
```

**Comment by bashtage** [comment]
Sm is pinned. sphinx>=5,<6 for now.

**Comment by bashtage** [comment]
I think there aren't likely to be any more 0.13 releases since we are hoping to have 0.14 out this week.

**Comment by kloczek** [comment]
That is ok 😄 
It would be sort out this issue no matter to which one version it iwqll go 😋

**Comment by kloczek** [comment]
Can you tell ET of next release? (just asking to coordinate that with other steps)

**Comment by bashtage** [comment]
Rc is out now, expect 2 weeks for 0.14.0 release/
