### ISSUE TITLE
statsmodels.tools.sm_exceptions.X13Error: ERROR: Number of user-defined X elements= 166 not equal to a multiple of the number of columns= 4

### ISSUE THREAD

**Issue by ahbon123** [statsmodels/statsmodels#8935]
My test data has two columns M0 and exog (You can download the X13 software and test data from [this link](https://www.dropbox.com/s/v4adf86g2rqzan5/X13_data.zip?dl=0)).

```
import statsmodels.api as sm
import pandas as pd
import numpy as np
import os

X13PATH = r'D:\data\X13'
os.chdir(X13PATH)
os.environ['X13PATH'] = X13PATH
print(os.environ['X13PATH'])

file_path = '../test_data/X13_test_data.xlsx'
sheet_name = 'Sheet1'

df = pd.read_excel(file_path, sheet_name=sheet_name, index_col='date')
print(df.head(5))

df.index = pd.to_datetime(df.index)
# df = df.rename(columns={'festival_factor': 'exog', 'M0': 'endog'})
res = sm.tsa.x13_arima_analysis(endog=df['M0'], exog=df['exog'], x12path=X13PATH, print_stdout=True)
# res = sm.tsa.x13_arima_analysis(endog=df['M0'], x12path=X13PATH, print_stdout=True)
print(res.seasadj)
print(res.plot)
```
Out:

```
                  M0      exog
date                          
2009-07-31  34239.30  0.000000
2009-08-31  34406.62  0.000000
2009-09-30  36787.89  0.333333
2009-10-31  35730.23  0.516129
2009-11-30  36343.86  0.000000

Traceback (most recent call last):
  File "D:\data\X13_test.py", line 19, in <module>
    res = sm.tsa.x13_arima_analysis(endog=df['M0'], exog=df['exog'], x12path=X13PATH, print_stdout=True)
  File "C:\Users\LSTM\AppData\Roaming\Python\Python310\site-packages\pandas\util\_decorators.py", line 210, in wrapper
    return func(*args, **kwargs)
  File "D:\Program Files\anaconda3\lib\site-packages\statsmodels\tsa\x13.py", line 518, in x13_arima_analysis
    _check_errors(errors)
  File "D:\Program Files\anaconda3\lib\site-packages\statsmodels\tsa\x13.py", line 201, in _check_errors
    raise X13Error(errors)
statsmodels.tools.sm_exceptions.X13Error: ERROR: Number of user-defined X elements= 166
        not equal to a multiple of the number of columns=  4.
```
I use `sm.tsa.x13_arima_analysis(endog=df['M0'], exog=df['exog'], x12path=X13PATH, print_stdout=True)` to perform X13 ARIMA on `M0 `For seasonal adjustment, the `exog `column is used as an exogenous variable, but an error occurs: `statsmodels.tools.sm_exceptions.X13Error: ERROR: Number of user-defined X elements= 166 not equal to a multiple of the number of columns= 4.`

My analysis found that the main cause of the error is caused by `exog=df['exog']`, because `sm.tsa.x13_arima_analysis(endog=df['M0'], x12path=X13PATH, print_stdout=True)` can run normally.

**Comment by josef-pkt** [comment]
(I'm on vacation and cannot try out anything)

Maybe `exog` needs to be a `DataFrame` and not a `Series`.
you could try
`sm.tsa.x13_arima_analysis(endog=df['M0'], exog=df[['exog']], x12path=X13PATH, print_stdout=True)`

**Comment by ahbon123** [comment]
Thanks for helping me to deal with this issue. After I changed code to `sm.tsa.x13_arima_analysis(endog=df['M0'], exog=df[['exog']], x12path=X13PATH, print_stdout=True)`, it generates a new error:

```
Traceback (most recent call last):
  File "D:\EconomicTSProcessor\X13_test.py", line 35, in <module>
    res = sm.tsa.x13_arima_analysis(endog=df['M0'], exog=df[['exog']], x12path=X13PATH, print_stdout=True)
  File "C:\Users\LSTM\AppData\Roaming\Python\Python310\site-packages\pandas\util\_decorators.py", line 210, in wrapper
b''
    return func(*args, **kwargs)
  File "D:\Program Files\anaconda3\lib\site-packages\statsmodels\tsa\x13.py", line 518, in x13_arima_analysis
    _check_errors(errors)
  File "D:\Program Files\anaconda3\lib\site-packages\statsmodels\tsa\x13.py", line 201, in _check_errors
    raise X13Error(errors)
statsmodels.tools.sm_exceptions.X13Error: ERROR: forecasts end date, 2024.Apr, must end on or before 
        user-defined regression variables end date, 2023.Apr.
```

**Comment by josef-pkt** [comment]
I have not looked at the details. However

The error message indicates that `exog` is not available for the forecast horizon.
To forecast with `exog`, the values of the regression variable needs to be available for the forecast periods. Because `exog` are not forecast by the model, the user needs to provide those values for the forecast horizon.
That's for example easy if those are calendar events, like season, holidays, ..., but needs to be predicted outside of the model for other `exog`.

To check, you could limit the endog to shorten the sample period and use the extra exog periods for the forecast periods.

**Comment by ahbon123** [comment]
Thank you. Would you mind testing it with the data and code I provided in the link at the beginning of the question? I took the first 10 rows of `df` for testing (`df = df.head(10)`), and an error occurred:` statsmodels.tools.sm_exceptions.X13Error: ERROR: Series to be modeled and/or seasonally adjusted must have at least 3 complete years of data .` If I take the first 36 rows for testing, the result is as follows: `statsmodels.tools.sm_exceptions.X13Error: ERROR: forecasts end date, 2013.Jun, must end on or before user-defined regression variables end date, 2012.Jun.`
My data `df `is like this:

 ```
                  M0 exog
date
2009-07-31 34239.30 0.000000
2009-08-31 34406.62 0.000000
2009-09-30 36787.89 0.333333
2009-10-31 35730.23 0.516129
2009-11-30 36343.86 0.000000
...
```

**Comment by bashtage** [comment]
This was already fixed in commit 51f430373 (BUG: Fix when exog is Series and its name have multiple chars, 2022-07-13), which predates this report - the reporter was on an older statsmodels version. Current code in statsmodels/tsa/x13.py wraps exog.name correctly before joining. Closing as fixed.
