### ISSUE TITLE
STL Decomposition Error after upgrading to version 0.14.0

### ISSUE THREAD

**Issue by MiguelGarcaoSilva** [statsmodels/statsmodels#9042]
#### Describe the bug

My application uses STL from statsmodels.tsa.seasonal to perform Time-Series Decomposition. It works perfectly when I use the version of statsmodels==0.13.2, but when I upgraded to version 0.14.0 it throws a ValueError on the endog.

<details>

```python
>>> from statsmodels.datasets import co2
>>> import matplotlib.pyplot as plt
>>> from pandas.plotting import register_matplotlib_converters
>>> register_matplotlib_converters()
>>> data = co2.load().data
>>> data = data.resample('M').mean().ffill()
>>> from statsmodels.tsa.seasonal import STL
>>> res = STL(data).fit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "statsmodels/tsa/stl/_stl.pyx", line 212, in statsmodels.tsa.stl._stl.STL.__init__
  File "/home/miguel/.local/lib/python3.8/site-packages/statsmodels/tools/validation/validation.py", line 147, in array_like
    raise ValueError(msg)
ValueError: endog must have ndim <= 1

</details>


#### Expected Output

I would expect the STL to perform without throwing "ValueError: endog must have ndm <=1"

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

dashboard_1  | INSTALLED VERSIONS
dashboard_1  | ------------------
dashboard_1  | Python: 3.8.16.final.0
dashboard_1  | OS: Linux 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64
dashboard_1  | byteorder: little
dashboard_1  | LC_ALL: None
dashboard_1  | LANG: C.UTF-8
dashboard_1  | 
dashboard_1  | statsmodels
dashboard_1  | ===========
dashboard_1  | 
dashboard_1  | Installed: 0.14.0 (/usr/local/lib/python3.8/site-packages/statsmodels)
dashboard_1  | 
dashboard_1  | Required Dependencies
dashboard_1  | =====================
dashboard_1  | 
dashboard_1  | cython: 0.29.21 (/usr/local/lib/python3.8/site-packages/Cython)
dashboard_1  | numpy: 1.20.0 (/usr/local/lib/python3.8/site-packages/numpy)
dashboard_1  | scipy: 1.5.0 (/usr/local/lib/python3.8/site-packages/scipy)
dashboard_1  | pandas: 1.4.3 (/usr/local/lib/python3.8/site-packages/pandas)
dashboard_1  |     dateutil: 2.8.2 (/usr/local/lib/python3.8/site-packages/dateutil)
dashboard_1  | patsy: 0.5.3 (/usr/local/lib/python3.8/site-packages/patsy)
dashboard_1  | 
dashboard_1  | Optional Dependencies
dashboard_1  | =====================
dashboard_1  | 
dashboard_1  | matplotlib: 3.7.1 (/usr/local/lib/python3.8/site-packages/matplotlib)
dashboard_1  |     backend: agg 
dashboard_1  | cvxopt: Not installed
dashboard_1  | joblib: 1.3.2 (/usr/local/lib/python3.8/site-packages/joblib)
dashboard_1  | 
dashboard_1  | Developer Tools
dashboard_1  | ================
dashboard_1  | 
dashboard_1  | IPython: Not installed
dashboard_1  |     jinja2: 3.1.2 (/usr/local/lib/python3.8/site-packages/jinja2)
dashboard_1  | sphinx: Not installed
dashboard_1  |     pygments: Not installed
dashboard_1  | pytest: Not installed
dashboard_1  | virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
You can call `squeeze()` as a workaround when passing 2d data.

**Comment by MiguelGarcaoSilva** [comment]
> You can call `squeeze()` as a workaround when passing 2d data.

Thank you for your reply.  But the same data with the same format works for both seasonal_decompose and the new MSTL statsmodels.tsa.seasonal methods.

**Comment by ixfd64** [comment]
Another temporary solution is to pass the data as a `Series` to the `STL()` function.

`res = STL(data['<column name>']).fit()`

**Comment by bashtage** [comment]
Yes, any 1-d array or array-like should work, including a `pd.Series`.
