### ISSUE TITLE
DynamicFactorMQ is not working 

### ISSUE THREAD

**Issue by msh855** [statsmodels/statsmodels#9062]
I am running [this example](https://www.chadfulton.com/topics/statespace_large_dynamic_factor_models.html) 

In the past I had no problems replicating tis example. Now it seems has something changed and I get the following errors when I  try to create the DFM object: 

```

# Construct the dynamic factor model
model = sm.tsa.DynamicFactorMQ(
    endog_m, endog_quarterly=endog_q,
    factors=factors, factor_orders=factor_orders,
    factor_multiplicities=factor_multiplicities)


```
```

Traceback (most recent call last):
  File "/Users/safishajjouz/opt/anaconda3/envs/myport_management_env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-55-40928c00cd95>", line 2, in <module>
    model = sm.tsa.DynamicFactorMQ(
  File "/Users/safishajjouz/opt/anaconda3/envs/myport_management_env/lib/python3.8/site-packages/statsmodels/tsa/statespace/dynamic_factor_mq.py", line 1320, in __init__
    s = self._s = DynamicFactorMQStates(
  File "/Users/safishajjouz/opt/anaconda3/envs/myport_management_env/lib/python3.8/site-packages/statsmodels/tsa/statespace/dynamic_factor_mq.py", line 443, in __init__
    self.factor_block_orders.append(default_block_orders))
  File "/Users/safishajjouz/opt/anaconda3/envs/myport_management_env/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'append'
```

**Comment by SuperMayo** [comment]
Which version of pandas are you using? I think it is related to Pandas>2.0 [deprecation of append() in favor of concat()](https://github.com/pandas-dev/pandas/issues/35407)

**Comment by motheeyue** [comment]
I met the same issue with pandas 2.2.2.

**Comment by msh855** [comment]
Yes, it relates to the pandas version. How are we progressing with the merge ? I see no progress with the pull request.

**Comment by mboldin** [comment]
I updated my statsmodel install using pip --upgrade  to 0.14.4 and did not get this change. The Series append  deprecated error persists. Replacing the  tsa statespace dynamic_factor_mq .py file in my local library fixed the error and let me estimate a model with the factor_orders option
