### ISSUE TITLE
`MultinomialResultsWrapper.score_test` crashes due to undefined function

### ISSUE THREAD

**Issue by Ge0rges** [statsmodels/statsmodels#9273]
#### Describe the bug
`statsmodels.discrete.discrete_model.MultinomialResultsWrapper.score_test` crashes due to the following function call in this traceback:

```
Traceback (most recent call last):
  File "/home/gio/Downloads/pycharm-2024.1.2/plugins/python/helpers-pro/pydevd_asyncio/pydevd_asyncio_utils.py", line 117, in _exec_async_code
    result = func()
             ^^^^^^
  File "<input>", line 1, in <module>
  File "/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py", line 4665, in score_test
    res = pinfer.score_test(self, exog_extra=exog_extra,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/statsmodels/base/_parameter_inference.py", line 234, in score_test
    score_factor = model.score_factor(params_constrained)
                   ^^^^^^^^^^^^^^^^^^
AttributeError: 'MNLogit' object has no attribute 'score_factor'
```

#### Code Sample, a copy-pastable example if possible

```
import pandas as pd
import numpy as np
import statsmodels.api as sm

# Sample DataFrame
data = {
    'name': [1, 2, 1, 2, 2],  # Changed 'name' column to integers
    'feature_1': np.random.randn(5),
    'feature_2': np.random.randn(5),
    'feature_3': np.random.randn(5),
    'sample_0': np.random.randn(5),
    'sample_1': np.random.randn(5),
}

df = pd.DataFrame(data)

# Get features
t = df['sample_1']
X_restricted = pd.concat([df['name'], df['sample_0']], axis=1)
y = df.iloc[:, 1:-2]

X_restricted = sm.add_constant(X_restricted)
restricted_model = sm.MNLogit(y, X_restricted).fit(method="lbfgs")
score_test_result = restricted_model.score_test(exog_extra=t)
```
The issue is found in the latest release version.

#### Expected Output

No crash, output as defined in [the docs](https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.MultinomialResults.score_test.html#statsmodels.discrete.discrete_model.MultinomialResults.score_test)

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.12.3.final.0
OS: Linux 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64
byteorder: little
LC_ALL: None
LANG: en_CA.UTF-8

statsmodels
===========

Installed: 0.14.2 (/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.26.4 (/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/numpy)
scipy: 1.13.1 (/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/scipy)
pandas: 2.2.2 (/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/pandas)
    dateutil: 2.9.0 (/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/dateutil)
patsy: 0.5.6 (/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.8.4 (/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/matplotlib)
    backend: TkAgg 
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: Not installed
    jinja2: 3.1.4 (/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/jinja2)
sphinx: Not installed
    pygments: Not installed
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
most likely I never checked whether score_test works for MNLogit
#7707 postestimation for MNLogit is mostly empty (not checked, not implemented)

The method is generically implemented.

MNLogit will need special code, because one additional exog variable adds several additional parameters

quick look

score_obs has
`return (firstterm[:,:,None] * self.exog[:,None,:]).reshape(self.exog.shape[0], -1)`

so `firstterm` should be a multivariate score_factor.
Hessian implementation is more difficult and I don't see what the "hessian_factor" would be

workaround
it is likely that the version of score_test that uses restricted params in full model works. That should not require the score_factor and score_obs, it should use score_obs and hessian instead.
But I'm not sure I ever checked this for MNLogit either. (and I don't remember right away how to do that.)

temporarily prio-high to check whether we can easily fix this.

question to your usecase
your null hypothesis is that exog_extra has no affect on any of the levels of endog?
For score_test, it should be possible also to check that an exog_extra has no effect on a specific level of endog instead of on all levels.

**Comment by Ge0rges** [comment]
You'll have to forgive my primitive understanding of the statistics here as I attempt to answer.

My goal ultimately is to understand whether two tables are identical or not (we've interacted on [this](https://stackoverflow.com/questions/78525705/getting-rao-score-from-mnlogit-in-statsmodels) SO question). That is I  would like to know if my two tables are different by comparing a model with all the classes, and a restricted one with a class removed (I believe this is the correct approach but could be mistaken).

I've also tried the following which I think is what you mean when you say 

> version of score_test that uses restricted params in full model

which crashes with a separate issue, but because I am unsure whether I am correctly using this function this may not be a bug. I'll report it here as it could be useful to you.

```
    import pandas as pd
    import numpy as np
    import statsmodels.api as sm

    # Sample DataFrame
    data = {
        'name': [1, 2, 1, 2, 2],  # Changed 'name' column to integers
        'feature_1': np.random.randn(5),
        'feature_2': np.random.randn(5),
        'feature_3': np.random.randn(5),
        'sample_0': np.random.randn(5),
        'sample_1': np.random.randn(5),
    }
    df = pd.DataFrame(data)

    # Get features
    X = pd.concat([df['name'], df['sample_0'], df['sample_1']], axis=1)
    X_restricted = pd.concat([df['name'], df['sample_0']], axis=1)
    y = df.iloc[:, 1:-2]

    # Add constant for intercept
    X = sm.add_constant(X)
    X_restricted = sm.add_constant(X_restricted)

    # Fit the logistic regression models
    model = sm.MNLogit(y, X).fit(method="lbfgs")
    restricted_model = sm.MNLogit(y, X_restricted).fit(method="lbfgs")

    # Get the rao score
    score_test_result = model.score_test(params_constrained=np.asarray(restricted_model.params), k_constraints=1)
```

Traceback:
```
Traceback (most recent call last):
  File "/home/gio/Downloads/pycharm-2024.1.2/plugins/python/helpers/pydev/pydevd.py", line 2238, in <module>
    main()
  File "/home/gio/Downloads/pycharm-2024.1.2/plugins/python/helpers/pydev/pydevd.py", line 2220, in main
    globals = debugger.run(setup['file'], None, None, is_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gio/Downloads/pycharm-2024.1.2/plugins/python/helpers/pydev/pydevd.py", line 1530, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gio/Downloads/pycharm-2024.1.2/plugins/python/helpers/pydev/pydevd.py", line 1537, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gio/Downloads/pycharm-2024.1.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/gio/Documents/Methylation-analysis/willis_dmr_analysis.py", line 167, in <module>
    run_analysis("34H_compare_5", "dmr_by_gene", data_dir, fig_savepath="plots_5")
  File "/home/gio/Documents/Methylation-analysis/willis_dmr_analysis.py", line 158, in run_analysis
    plot_pairwise_results(pairwise_epigenomes(combined_methyl_data, logistic_regression_pvalue), genome_name + " using statsmodels score")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gio/Documents/Methylation-analysis/willis_dmr_analysis.py", line 127, in pairwise_epigenomes
    results[sample1, sample2] = function(sample_pair)
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gio/Documents/Methylation-analysis/_statistics.py", line 65, in logistic_regression_pvalue
    score_test_result = model.score_test(params_constrained=np.asarray(restricted_model.params), k_constraints=1)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py", line 4665, in score_test
    res = pinfer.score_test(self, exog_extra=exog_extra,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/statsmodels/base/_parameter_inference.py", line 206, in score_test
    score = model.score(params_constrained, **score_kwd)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gio/miniforge3/envs/python/lib/python3.12/site-packages/statsmodels/discrete/discrete_model.py", line 3121, in score
    params = params.reshape(self.K, -1, order='F')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 9 into shape (4,newaxis)
```

**Comment by josef-pkt** [comment]
> My goal ultimately is to understand whether two tables are identical or not

You can use the Wald tests on the full model to test the parameter restriction.
Those should be available for all models.

score_test was added more recently and still is not supported in all models.


The constraints in the full version needs to have params for the full model, with zeros in the position of the parameters that are not in the reduced model

I guess  (I changed the example to 3 levels, i.e. 2 non-reference levels)
```
params_r = np.concatenate((restricted_model.params.to_numpy(), [[0, 0]]), axis=0).ravel("f")
score_test_result = model.score_test(params_constrained=np.asarray(params_r), k_constraints=2)
```

**Comment by Ge0rges** [comment]
Thank you for that clarification and suggestion. I've chosen to use the score test as I believe it to be more robust for my dataset with a small number of observations.

**Comment by josef-pkt** [comment]
> I've chosen to use the score test as I believe it to be more robust for my dataset with a small number of observations. I will use the full version with corrected parameters as indicated.

Yes, in many cases like binomial with small counts the score_test is often a bit conservative (underrejects) while the wald tests are a bit liberal (overrejects)

You still have to check that the results look correct, given that I'm not sure how the score_test exactly works in MNLogit.
and check how endog y is supposed to be specified

Score test and wald test still should have similar results, with a bit smaller p-value(s) in wald tests.

(I'm mostly using Poisson, Logit and GLM to check the enhancements that I add to statsmodels and I'm not always very familiar with how it works with other models that don't have the same simple pattern, like MNLogit or zero-inflated count models)

**Comment by Ge0rges** [comment]
Thank you that's noted. I will run a wald test and compare results and report back with some more detailed information about how I ran them and results.

**Comment by josef-pkt** [comment]
another way to implement score test for variable addition 

If score_obs and hessian were to take a new exog (endog not needed) that have the same rows (row index) as self.exog with extra columns, then we can just compute score_test for the full unconstrained model from the reduced model.
(For out of sample evaluation we would also need extra arrays, offset, exposure, weights, ... , but for score_obs we would only need exog and exog_xxx e.g. exog_precision, but insample we could just reuse unspecified arrays)

I guess this would work also for other models where we don't have score and hessian factors, e.g. in some count models AFAIR.

I need to check unit test coverage for score_test by models
based on file search:

in discrete  
- tests.test_predict NBP and GPP 2 versions of score_test
- tests.test_sandwich_cov  assert between discrete, resp OLS, and GLM, looks like Poisson, Logit, Probit, Gauss

in genmod
- test_score_test GLM-Gaussian, GLM-Poisson, dispersion  test for poisson, conditional moment tests, Wooldridge, 
- test_glm
   - smoke test  
   - GLM-logit, assert against R values
   - GLM-gaussian, compare with OLS
- gee has separate implementation and unit tests
 
in othermod
- test_beta: compares two methods of score_test (keyword versions `exog_extra` and `params_constrained`)

several unit tests use the function `from statsmodels.base._parameter_inference import score_test` and some models don't have the method.
 
AFAIR, I tried the `params_constrained` version also for other models, but I don't see unit tests.  ZI, ...?

**Comment by Ge0rges** [comment]
I tried to run a small example to test your suggestion and the Wald score, here's what I did:

```
X = pd.DataFrame({
        'name': [1, 1, 1, 2, 2],
        'sample_0': [1, 0, 0, 1, 0],
        'sample_1': [0, 1, 1, 0, 1]
    })

    # Creating the X_restricted DataFrame
    X_restricted = pd.DataFrame({
        'name': [1, 1, 1, 2, 2],
        'sample_0': [1, 0, 0, 1, 0]
    })

    # Creating the y DataFrame
    y = pd.DataFrame({
        'class1': [0, 0, 0, 1, 1],
        'class2': [0, 0, 0, 0, 0],
        'class3': [0, 0, 0, 0, 0],
        'class4': [1, 1, 1, 0, 0]
    })

    # Add constant for intercept
    X = sm.add_constant(X)
    X_restricted = sm.add_constant(X_restricted)

    # Fit the logistic regression models
    model = sm.MNLogit(y, X).fit()
    restricted_model = sm.MNLogit(y, X_restricted).fit()

    # Get the rao score
    params_r = np.concatenate((restricted_model.params.to_numpy(), np.zeros((1, X.shape[1]-1))), axis=0).ravel("f")
    score_test_result = model.score_test(params_constrained=params_r, k_constraints=1)

    # Make the restriction matrix
    num_classes = y.shape[1] - 1
    num_params_per_class = X.shape[1]

    R = np.zeros((num_classes, num_classes*num_params_per_class))
    for i in range(num_classes):
        R[i, i * num_params_per_class + 3] = 1

    wald_test = model.wald_test(R)
```

Perhaps there is something fundamentally wrong with my example, or a bug with my code because the Wald test fails with `ValueError: r_matrix performs f_test for using dimensions that are asymptotically non-normal`. The output of the first fit:

```
Optimization terminated successfully.
         Current function value: nan
         Iterations 22
/Users/GeorgesKanaan/micromamba/envs/jupyter/lib/python3.10/site-packages/statsmodels/discrete/discrete_model.py:3025: RuntimeWarning: overflow encountered in exp
  eXB = np.column_stack((np.ones(len(X)), np.exp(X)))
/Users/GeorgesKanaan/micromamba/envs/jupyter/lib/python3.10/site-packages/statsmodels/discrete/discrete_model.py:3026: RuntimeWarning: invalid value encountered in divide
  return eXB/eXB.sum(1)[:,None]
```

and second fit:
```
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.000000
         Iterations: 35
/Users/GeorgesKanaan/micromamba/envs/jupyter/lib/python3.10/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
```

I noticed the Wald test implicitly assumes that the first class is a reference class, though my understanding of this is limited I don't believe my particular case has a reference class though that is perhaps beyond the scope of this issue. Just wanted to post this update re: comparing the score and Wald tests.

**Comment by josef-pkt** [comment]
Make a larger example add more observations. You have fewer observations than parameters.
that's the reason for convergence warning AFAICS

I don't have a guess for the first problem and will need to try out the example and check what causes the error

**Comment by josef-pkt** [comment]
changing your example to have full rank cov_params without nans

The following example works but test statistics for both wald and score-test are around 1e-15 or 1e-16 (p-value=1), so they are difficult to compare in relative terms. The example just shuffles exog to avoid perfect prediction or other numerical problems.

To see better comparison of wald and score tests, the extra exog should have some small effect so pvalues are in the 0.01 to 0.2 range.
We don't have a quick way to simulate mnlogit models.  #9286

```
r = 10
X = pd.DataFrame({
    'name': [1, 1, 1, 2, 2] * r,
    'sample_0': [1, 0, 0, 1, 0] * r,
    'sample_1': [0, 1, 1, 0, 1] * r
})

X = X.sample(frac=1).reset_index(drop=True)

# Creating the X_restricted DataFrame
X_restricted = pd.DataFrame({
    'name': [1, 1, 1, 2, 2] * r,
    'sample_0': [1, 0, 0, 1, 0] * r
})
X_restricted = X[["name", "sample_0"]]

# Creating the y DataFrame
y = pd.DataFrame({
    'class1': [0, 0, 0, 0, 1] * r,
    'class2': [0, 0, 0, 1, 0] * r,
    'class3': [0, 0, 1, 0, 0] * r,
    'class4': [1, 1, 0, 0, 0] * r
})

# Add constant for intercept
X = sm.add_constant(X)
X_restricted = sm.add_constant(X_restricted)

# Fit the logistic regression models
model = sm.MNLogit(y, X).fit()
restricted_model = sm.MNLogit(y, X_restricted).fit(maxiter=100)

# Get the rao score
params_r = np.concatenate((restricted_model.params.to_numpy(), np.zeros((1, X.shape[1]-1))), axis=0).ravel("f")
score_test_result = model.score_test(params_constrained=params_r, k_constraints=X.shape[1]-1)

# Make the restriction matrix
num_classes = y.shape[1] - 1
num_params_per_class = X.shape[1]

R = np.zeros((num_classes, num_classes*num_params_per_class))
for i in range(num_classes):
    R[i, i * num_params_per_class + 3] = 1

wald_test = model.wald_test(R)
wald_test, score_test_result
```
