### ISSUE TITLE
version 0.14.2 still incompatible wtih numpy 2.1.0

### ISSUE THREAD

**Issue by rgouveiamendes** [statsmodels/statsmodels#9332]
I am getting the following error using Marimo:

![image](https://github.com/user-attachments/assets/9f6769d7-1df3-4b92-8f24-dad20426f4e9)

I checked I am running the following versions of the packages:
```
numpy==2.1.0
statsmodels==0.14.2
```

If anyone wants to copy the code:
```python
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
```

Anyone facing the same issue?

**Comment by bashtage** [comment]
Can you post the full traceback.  Not us I think.

**Comment by rgouveiamendes** [comment]
Sure!

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/ric/.local/bin/marimo", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_cli/cli.py", line 309, in edit
    start(
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_server/start.py", line 176, in start
    server.run()
  File "/home/ric/.local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ric/.local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "/home/ric/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_server/api/auth.py", line 216, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/middleware/authentication.py", line 49, in __call__
    await self.app(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_server/api/middleware.py", line 64, in __call__
    return await self.app(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/routing.py", line 483, in handle
    await self.app(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/routing.py", line 371, in handle
    await self.app(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/ric/.local/lib/python3.10/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_server/api/endpoints/ws.py", line 86, in websocket_endpoint
    await WebsocketHandler(
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_server/api/endpoints/ws.py", line 457, in start
    get_session()
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_server/api/endpoints/ws.py", line 439, in get_session
    new_session = mgr.create_session(
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_server/sessions.py", line 660, in create_session
    self.sessions[session_id] = Session.create(
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_server/sessions.py", line 373, in create
    return cls(
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_server/sessions.py", line 401, in __init__
    self.kernel_manager.start_kernel()
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_server/sessions.py", line 239, in start_kernel
    self.kernel_task.start()  # type: ignore
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_runtime/runtime.py", line 1834, in launch_kernel
    asyncio.run(control_loop())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_runtime/runtime.py", line 1828, in control_loop
    await kernel.handle_message(request)
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_runtime/runtime.py", line 1661, in handle_message
    await self.run(request.execution_requests)
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_runtime/runtime.py", line 1153, in run
    await self._run_cells(
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_runtime/runtime.py", line 979, in _run_cells
    while cell_ids := await self._run_cells_internal(cell_ids):
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_runtime/runtime.py", line 1087, in _run_cells_internal
    await runner.run_all()
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_runtime/runner/cell_runner.py", line 549, in run_all
    run_result = await self.run(cell_id)
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_runtime/runner/cell_runner.py", line 340, in run
    return_value = execute_cell(
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_runtime/executor.py", line 108, in execute_cell
    return EXECUTION_TYPES[execution_type].execute_cell(cell, glbls, graph)
  File "/home/ric/.local/lib/python3.10/site-packages/marimo/_runtime/executor.py", line 170, in execute_cell
    exec(cell.body, glbls)
  File "/tmp/marimo_21770/__marimo__cell_MJUe_.py", line 4, in <module>
    import statsmodels.api as sm
  File "/home/ric/.local/lib/python3.10/site-packages/statsmodels/__init__.py", line 1, in <module>
    from statsmodels.compat.patsy import monkey_patch_cat_dtype
  File "/home/ric/.local/lib/python3.10/site-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/home/ric/.local/lib/python3.10/site-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/home/ric/.local/lib/python3.10/site-packages/statsmodels/tools/tools.py", line 6, in <module>
    import scipy.linalg
  File "/usr/lib/python3/dist-packages/scipy/linalg/__init__.py", line 198, in <module>
    from ._misc import *
  File "/usr/lib/python3/dist-packages/scipy/linalg/_misc.py", line 3, in <module>
    from .blas import get_blas_funcs
  File "/usr/lib/python3/dist-packages/scipy/linalg/blas.py", line 213, in <module>
    from scipy.linalg import _fblas
AttributeError: _ARRAY_API not found
```

**Comment by bashtage** [comment]
Your scipy isn't compatible.

**Comment by rgouveiamendes** [comment]
Thank you very much! It was exactly that.
