### ISSUE TITLE
statsmodel uses old scipy -> pythran -> gast chain that fails to recompile as of current

### ISSUE THREAD

**Issue by aosadchyy** [statsmodels/statsmodels#9350]
#### Describe the bug
Performing pip3 install statsmodels==0.14.2  without a readily available wheel package fails with the compilation error.  I tried older versions of statsmodels and got the same result. The reason seems to be in the older versions of scipy -> pythran -> gast depdendecies used in  statsmodels.

#### Code Sample, a copy-pastable example if possible

```python
pip3 install statsmodels==0.14.2 --no-binary :all:
```
<details>
As pip3 install progresses with compilation of binaries. It goes to install scipy  -> pythran, which then fails with the error 
AttributeError: module 'gast' has no attribute 'MatchStar'
The attribute is no longer available in the newer gast package versions, e.g. 0.5.3.  

Installing newer versions of scipy==1.12.0 or scipy==1.13.1 woks fine. 

pip3 install scipy==1.12.0 --no-binary :all:

Which leads me to a conclusion that whatever version statsmodels uses is older and cannot be longer compiled. 

```
pip3 install statsmodels==0.14.2 --no-binary :all:
...
            [780/1576] Generating scipy/stats/_hypotests_pythran with a custom command
            FAILED: scipy/stats/_hypotests_pythran.cpp
            /tmp/pip-build-env-y9l5wz_p/overlay/local/bin/pythran -E ../scipy/stats/_hypotests_pythran.py -o scipy/stats/_hypotests_pythran.cpp
            Traceback (most recent call last):
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/bin/pythran", line 8, in <module>
                sys.exit(run())
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/run.py", line 180, in run
                pythran.compile_pythranfile(args.input_file,
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/toolchain.py", line 481, in compile_pythranfile
                output_file = compile_pythrancode(module_name, fd.read(),
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/toolchain.py", line 399, in compile_pythrancode
                module, error_checker = generate_cxx(module_name, pythrancode, specs, opts,
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/toolchain.py", line 142, in generate_cxx
                pm, ir, docstrings = front_middle_end(module_name, code, optimizations,
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/toolchain.py", line 109, in front_middle_end
                refine(pm, ir, optimizations, report_times)
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/middlend.py", line 57, in refine
                pm.apply(FalsePolymorphism, node, run_times)
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/passmanager.py", line 243, in apply
                ret=a.apply(node)
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/passmanager.py", line 200, in apply
                new_node = self.run(node)
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/passmanager.py", line 189, in run
                n = super(Transformation, self).run(node)
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/passmanager.py", line 97, in run
                return self.visit(node)
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/passmanager.py", line 79, in visit
                return super(ContextManager, self).visit(node)
              File "/usr/lib/python3.10/ast.py", line 418, in visit
                return visitor(node)
              File "/usr/lib/python3.10/ast.py", line 494, in generic_visit
                value = self.visit(value)
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/passmanager.py", line 79, in visit
                return super(ContextManager, self).visit(node)
              File "/usr/lib/python3.10/ast.py", line 418, in visit
                return visitor(node)
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/pythran/transformations/false_polymorphism.py", line 55, in visit_FunctionDef
                if curr.name() != def_.name():
              File "/tmp/pip-build-env-y9l5wz_p/overlay/local/lib/python3.10/dist-packages/beniget/beniget.py", line 112, in name
                elif isinstance(self.node, (ast.MatchStar, ast.MatchAs)):
            AttributeError: module 'gast' has no attribute 'MatchStar'
            [781/1576] Compiling C++ object scipy/stats/_biasedurn.cpython-310-s390x-linux-gnu.so.p/biasedurn_stoc3.cpp.o
            [782/1576] Generating 'scipy/stats/_qmc_cy.cpython-310-s390x-linux-gnu.so.p/_qmc_cy.cpp'
            [783/1576] Generating 'scipy/stats/_boost/hypergeom_ufunc.cpython-310-s390x-linux-gnu.so.p/hypergeom_ufunc.cpp'
            [784/1576] Generating 'scipy/stats/_boost/nbinom_ufunc.cpython-310-s390x-linux-gnu.so.p/nbinom_ufunc.cpp'
            [785/1576] Generating 'scipy/stats/_sobol.cpython-310-s390x-linux-gnu.so.p/_sobol.c'
            [786/1576] Generating 'scipy/stats/_stats.cpython-310-s390x-linux-gnu.so.p/_stats.c'
            [787/1576] Compiling C++ object scipy/stats/_biasedurn.cpython-310-s390x-linux-gnu.so.p/meson-generated__biasedurn.cpp.o
            [788/1576] Compiling C++ object scipy/sparse/sparsetools/_sparsetools.cpython-310-s390x-linux-gnu.so.p/csr.cxx.o
            [789/1576] Compiling C++ object scipy/sparse/sparsetools/_sparsetools.cpython-310-s390x-linux-gnu.so.p/bsr.cxx.o
            ninja: build stopped: subcommand failed.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
```
</details>

**Comment by bashtage** [comment]
This is an issue for SciPy to fix if it wants. You can pin SciPy in your install command as needed, or gast. SciPy was for a long time hard to compile, and we only support compilation from an existing binary SciPy install.

**Comment by aosadchyy** [comment]
Soupy fixed it in later versions. Installing scipy==1.12.0 or scipy==1.13.1 from the source woks fine. Hence suggesting to update your dependencies for it.

**Comment by bashtage** [comment]
We try and keep the dependencies at least 2 years old to support the widest set of users.  Since there is no problem building against a wheel for 1.8 I think we won't move it forward.  I think this thread can be useful for anyone who needs to build fully from source so they will know to pin SciPy to be a appropriate.  

One could always install dependencies and the build with `--no-build-isolation`
