### ISSUE TITLE
AttributeError: module 'numpy.random' has no attribute 'mtrand' when trying to import statsmodels.api

### ISSUE THREAD

**Issue by cppt** [statsmodels/statsmodels#9373]
#### Describe the bug

Attempting to import statsmodels.api, getting the referenced error.  

Working within Spyder 
* Spyder version: 5.3.3  (conda)
* Python version: 3.9.13 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 6.8.0-45-generic

statsmodels version '0.14.3'

#### Code Sample, a copy-pastable example if possible
import statsmodels.api as sm
Traceback (most recent call last):

  File "/tmp/ipykernel_284942/2479605915.py", line 1, in <module>
    import statsmodels.api as sm

  File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/api.py", line 78, in <module>
    from . import datasets, distributions, iolib, regression, robust, tools

  File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/distributions/__init__.py", line 7, in <module>
    from .discrete import (

  File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/distributions/discrete.py", line 36, in <module>
    genpoisson_p = genpoisson_p_gen(name='genpoisson_p',

  File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 3225, in __init__
    super().__init__(seed)

  File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 643, in __init__
    self._random_state = check_random_state(seed)

  File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/_lib/_util.py", line 265, in check_random_state
    return np.random.mtrand._rand

AttributeError: module 'numpy.random' has no attribute 'mtrand'

#### Expected Output
Package imports successfully

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

Same error, below.  

import statsmodels.api as sm; sm.show_versions()
Traceback (most recent call last):

  File "/tmp/ipykernel_284942/3982767643.py", line 1, in <module>
    import statsmodels.api as sm; sm.show_versions()

  File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/api.py", line 78, in <module>
    from . import datasets, distributions, iolib, regression, robust, tools

  File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/distributions/__init__.py", line 7, in <module>
    from .discrete import (

  File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/distributions/discrete.py", line 36, in <module>
    genpoisson_p = genpoisson_p_gen(name='genpoisson_p',

  File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 3225, in __init__
    super().__init__(seed)

  File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 643, in __init__
    self._random_state = check_random_state(seed)

  File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/_lib/_util.py", line 265, in check_random_state
    return np.random.mtrand._rand

AttributeError: module 'numpy.random' has no attribute 'mtrand'

**Comment by bashtage** [comment]
This is a scipy issue.  Which scipy and bumpy are you trying to use?

**Comment by cppt** [comment]
@bashtage, showing:

```
scipy.__version__
Out[36]: '1.13.1'

numpy.__version__
Out[39]: '1.26.4'
```

**Comment by bashtage** [comment]
This isn't our issue to fix, closing as nothing we can do.

**Comment by josef-pkt** [comment]
This might be a installation or import issue. I don't find any indication that numpy did not have random.mtrand at any time.

Related (because I was surprised that numpy.random state is called just on import):
I never realized that distribution instances get a random state since 2014
https://github.com/scipy/scipy/pull/4129
in addition to the option in the `rvs` method.

Our subclasses of distributions like genpoisson_p_gen and the corresponding instances do not have an option in the `__init__` to set a seed or random state as instance attribute.
That means the instances will always have a global default instance.
With a single global instance, this should work as expected in the old style, e.g. setting seed will reset global instance but would not reset any user specified random state.
