### ISSUE TITLE
GAM: Documentation doesn't provide example on how to predict out of sample

### ISSUE THREAD

**Issue by eddyojb88** [statsmodels/statsmodels#9438]
#### Describe the bug

When predicting out of sample, I receive errors indicating that there is something incorrect about my input frame. My X_train and X_test have gone through a function that asserts that the X_train and X_test input feature dimensions are the same. 
It's really unclear what I'm supposed to do differently.

#### Code Sample, a copy-pastable example if possible

```python
        Xy_train = X_train.copy()
        Xy_train[kwargs['target_col']] = y_train

        continuous_X = Xy_train[continuous_features]
        bs = BSplines(continuous_X, df=[12] * len(continuous_features), degree=[3] * len(continuous_features))
        formula = f'{target_col} ~ ' + ' + '.join(X_feature_names)

        gam = GLMGam.from_formula(formula,
                                data=Xy_train, smoother=bs,
                                family=sm.families.Binomial()
                                )

        results = gam.fit()
        results.summary()

        y_test_pred_proba = results.predict(X_test) 
```
Errors:
<details>
Error when predicting:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/statsmodels/gam/generalized_additive_model.py", line 217, in predict
    predict_results = super().predict(ex, transform=False, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/statsmodels/base/model.py", line 1174, in predict
    predict_results = self.model.predict(self.params, exog, *args,
  File "/usr/local/lib/python3.10/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1012, in predict
    linpred = np.dot(exog, params) + offset + exposure
ValueError: shapes (109,15) and (48,) not aligned: 15 (dim 1) != 48 (dim 0)

</details>

Versions
```

INSTALLED VERSIONS
------------------
Python: 3.10.15.final.0
OS: Linux 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8

statsmodels
===========

Installed: 0.14.4 (/usr/local/lib/python3.10/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 2.1.3 (/usr/local/lib/python3.10/site-packages/numpy)
scipy: 1.14.1 (/usr/local/lib/python3.10/site-packages/scipy)
pandas: 2.2.3 (/usr/local/lib/python3.10/site-packages/pandas)
    dateutil: 2.9.0.post0 (/usr/local/lib/python3.10/site-packages/dateutil)
patsy: 1.0.1 (/usr/local/lib/python3.10/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: Not installed
cvxopt: Not installed
joblib: 1.4.2 (/usr/local/lib/python3.10/site-packages/joblib)

Developer Tools
================

IPython: Not installed
    jinja2: Not installed
sphinx: Not installed
    pygments: 2.18.0 (/usr/local/lib/python3.10/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed
```

</details>

**Comment by josef-pkt** [comment]
quick answer, not verified

https://www.statsmodels.org/dev/generated/statsmodels.gam.generalized_additive_model.GLMGamResults.predict.html
predict needs additionally `exog_smooth=continuous_X_oos`  with out of sample data for the splines

the splines should not be based on the same variables as those in the linear part.
splines encompass linear trend, so there will be collinearity if a spline variable is also included in the non-spline part

**Comment by josef-pkt** [comment]
one of my old notebooks for overview of GLMGAM
https://gist.github.com/josef-pkt/453de603b019143e831fbdd4dfb6aa30

there is also an example for predict is in #6487
